static constexpr const char* DEFAULT_SYNTAX_C =
    "// supported feature lists -----------------------------------------------------\n"
    "\n"
    "supported_apis = [\"simple\", \"generic\", \"record\"];\n"
    "supported_api_styles = [\"functions\", \"free-form\"];\n"
    "supported_code_models = [\"goto-label\", \"loop-switch\", \"recursive-functions\"];\n"
    "supported_targets = [\"code\", \"dot\", \"skeleton\"];\n"
    "supported_features = [\"nested-ifs\", \"bitmaps\", \"computed-gotos\", \"case-ranges\",\n"
    "    \"tags\", \"captures\", \"captvars\", \"vectorize-loops\", \"keywords\", \"keywords-archtime\"];\n"
    "\n"
    "\n"
    "// language-specific options ---------------------------------------------------\n"
    "\n"
    "semicolons = 1;\n"
    "backtick_quoted_strings = 0;\n"
    "single_quoted_strings = 0;\n"
    "indentation_sensitive = 0;\n"
    "wrap_blocks_in_braces = 1;\n"
    "special_escapes = \"\\a\\b\\f\\n\\r\\t\\v\\\\'\\\"\";\n"
    "\n"
    "\n"
    "// immutable configurations (command-line only options) ------------------------\n"
    "\n"
    "re2c:target = code;\n"
    "re2c:code-model = goto-label;\n"
    "re2c:input-encoding = ascii;\n"
    "re2c:date = 1;\n"
    "re2c:version = 1;\n"
    "re2c:conditions = 0;\n"
    "re2c:storable-state = 0;\n"
    "re2c:flex-syntax = 0;\n"
    "re2c:verbose = 0;\n"
    "re2c:line-dirs = 1;\n"
    "\n"
    "\n"
    "// mutable configurations ------------------------------------------------------\n"
    "\n"
    "re2c:api = simple;\n"
    "re2c:api:style = functions;\n"
    "re2c:api:sigil = \"@@\";\n"
    "re2c:YYGETCOND:naked = 0;\n"
    "re2c:YYSETCOND:naked = 0;\n"
    "re2c:YYSETCOND@cond = \"@@\";\n"
    "re2c:YYGETSTATE:naked = 0;\n"
    "re2c:YYSETSTATE:naked = 0;\n"
    "re2c:YYSETSTATE@state = \"@@\";\n"
    "re2c:YYFILL@len = \"@@\";\n"
    "re2c:YYFILL:naked = 0;\n"
    "re2c:YYFN = [\"<undefined-function-name>;<undefined-function-type>\"];\n"
    "re2c:yyfn:sep = \";\";\n"
    "re2c:yyfn:throw = \"\";\n"
    "re2c:yycond = \"yycond\";\n"
    "re2c:yyctable = \"yyctable\";\n"
    "re2c:yyaccept = \"yyaccept\";\n"
    "re2c:yytarget = \"yytarget\";\n"
    "re2c:yystate = \"yystate\";\n"
    "re2c:yynmatch = \"yynmatch\";\n"
    "re2c:yypmatch = \"yypmatch\";\n"
    "re2c:yyrecord = \"yyrecord\";\n"
    "re2c:yych = \"yych\";\n"
    "re2c:yych:conversion = 0;\n"
    "re2c:yych:literals = char-or-hex;\n"
    "re2c:yych:emit = (.code_model.recursive_functions ? 0 : 1);\n"
    "re2c:yybm = \"yybm\";\n"
    "re2c:yybm:hex = 0;\n"
    "re2c:yystable = \"\"; // deprecated\n"
    "re2c:header = \"\";\n"
    "re2c:eof = -1;\n"
    "re2c:sentinel = -1;\n"
    "re2c:yyfill = \"\";\n"
    "re2c:yyfill:enable = 1;\n"
    "re2c:yyfill:parameter = 1;\n"
    "re2c:yyfill:check = 1;\n"
    "re2c:tags = 0;\n"
    "re2c:tags:prefix = \"yyt\";\n"
    "re2c:captures = 0;\n"
    "re2c:captvars = 0;\n"
    "re2c:posix-captures = 0;\n"
    "re2c:posix-captvars = 0;\n"
    "re2c:invert-captures = 0;\n"
    "re2c:cond:abort = (.code_model.recursive_functions ? 1 : 0); // `abort()` requires include\n"
    "re2c:cond:prefix = \"yyc_\";\n"
    "re2c:cond:enumprefix = \"yyc\";\n"
    "re2c:cond:divider@cond = \"@@\";\n"
    "re2c:cond:goto@cond = \"@@\";\n"
    "re2c:state:abort = (.code_model.recursive_functions ? 1 : 0); // `abort()` requires include\n"
    "re2c:state:nextlabel = 0;\n"
    "re2c:bit-vectors = 0;\n"
    "re2c:debug-output = 0;\n"
    "re2c:computed-gotos = 0;\n"
    "re2c:computed-gotos:threshold = 9;\n"
    "re2c:computed-gotos:relative = 0;\n"
    "re2c:nested-ifs = 0;\n"
    "re2c:case-insensitive = 0;\n"
    "re2c:case-inverted = 0;\n"
    "re2c:case-ranges = 0;\n"
    "re2c:unsafe = 0;\n"
    "re2c:monadic = 0;\n"
    "re2c:vectorize:loops = 0;\n"
    "re2c:keywords = 0;\n"
    "re2c:keywords:token = \"\";\n"
    "re2c:encoding:ebcdic = 0;\n"
    "re2c:encoding:utf32 = 0;\n"
    "re2c:encoding:ucs2 = 0;\n"
    "re2c:encoding:utf16 = 0;\n"
    "re2c:encoding:utf8 = 0;\n"
    "re2c:encoding-policy = ignore;\n"
    "re2c:empty-class = match-empty;\n"
    "re2c:indent:string = \"\\t\";\n"
    "re2c:indent:top = 0;\n"
    "re2c:label:prefix = \"yy\";\n"
    "re2c:label:yyfill = \"yyFillLabel\";\n"
    "re2c:label:yyloop = \"\";\n"
    "re2c:label:yyNext = \"yyNext\";\n"
    "re2c:label:start = 0;\n"
    "\n"
    "\n"
    "// mutable code configuration --------------------------------------------------\n"
    "\n"
    "re2c:YYBACKUP = \"YYBACKUP\";\n"
    "re2c:YYBACKUPCTX = \"YYBACKUPCTX\";\n"
    "re2c:YYCONDTYPE = \"YYCONDTYPE\";\n"
    "re2c:YYCOPYMTAG = sigil \"{lhs} = \" sigil \"{rhs};\";\n"
    "re2c:YYCOPYSTAG = sigil \"{lhs} = \" sigil \"{rhs};\";\n"
    "re2c:YYCTXMARKER = (.api.record ? yyrecord \"->yyctxmarker\" : \"YYCTXMARKER\");\n"
    "re2c:YYCTYPE = \"YYCTYPE\";\n"
    "re2c:YYCURSOR = (.api.record ? yyrecord \"->yycursor\" : \"YYCURSOR\");\n"
    "re2c:YYDEBUG = \"YYDEBUG\";\n"
    "re2c:YYEND = \"YYEND\";\n"
    "re2c:YYFILL = \"YYFILL\";\n"
    "re2c:YYGETACCEPT = sigil \"{var}\";\n"
    "re2c:YYGETCOND = \"YYGETCONDITION\"; // historic default\n"
    "re2c:YYGETSTATE = \"YYGETSTATE\";\n"
    "re2c:YYINPUT = (.api.record ? yyrecord \"->yyinput\" : \"YYINPUT\");\n"
    "re2c:YYLESSTHAN = \"YYLESSTHAN\";\n"
    "re2c:YYLIMIT = (.api.record ? yyrecord \"->yylimit\" : \"YYLIMIT\");\n"
    "re2c:YYMARKER = (.api.record ? yyrecord \"->yymarker\" : \"YYMARKER\");\n"
    "re2c:YYMAXFILL = \"YYMAXFILL\";\n"
    "re2c:YYMAXNMATCH = \"YYMAXNMATCH\";\n"
    "re2c:YYMTAGN = \"YYMTAGN\";\n"
    "re2c:YYMTAGP = \"YYMTAGP\";\n"
    "re2c:YYPEEK = \"YYPEEK\";\n"
    "re2c:YYRESTORE = \"YYRESTORE\";\n"
    "re2c:YYRESTORECTX = \"YYRESTORECTX\";\n"
    "re2c:YYRESTORETAG = \"YYRESTORETAG\";\n"
    "re2c:YYSETACCEPT = sigil \"{var} = \" sigil \"{val};\";\n"
    "re2c:YYSETCOND = \"YYSETCONDITION\"; // historic default\n"
    "re2c:YYSETSTATE = \"YYSETSTATE\";\n"
    "re2c:YYSHIFT = \"YYSHIFT\";\n"
    "re2c:YYSHIFTSTAG = \"YYSHIFTSTAG\";\n"
    "re2c:YYSHIFTMTAG = \"YYSHIFTMTAG\";\n"
    "re2c:YYSKIP = \"YYSKIP\";\n"
    "re2c:YYSTAGN = \"YYSTAGN\";\n"
    "re2c:YYSTAGP = \"YYSTAGP\";\n"
    "re2c:tags:expression = (.api.record ? yyrecord \"->\") sigil;\n"
    "re2c:tags:negative = (.api.generic ? \"@@\" : \"NULL\");\n"
    "re2c:cond:divider = \"/* *********************************** */\";\n"
    "re2c:cond:goto = \"goto \" sigil \";\";\n"
    "\n"
    "\n"
    "// code templates --------------------------------------------------------------\n"
    "\n"
    "code:var_local = topindent type \" \" name (.init ? \" = \" init) \";\" nl;\n"
    "code:var_global = code:var_local;\n"
    "\n"
    "code:const_local = topindent type \" \" name \" = \" init \";\" nl;\n"
    "code:const_global = topindent \"#define \" name \" \" init nl;\n"
    "\n"
    "code:array_local =\n"
    "    topindent (.const ? \"static const \") type \" \" name \"[\" size \"] = {\" nl indent\n"
    "        [row{0:-2}: topindent [elem{0:-2}: elem \", \"] [elem{-1}: elem \",\"] nl]\n"
    "        [row{-1}:   topindent [elem{0:-2}: elem \", \"] [elem{-1}: elem]     nl]\n"
    "    dedent topindent \"};\" nl;\n"
    "\n"
    "code:array_global = code:array_local;\n"
    "\n"
    "code:array_elem = array \"[\" index \"]\";\n"
    "\n"
    "code:enum =\n"
    "    \"enum \" type \" {\" nl indent\n"
    "        [elem{0:-2}: topindent elem (!.code_model.goto_label ? \" = \" init) \",\" nl]\n"
    "        [elem{-1}:   topindent elem (!.code_model.goto_label ? \" = \" init) nl]\n"
    "    dedent \"};\" nl;\n"
    "\n"
    "code:enum_elem = name;\n"
    "\n"
    "code:assign = topindent lhs \" = \" rhs \";\" nl;\n"
    "\n"
    "code:type_int = \"int\";\n"
    "code:type_uint = \"unsigned int\";\n"
    "code:type_yybm = \"unsigned char\";\n"
    "code:type_yytarget = (.cgoto.relative ? \"int\" : \"void*\");\n"
    "code:type_yyctable = (.cgoto.relative ? \"int\" : \"void*\");\n"
    "\n"
    "code:cmp_eq = \"==\";\n"
    "code:cmp_ne = \"!=\";\n"
    "code:cmp_lt = \"<\";\n"
    "code:cmp_gt = \">\";\n"
    "code:cmp_le = \"<=\";\n"
    "code:cmp_ge = \">=\";\n"
    "\n"
    "code:if_then_else =\n"
    "    [branch{0}: topindent \"if (\" cond \") {\" nl\n"
    "        indent [stmt: stmt] dedent]\n"
    "    [branch{1:-1}: topindent \"} else \" (.cond ? \"if (\" cond \") \") \"{\" nl\n"
    "        indent [stmt: stmt] dedent]\n"
    "    topindent \"}\" nl;\n"
    "\n"
    "code:if_then_else_oneline =\n"
    "    [branch{0}:    topindent \"if (\" cond \") \" [stmt: stmt] nl]\n"
    "    [branch{1:-1}: topindent \"else \" (.cond ? \"if (\" cond \") \") [stmt: stmt] nl];\n"
    "\n"
    "code:switch =\n"
    "    topindent \"switch (\" expr \") {\" nl\n"
    "        indent [case: case] dedent\n"
    "    topindent \"}\" nl;\n"
    "\n"
    "code:switch_cases =\n"
    "    [case: case nl]\n"
    "        indent [stmt: stmt] dedent;\n"
    "\n"
    "code:switch_cases_oneline =\n"
    "    [case{0:-2}: case nl]\n"
    "    [case{-1}:   case \" \" [stmt: stmt] nl];\n"
    "\n"
    "code:switch_case_range = (.case_ranges\n"
    "    ? topindent \"case \" [val{0}: val] (.many ? \" ... \" [val{-1}: val]) \":\"\n"
    "    : [val{0:-2}: topindent \"case \" val \":\" nl]\n"
    "      [val{-1}:   topindent \"case \" val \":\"]);\n"
    "\n"
    "code:switch_case_default =\n"
    "    topindent \"default:\";\n"
    "\n"
    "code:loop =\n"
    "    topindent \"for (;;) {\" nl\n"
    "        indent [stmt: stmt] dedent\n"
    "    topindent \"}\" nl;\n"
    "\n"
    "code:continue = topindent \"continue;\" nl;\n"
    "\n"
    "code:goto = topindent \"goto \" label \";\" nl;\n"
    "\n"
    "code:cgoto =\n"
    "    topindent \"goto \" (.cgoto.relative\n"
    "        ? \"*((char*)&&\" base \" + \" array \"[\" index \"])\"\n"
    "        : \"*\" array \"[\" index \"]\"\n"
    "    ) \";\" nl;\n"
    "\n"
    "code:cgoto_data = (.cgoto.relative\n"
    "    ? \"(\" type \")((char*)&&\" label \" - (char*)&&\" base \")\"\n"
    "    : \"&&\" label);\n"
    "\n"
    "code:fndecl =\n"
    "    topindent type \" \" name \"(\"\n"
    "        [arg{0:-2}: argtype \" \" argname \", \"]\n"
    "        [arg{-1}:   argtype \" \" argname]\n"
    "    \");\" nl;\n"
    "\n"
    "code:fndef =\n"
    "    topindent type \" \" name \"(\"\n"
    "        [arg{0:-2}: argtype \" \" argname \", \"]\n"
    "        [arg{-1}:   argtype \" \" argname]\n"
    "    \") {\" nl\n"
    "        indent [stmt: stmt] dedent\n"
    "    \"}\" nl;\n"
    "\n"
    "code:fncall =\n"
    "    topindent (.retval ? retval \" = \") name \"(\" [arg{0:-2}: arg \", \"] [arg{-1}: arg] \");\" nl;\n"
    "\n"
    "code:tailcall =\n"
    "    topindent (.retval ? \"return \") name \"(\" [arg{0:-2}: arg \", \"] [arg{-1}: arg] \");\" nl;\n"
    "\n"
    "code:recursive_functions =\n"
    "    [fn: fndecl] nl\n"
    "    [fn: fndef nl];\n"
    "\n"
    "code:fingerprint =\n"
    "    \"/* Generated by re2c\" (.version ? \" \" version) (.date ? \" on \" date) \" */\" nl;\n"
    "\n"
    "code:line_info = \"#line \" line \" \\\"\" file \"\\\"\" nl;\n"
    "\n"
    "code:abort = topindent \"abort();\" nl;\n"
    "\n"
    "code:yydebug =\n"
    "    topindent (.api.generic\n"
    "        ? YYDEBUG (.api_style.functions ? \"();\")\n"
    "    : (.api.record\n"
    "        ? YYDEBUG \"(\" yyrecord \");\"\n"
    "        : YYDEBUG \"(\" state \", \" yych \");\"\n"
    "    )) nl;\n"
    "\n"
    "code:yypeek =\n"
    "    topindent (.code_model.recursive_functions ? YYCTYPE \" \") yych \" = \" (.api.generic\n"
    "        ? YYPEEK (.api_style.functions ? \"()\")\n"
    "        : (.cast ? \"(\" YYCTYPE \")\") \"*\" YYCURSOR\n"
    "    ) \";\" nl;\n"
    "\n"
    "code:yyskip =\n"
    "    topindent (.api.generic\n"
    "        ? YYSKIP (.api_style.functions ? \"();\")\n"
    "        : \"++\" YYCURSOR \";\"\n"
    "    ) nl;\n"
    "\n"
    "code:yybackup =\n"
    "    topindent (.api.generic\n"
    "        ? YYBACKUP (.api_style.functions ? \"();\")\n"
    "        : YYMARKER \" = \" YYCURSOR \";\"\n"
    "    ) nl;\n"
    "\n"
    "code:yybackupctx =\n"
    "    topindent (.api.generic\n"
    "        ? YYBACKUPCTX (.api_style.functions ? \"();\")\n"
    "        : YYCTXMARKER \" = \" YYCURSOR \";\"\n"
    "    ) nl;\n"
    "\n"
    "code:yyskip_yypeek =\n"
    "    topindent (.code_model.recursive_functions ? YYCTYPE \" \") yych \" = \"\n"
    "        (.cast ? \"(\" YYCTYPE \")\") \"*++\" YYCURSOR \";\" nl;\n"
    "\n"
    "code:yypeek_yyskip =\n"
    "    topindent (.code_model.recursive_functions ? YYCTYPE \" \") yych \" = \"\n"
    "        (.cast ? \"(\" YYCTYPE \")\") \"*\" YYCURSOR \"++;\" nl;\n"
    "\n"
    "code:yyskip_yybackup =\n"
    "    topindent YYMARKER \" = ++\" YYCURSOR \";\" nl;\n"
    "\n"
    "code:yybackup_yyskip =\n"
    "    topindent YYMARKER \" = \" YYCURSOR \"++;\" nl;\n"
    "\n"
    "code:yybackup_yypeek =\n"
    "    topindent (.code_model.recursive_functions ? YYCTYPE \" \") yych \" = \"\n"
    "        (.cast ? \"(\" YYCTYPE \")\") \"*(\" YYMARKER \" = \" YYCURSOR \");\" nl;\n"
    "\n"
    "code:yyskip_yybackup_yypeek =\n"
    "    topindent (.code_model.recursive_functions ? YYCTYPE \" \") yych \" = \"\n"
    "        (.cast ? \"(\" YYCTYPE \")\") \"*(\" YYMARKER \" = ++\" YYCURSOR \");\" nl;\n"
    "\n"
    "code:yybackup_yypeek_yyskip =\n"
    "    topindent (.code_model.recursive_functions ? YYCTYPE \" \") yych \" = \"\n"
    "        (.cast ? \"(\" YYCTYPE \")\") \"*(\" YYMARKER \" = \" YYCURSOR \"++);\" nl;\n"
    "\n"
    "code:yyrestore =\n"
    "    topindent (.api.generic\n"
    "        ? YYRESTORE (.api_style.functions ? \"();\")\n"
    "        : YYCURSOR \" = \" YYMARKER \";\"\n"
    "    ) nl;\n"
    "\n"
    "code:yyrestorectx =\n"
    "    topindent (.api.generic\n"
    "        ? YYRESTORECTX (.api_style.functions ? \"();\")\n"
    "        : YYCURSOR \" = \" YYCTXMARKER \";\"\n"
    "    ) nl;\n"
    "\n"
    "code:yyrestoretag =\n"
    "    topindent (.api.generic\n"
    "        ? YYRESTORETAG (.api_style.functions ? \"(\" tag \");\")\n"
    "        : YYCURSOR \" = \" tag \";\"\n"
    "    ) nl;\n"
    "\n"
    "code:yyshift =\n"
    "    topindent (.api.generic\n"
    "        ? YYSHIFT (.api_style.functions ? \"(-\" offset \");\")\n"
    "        : YYCURSOR \" -= \" offset \";\"\n"
    "    ) nl;\n"
    "\n"
    "code:yyshiftstag =\n"
    "    topindent (.nested ? \"if (\" tag \" != \" neg \") \") (.api.generic\n"
    "        ? YYSHIFTSTAG (.api_style.functions ? \"(\" tag \", -\" offset \");\")\n"
    "        : tag \" -= \" offset \";\"\n"
    "    ) nl;\n"
    "\n"
    "code:yyshiftmtag =\n"
    "    topindent YYSHIFTMTAG (.api_style.functions ? \"(\" tag \", -\" offset \");\") nl;\n"
    "\n"
    "code:yystagp =\n"
    "    topindent (.api.generic\n"
    "        ? YYSTAGP (.api_style.functions ? \"(\" tag \");\")\n"
    "        : tag \" = \" YYCURSOR \";\"\n"
    "    ) nl;\n"
    "\n"
    "code:yymtagp =\n"
    "    topindent YYMTAGP (.api_style.functions ? \"(\" tag \");\") nl;\n"
    "\n"
    "code:yystagn =\n"
    "    topindent (.api.generic\n"
    "        ? YYSTAGN (.api_style.functions ? \"(\" tag \");\")\n"
    "        : tag \" = \" neg \";\"\n"
    "    ) nl;\n"
    "\n"
    "code:yymtagn =\n"
    "    topindent YYMTAGN (.api_style.functions ? \"(\" tag \");\") nl;\n"
    "\n"
    "code:yycopystag =\n"
    "    topindent (.api.generic\n"
    "        ? YYCOPYSTAG // function style is not supported, as there's no sensible default\n"
    "        : lhs \" = \" rhs \";\"\n"
    "    ) nl;\n"
    "\n"
    "code:yycopymtag =\n"
    "    topindent (.api.generic\n"
    "        ? YYCOPYMTAG // function style is not supported, as there's no sensible default\n"
    "        : lhs \" = \" rhs \";\"\n"
    "    ) nl;\n"
    "\n"
    "code:yygetaccept =\n"
    "    (.api.generic\n"
    "        ? YYGETACCEPT // function style is not supported, as there's no sensible default\n"
    "        : (.api.record & (.storable_state | .code_model.recursive_functions) ? yyrecord \"->\") var);\n"
    "\n"
    "code:yysetaccept =\n"
    "    topindent (.api.generic\n"
    "        ? YYSETACCEPT // function style is not supported, as there's no sensible default\n"
    "        : (.api.record & (.storable_state | .code_model.recursive_functions) ? yyrecord \"->\")\n"
    "            var \" = \" val \";\"\n"
    "    ) nl;\n"
    "\n"
    "// Historically simple API did not provide default definition for YYGETCOND.\n"
    "// Changing it would break backwards compatibility, as there may be a macro definition\n"
    "// not based on `yycond` that re2c is unable to see, e.g. included from a header file.\n"
    "code:yygetcond =\n"
    "    (.api.generic | .api.simple\n"
    "        ? YYGETCOND (.api_style.functions ? \"()\")\n"
    "        : yyrecord \"->\" var);\n"
    "\n"
    "// Historically simple API did not provide default definition for YYSETCOND.\n"
    "// Changing it would break backwards compatibility, as there may be a macro definition\n"
    "// not based on `yycond` that re2c is unable to see, e.g. included from a header file.\n"
    "code:yysetcond =\n"
    "    topindent (.api.generic | .api.simple\n"
    "        ? YYSETCOND (.api_style.functions ? \"(\" val \");\")\n"
    "        : yyrecord \"->\" var \" = \" val \";\"\n"
    "    ) nl;\n"
    "\n"
    "// Historically simple API did not provide default definition for YYGETSTATE.\n"
    "// Changing it would break backwards compatibility, as there may be a macro definition\n"
    "// not based on `yystate` that re2c is unable to see, e.g. included from a header file.\n"
    "code:yygetstate =\n"
    "    (.api.generic | .api.simple\n"
    "        ? YYGETSTATE (.api_style.functions ? \"()\")\n"
    "        : yyrecord \"->\" var);\n"
    "\n"
    "// Historically simple API did not provide default definition for YYSETSTATE.\n"
    "// Changing it would break backwards compatibility, as there may be a macro definition\n"
    "// not based on `yystate` that re2c is unable to see, e.g. included from a header file.\n"
    "code:yysetstate =\n"
    "    topindent (.api.generic | .api.simple\n"
    "        ? YYSETSTATE (.api_style.functions ? \"(\" val \");\")\n"
    "        : yyrecord \"->\" var \" = \" val \";\"\n"
    "    ) nl;\n"
    "\n"
    "code:yylessthan =\n"
    "    (.api.generic\n"
    "        ? YYLESSTHAN (.api_style.functions ? \"(\" need \")\")\n"
    "        : (.many\n"
    "            ? \"(\" YYLIMIT \" - \" YYCURSOR \") < \" need\n"
    "            : YYLIMIT \" <= \" YYCURSOR));\n"
    "\n"
    "code:yyend =\n"
    "    (.api.generic | .yyfill.enable\n"
    "        ? YYEND (.api_style.functions ? \"()\")\n"
    "        : YYLIMIT \" <= \" YYCURSOR);\n"
    "\n"
    "code:yybm_filter = yych \" & ~0xFF\";\n"
    "\n"
    "code:yybm_match = yybm \"[\" offset \"+\" yych \"] & \" mask;\n"
    "\n"
    "code:yytarget_filter = yych \" & ~0xFF\";\n"
    "\n"
    "// The range bounds and the zero vector are loop invariants: they are broadcast once before the\n"
    "// loop, in a block that scopes them to this state. Ranges are disjoint, so their bounds are\n"
    "// distinct and name the vectors uniquely.\n"
    "code:vector_loop =\n"
    "    topindent \"#if (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 201112L) || (defined(__cplusplus) && __cplusplus >= 201103L)\" nl\n"
    "    topindent \"static_assert(sizeof(*(\" YYCURSOR \")) == 1, \\\"re2c: 8-bit character unit required for vector loop\\\");\" nl\n"
    "    topindent \"#elif defined(__GNUC__) || defined(__clang__)\" nl\n"
    "    topindent \"_Static_assert(sizeof(*(\" YYCURSOR \")) == 1, \\\"re2c: 8-bit character unit required for vector loop\\\");\" nl\n"
    "    topindent \"#endif\" nl\n"
    "    topindent \"{\" nl\n"
    "    indent\n"
    "    topindent \"#if defined(__AVX2__)\" nl\n"
    "    [range{0:-1}: topindent \"const __m256i yysimdlo\" range_lo \" = _mm256_set1_epi8(\" range_lo \");\" nl\n"
    "        topindent \"const __m256i yysimdhi\" range_hi \" = _mm256_set1_epi8(\" range_hi \");\" nl]\n"
    "    topindent \"const __m256i yysimdzero = _mm256_setzero_si256();\" nl\n"
    "    topindent \"#endif\" nl\n"
    "    topindent \"while (!(\" lessthan \")) {\" nl\n"
    "        indent\n"
    "        topindent \"#if defined(__AVX2__)\" nl\n"
    "        topindent \"__m256i yysimd0 = _mm256_loadu_si256((const __m256i*)(\" YYCURSOR \"));\" nl\n"
    "        [range{0}: topindent \"__m256i yysimd1 = _mm256_cmpeq_epi8(_mm256_or_si256(_mm256_subs_epu8(yysimd0, yysimdhi\" range_hi \"), _mm256_subs_epu8(yysimdlo\" range_lo \", yysimd0)), yysimdzero);\" nl]\n"
    "        [range{1:-1}: topindent \"yysimd1 = _mm256_or_si256(yysimd1, _mm256_cmpeq_epi8(_mm256_or_si256(_mm256_subs_epu8(yysimd0, yysimdhi\" range_hi \"), _mm256_subs_epu8(yysimdlo\" range_lo \", yysimd0)), yysimdzero));\" nl]\n"
    "        topindent \"if ((unsigned int)_mm256_movemask_epi8(yysimd1) != \" mask \") {\" nl\n"
    "            indent topindent \"break;\" nl dedent\n"
    "        topindent \"}\" nl\n"
    "        topindent \"#else\" nl\n"
    "        topindent \"{\" nl\n"
    "        indent\n"
    "        topindent \"unsigned int yysimd_ok = 1;\" nl\n"
    "        topindent \"for (size_t yyi = 0; yyi < \" size \"; ++yyi) {\" nl\n"
    "            indent\n"
    "            topindent \"unsigned char yyc = (unsigned char)(\" YYCURSOR \")[yyi];\" nl\n"
    "            topindent \"if (!(\"\n"
    "            [range{0}: \"(yyc >= \" range_lo \" && yyc <= \" range_hi \")\"]\n"
    "            [range{1:-1}: \" || (yyc >= \" range_lo \" && yyc <= \" range_hi \")\"]\n"
    "            \")) { yysimd_ok = 0; break; }\" nl\n"
    "            dedent\n"
    "        topindent \"}\" nl\n"
    "        topindent \"if (!yysimd_ok) break;\" nl\n"
    "        dedent\n"
    "        topindent \"}\" nl\n"
    "        topindent \"#endif\" nl\n"
    "        topindent YYCURSOR \" += \" size \";\" nl\n"
    "        dedent\n"
    "    topindent \"}\" nl\n"
    "    topindent \"#if defined(__AVX2__)\" nl\n"
    "    topindent \"_mm256_zeroupper();\" nl\n"
    "    topindent \"#endif\" nl\n"
    "    dedent\n"
    "    topindent \"}\" nl;\n"
    "\n"
    "// multi-character primitives (linear vectorization) ---------------------------\n"
    "\n"
    "// The value of `n` code units at the cursor, the code unit at offset `k` in bits [8*k, 8*k+8).\n"
    "// For the simple and record APIs the value is assembled from single bytes, which does not depend on\n"
    "// the host byte order and does not assume alignment; compilers turn it into one load.\n"
    "code:yypeekn = (.api.generic\n"
    "    ? \"YYPEEKN(\" YYCURSOR \", \" n \")\"\n"
    "    : \"(\"\n"
    "        [offset{0}:    \"(unsigned long long)(unsigned char)\" YYCURSOR \"[\" offset \"]\"]\n"
    "        [offset{1:-1}: \" | (unsigned long long)(unsigned char)\" YYCURSOR \"[\" offset \"] << 8 * \" offset]\n"
    "    \")\");\n"
    "\n"
    "// Without YYFILL nothing guarantees that `n` code units can be read at the cursor.\n"
    "code:yypeekn_guard = (.api.generic | .yyfill.enable ? \"\" : \"(\" YYLIMIT \" - \" YYCURSOR \") >= \" n);\n"
    "\n"
    "// The number of low-order zero code units of `expr`, the nonzero XOR of the value read by\n"
    "// `code:yypeekn` and the literal (that is, the number of leading code units that still agree with\n"
    "// the literal). `(expr - 1) & ~expr` keeps the bits below the lowest set bit of `expr`; bit 7 of a\n"
    "// byte is set in it only if the whole byte is below that bit, and the multiplication adds these\n"
    "// bits up in the top byte. The code is branchless and portable; with GCC or Clang it may be\n"
    "// replaced by `__builtin_ctzll(expr) >> 3`.\n"
    "code:yypeekn_diverge = \"((((((\" expr \" - 1) & ~\" expr \") >> 7) & 0x0101010101010101ULL) * 0x0101010101010101ULL) >> 56)\";\n"
    "\n"
    "code:yyskipn =\n"
    "    topindent (.api.generic\n"
    "        ? \"YYSKIPN(\" YYCURSOR \", \" n \");\"\n"
    "        : YYCURSOR \" += \" n \";\"\n"
    "    ) nl;\n"
    "\n"
    "// keyword tables (see `re2c:keywords`) ----------------------------------------\n"
    "\n"
    "code:keyword_table =\n"
    "    topindent \"static const \" (.wide ? \"unsigned short\" : \"unsigned char\") \" \" name \"_slot[\"\n"
    "        size \"] = {\" nl indent\n"
    "        [row: topindent [elem{0:-2}: elem \", \"] [elem{-1}: elem \",\"] nl]\n"
    "    dedent topindent \"};\" nl\n"
    "    topindent \"static const struct { unsigned long long w0, w1; int n, id; } \" name \"_entry[] = {\" nl\n"
    "    indent\n"
    "        [entry: topindent \"{\" word0 \"ull, \" word1 \"ull, \" length \", \" val \"},\" nl]\n"
    "    dedent topindent \"};\" nl\n"
    "    topindent \"/* \" name \" returns 1 + the index of the keyword in [s, e), or 0 if it is not a keyword. */\" nl\n"
    "    topindent \"static int \" name \"(const void* s, const void* e) {\" nl indent\n"
    "        topindent \"const unsigned char* t = (const unsigned char*)s;\" nl\n"
    "        topindent \"const long n = (long)((const unsigned char*)e - t);\" nl\n"
    "        topindent \"unsigned long long w0, w1 = 0;\" nl\n"
    "        topindent \"if (n <= 0 || n > 16) return 0;\" nl\n"
    "        topindent \"if (n > 8) {\" nl indent\n"
    "            topindent \"const unsigned char* b = t + n - 8;\" nl\n"
    "            topindent \"w0 = (unsigned long long)t[0] | (unsigned long long)t[1] << 8\" nl\n"
    "            topindent \"    | (unsigned long long)t[2] << 16 | (unsigned long long)t[3] << 24\" nl\n"
    "            topindent \"    | (unsigned long long)t[4] << 32 | (unsigned long long)t[5] << 40\" nl\n"
    "            topindent \"    | (unsigned long long)t[6] << 48 | (unsigned long long)t[7] << 56;\" nl\n"
    "            topindent \"w1 = ((unsigned long long)b[0] | (unsigned long long)b[1] << 8\" nl\n"
    "            topindent \"    | (unsigned long long)b[2] << 16 | (unsigned long long)b[3] << 24\" nl\n"
    "            topindent \"    | (unsigned long long)b[4] << 32 | (unsigned long long)b[5] << 40\" nl\n"
    "            topindent \"    | (unsigned long long)b[6] << 48 | (unsigned long long)b[7] << 56) >> (8 * (16 - n));\" nl\n"
    "        dedent topindent \"} else if (n >= 4) {\" nl indent\n"
    "            topindent \"const unsigned char* b = t + n - 4;\" nl\n"
    "            topindent \"w0 = ((unsigned long long)t[0] | (unsigned long long)t[1] << 8\" nl\n"
    "            topindent \"    | (unsigned long long)t[2] << 16 | (unsigned long long)t[3] << 24)\" nl\n"
    "            topindent \"    | ((unsigned long long)b[0] | (unsigned long long)b[1] << 8\" nl\n"
    "            topindent \"    | (unsigned long long)b[2] << 16 | (unsigned long long)b[3] << 24) << (8 * (n - 4));\" nl\n"
    "        dedent topindent \"} else {\" nl indent\n"
    "            topindent \"w0 = (unsigned long long)t[0] | (unsigned long long)t[n >> 1] << (8 * (n >> 1))\" nl\n"
    "            topindent \"    | (unsigned long long)t[n - 1] << (8 * (n - 1));\" nl\n"
    "        dedent topindent \"}\" nl\n"
    "        topindent \"{\" nl indent\n"
    "            topindent \"const unsigned idx = \" name \"_slot[(w0 * \" mul0 \"ull + w1 * \" mul1 \"ull) >> \" shift \"];\" nl\n"
    "            topindent \"if (\" name \"_entry[idx].n == n && \" name \"_entry[idx].w0 == w0 && \"\n"
    "                name \"_entry[idx].w1 == w1) return \" name \"_entry[idx].id;\" nl\n"
    "        dedent topindent \"}\" nl\n"
    "        topindent \"return 0;\" nl\n"
    "    dedent topindent \"}\" nl;\n"
    "\n"
    "// Flat composite table `c2_kw_table_t` (5464 bytes, the layout of c2simd `c2_kw_resolve.h`) with\n"
    "// `re2c:keywords:model = archtime`. The type is declared once per file, unless `c2_kw_resolve.h`\n"
    "// has been included before.\n"
    "code:keyword_table_archtime =\n"
    "    \"#ifndef RE2C_C2_KW_TABLE_T\" nl\n"
    "    \"#define RE2C_C2_KW_TABLE_T\" nl\n"
    "    \"#ifndef C2_KW_RESOLVE_H\" nl\n"
    "    \"#include <stdint.h>\" nl\n"
    "    topindent \"typedef struct {\" nl indent\n"
    "        topindent \"uint64_t m1;\" nl\n"
    "        topindent \"uint64_t m2;\" nl\n"
    "        topindent \"uint16_t eh0[256];\" nl\n"
    "        topindent \"uint8_t disp[64];\" nl\n"
    "        topindent \"uint8_t key[4096];\" nl\n"
    "        topindent \"uint8_t len[256];\" nl\n"
    "        topindent \"uint16_t tok[256];\" nl\n"
    "        topindent \"uint8_t fold;\" nl\n"
    "    dedent topindent \"} c2_kw_table_t;\" nl\n"
    "    \"#endif\" nl\n"
    "    topindent \"typedef char re2c_c2_kw_table_size[sizeof(c2_kw_table_t) == 5464 ? 1 : -1];\" nl\n"
    "    \"#if defined(__GNUC__) || defined(__clang__)\" nl\n"
    "    \"#define RE2C_C2_KW_ALIGN __attribute__((aligned(64)))\" nl\n"
    "    \"#else\" nl\n"
    "    \"#define RE2C_C2_KW_ALIGN\" nl\n"
    "    \"#endif\" nl\n"
    "    \"#endif\" nl\n"
    "    topindent \"static const c2_kw_table_t \" name \"_table RE2C_C2_KW_ALIGN = {\" nl indent\n"
    "        topindent mul0 \"ull, /* m1 */\" nl\n"
    "        topindent mul1 \"ull, /* m2 */\" nl\n"
    "        topindent \"{ /* eh0 */\" nl indent\n"
    "            [eh0: topindent [elem: elem \",\"] nl]\n"
    "        dedent topindent \"},\" nl\n"
    "        topindent \"{ /* disp */\" nl indent\n"
    "            [disp: topindent [elem: elem \",\"] nl]\n"
    "        dedent topindent \"},\" nl\n"
    "        topindent \"{ /* key */\" nl indent\n"
    "            [key: topindent [elem: elem \",\"] nl]\n"
    "        dedent topindent \"},\" nl\n"
    "        topindent \"{ /* len */\" nl indent\n"
    "            [keylen: topindent [elem: elem \",\"] nl]\n"
    "        dedent topindent \"},\" nl\n"
    "        topindent \"{ /* tok */\" nl indent\n"
    "            [tok: topindent [elem: elem \",\"] nl]\n"
    "        dedent topindent \"},\" nl\n"
    "        topindent fold \" /* fold */\" nl\n"
    "    dedent topindent \"};\" nl\n"
    "    topindent \"/* \" name \" returns 1 + the index of the keyword in [s, e), or 0 if it is not a keyword. */\" nl\n"
    "    topindent \"static int \" name \"(const void* s, const void* e) {\" nl indent\n"
    "        topindent \"const unsigned char* t = (const unsigned char*)s;\" nl\n"
    "        topindent \"const long n = (long)((const unsigned char*)e - t);\" nl\n"
    "        topindent \"const c2_kw_table_t* kt = &\" name \"_table;\" nl\n"
    "        topindent \"const unsigned char* k;\" nl\n"
    "        topindent \"uint64_t w0, w1 = 0, k0 = 0, k1 = 0, lo, up, fm, w;\" nl\n"
    "        topindent \"uint32_t slot, eq, i;\" nl\n"
    "        topindent \"if (n <= 0 || n > 16) return 0;\" nl\n"
    "        topindent \"/* level 0: lengths of the keys starting with this byte */\" nl\n"
    "        topindent \"if (n < 16 && !((kt->eh0[t[0]] >> n) & 1u)) return 0;\" nl\n"
    "        topindent \"if (n > 8) {\" nl indent\n"
    "            topindent \"const unsigned char* b = t + n - 8;\" nl\n"
    "            topindent \"w0 = (uint64_t)t[0] | (uint64_t)t[1] << 8 | (uint64_t)t[2] << 16 | (uint64_t)t[3] << 24\" nl\n"
    "            topindent \"    | (uint64_t)t[4] << 32 | (uint64_t)t[5] << 40 | (uint64_t)t[6] << 48 | (uint64_t)t[7] << 56;\" nl\n"
    "            topindent \"w1 = ((uint64_t)b[0] | (uint64_t)b[1] << 8 | (uint64_t)b[2] << 16 | (uint64_t)b[3] << 24\" nl\n"
    "            topindent \"    | (uint64_t)b[4] << 32 | (uint64_t)b[5] << 40 | (uint64_t)b[6] << 48\" nl\n"
    "            topindent \"    | (uint64_t)b[7] << 56) >> (8 * (16 - n));\" nl\n"
    "        dedent topindent \"} else if (n >= 4) {\" nl indent\n"
    "            topindent \"const unsigned char* b = t + n - 4;\" nl\n"
    "            topindent \"w0 = ((uint64_t)t[0] | (uint64_t)t[1] << 8 | (uint64_t)t[2] << 16 | (uint64_t)t[3] << 24)\" nl\n"
    "            topindent \"    | ((uint64_t)b[0] | (uint64_t)b[1] << 8 | (uint64_t)b[2] << 16\" nl\n"
    "            topindent \"    | (uint64_t)b[3] << 24) << (8 * (n - 4));\" nl\n"
    "        dedent topindent \"} else {\" nl indent\n"
    "            topindent \"w0 = (uint64_t)t[0] | (uint64_t)t[n >> 1] << (8 * (n >> 1)) | (uint64_t)t[n - 1] << (8 * (n - 1));\" nl\n"
    "        dedent topindent \"}\" nl\n"
    "        topindent \"/* branchless ASCII case folding of 'A'..'Z' (no-op if fold is 0) */\" nl\n"
    "        topindent \"fm = 0x0101010101010101ull * kt->fold;\" nl\n"
    "        topindent \"lo = w0 & 0x7F7F7F7F7F7F7F7Full;\" nl\n"
    "        topindent \"up = (lo + 0x3F3F3F3F3F3F3F3Full) & ~(lo + 0x2525252525252525ull) & ~w0 & 0x8080808080808080ull;\" nl\n"
    "        topindent \"w0 |= (up >> 2) & fm;\" nl\n"
    "        topindent \"lo = w1 & 0x7F7F7F7F7F7F7F7Full;\" nl\n"
    "        topindent \"up = (lo + 0x3F3F3F3F3F3F3F3Full) & ~(lo + 0x2525252525252525ull) & ~w1 & 0x8080808080808080ull;\" nl\n"
    "        topindent \"w1 |= (up >> 2) & fm;\" nl\n"
    "        topindent \"/* two-level perfect hash and branchless key comparison */\" nl\n"
    "        topindent \"w = w0 ^ ((uint64_t)n << 56);\" nl\n"
    "        topindent \"slot = (uint32_t)(((w * kt->m2) >> 56) ^ kt->disp[(w * kt->m1) >> 58]) & 0xFFu;\" nl\n"
    "        topindent \"k = kt->key + 16 * slot;\" nl\n"
    "        topindent \"for (i = 0; i < 8; ++i) {\" nl indent\n"
    "            topindent \"k0 |= (uint64_t)k[i] << (8 * i);\" nl\n"
    "            topindent \"k1 |= (uint64_t)k[i + 8] << (8 * i);\" nl\n"
    "        dedent topindent \"}\" nl\n"
    "        topindent \"eq = (uint32_t)(((w0 ^ k0) | (w1 ^ k1)) == 0) & (uint32_t)(kt->len[slot] == n);\" nl\n"
    "        topindent \"return (int)(kt->tok[slot] & (0u - eq));\" nl\n"
    "    dedent topindent \"}\" nl;\n"
    "\n"
    "code:keyword_lookup = name \"(\" token \", \" YYCURSOR \")\";\n"
    ;
