// Code generated by re2go, DO NOT EDIT.
//go:generate re2go $INPUT -o $OUTPUT -i --api simple --simd
//go:build goexperiment.simd && (amd64 || arm64)

package main

import (
	"fmt"
)

// LexString scanne une tranche d'octets délimitée par des guillemets avec Fast-Forward SIMD.
// Accepte []byte (standard zéro-allocation Go) et retourne la longueur du contenu extrait ou -1.
func LexString(yyinput []byte) int {
	var yycursor int
	yylimit := len(yyinput)

	if yycursor >= yylimit || yyinput[yycursor] != '"' {
		return -1
	}
	yycursor++
	start := yycursor

	for {
		
{
	var yych byte
	yych = yyinput[yycursor]
	switch (yych) {
	case 0x00:
		fallthrough
	case '\n':
		fallthrough
	case '\r':
		goto yy1
	case '"':
		goto yy5
	case '\\':
		goto yy6
	default:
		goto yy3
	}
yy1:
	yycursor += 1
yy2:
	{ return -1 }
yy3:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 0x00:
		fallthrough
	case '\n':
		fallthrough
	case '\r':
		fallthrough
	case '"':
		fallthrough
	case '\\':
		goto yy4
	default:
		goto yy3
	}
yy4:
	{ continue }
yy5:
	yycursor += 1
	{ return yycursor - start - 1 }
yy6:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case '"':
		fallthrough
	case '/':
		fallthrough
	case '\\':
		fallthrough
	case 'b':
		fallthrough
	case 'f':
		fallthrough
	case 'n':
		fallthrough
	case 'r':
		fallthrough
	case 't':
		goto yy7
	default:
		goto yy2
	}
yy7:
	yycursor += 1
	{ continue }
}

	}
}

func main() {
	sample := []byte("\"Identifiant_Systeme_Tres_Long_Sans_Echappement_Pour_Prouver_Le_Debit_SIMD\"\x00")
	length := LexString(sample)
	fmt.Printf("Longueur extraite : %d\n", length)
}
