// Code generated by re2go, DO NOT EDIT.
//go:generate re2go $INPUT -o $OUTPUT -i --api simple
package main

import "fmt"

// Keyword tables for keyword rules subsumed by the identifier rule.
var yykw0_slot = [32]uint8{
	0, 0, 0, 3, 0, 0, 0, 12, 10, 0, 9, 0, 0, 0, 7, 4,
	0, 0, 8, 0, 11, 0, 2, 0, 1, 0, 0, 13, 5, 0, 6, 0,
}

var yykw0_entry = [...]struct {
	w0, w1 uint64
	n, id  int32
}{
	{0x0000000000000000, 0x0000000000000000, 0, 0},
	{0x0000000000000078, 0x0000000000000000, 1, 1},
	{0x0000000000006261, 0x0000000000000000, 2, 2},
	{0x0000000000636261, 0x0000000000000000, 3, 3},
	{0x000000006d6f7266, 0x0000000000000000, 4, 4},
	{0x0000006572656877, 0x0000000000000000, 5, 5},
	{0x00007463656c6573, 0x0000000000000000, 6, 6},
	{0x006e656577746562, 0x0000000000000000, 7, 7},
	{0x74636e6974736964, 0x0000000000000000, 8, 8},
	{0x766973756c637865, 0x0000000000000065, 9, 9},
	{0x5f746e6572727563, 0x0000000065746164, 12, 10},
	{0x5f746e6572727563, 0x00000000656d6974, 12, 11},
	{0x636e695f6f747561, 0x0000746e656d6572, 14, 12},
	{0x746361736e617274, 0x000064695f6e6f69, 14, 13},
}

// yykw0 returns 1 + the index of the keyword equal to t, or 0 if t is not a keyword.
func yykw0(t []byte) int {
	n := len(t)
	var w0, w1 uint64
	switch {
	case n > 16 || n == 0:
		return 0
	case n > 8:
		a, b := t[:8], t[n-8:]
		_ = b[7]
		w0 = uint64(a[0]) | uint64(a[1])<<8 | uint64(a[2])<<16 | uint64(a[3])<<24 |
			uint64(a[4])<<32 | uint64(a[5])<<40 | uint64(a[6])<<48 | uint64(a[7])<<56
		w1 = (uint64(b[0]) | uint64(b[1])<<8 | uint64(b[2])<<16 | uint64(b[3])<<24 |
			uint64(b[4])<<32 | uint64(b[5])<<40 | uint64(b[6])<<48 | uint64(b[7])<<56) >> (128 - 8*n)
	case n >= 4:
		a, b := t[:4], t[n-4:]
		_ = b[3]
		w0 = uint64(uint32(a[0])|uint32(a[1])<<8|uint32(a[2])<<16|uint32(a[3])<<24) |
			uint64(uint32(b[0])|uint32(b[1])<<8|uint32(b[2])<<16|uint32(b[3])<<24)<<(8*n-32)
	default:
		w0 = uint64(t[0]) | uint64(t[n>>1])<<(8*(n>>1)) | uint64(t[n-1])<<(8*(n-1))
	}
	e := &yykw0_entry[yykw0_slot[(w0*0x391ceef02702c2fd+w1*0x4baf8cac4784cb13)>>59]]
	if int(e.n) == n && e.w0 == w0 && e.w1 == w1 {
		return int(e.id)
	}
	return 0
}


const (
	ID = iota
	NUM
	SPACE
	END
	ERR
	IN_PREFIX
	KW_X
	KW_AB
	KW_ABC
	KW_FROM
	KW_WHERE
	KW_SELECT
	KW_BETWEEN
	KW_DISTINCT
	KW_EXCLUSIVE
	KW_CURRENT_DATE
	KW_CURRENT_TIME
	KW_AUTO_INCREMENT
	KW_TRANSACTION_ID
	KW_INT
	KW_CURRENT_TIMESTAMP
)

func lex(yyinput []byte, yycursor int) (int, int) {
	var yymarker int
	_ = yymarker
	tok := yycursor
	
{
	var yych byte
	yych = yyinput[yycursor]
	switch (yych) {
	case 0x00:
		goto yy1
	case ' ':
		goto yy3
	case '0','1','2','3','4','5','6','7','8','9':
		goto yy5
	case '_':
		fallthrough
	case 'a','b':
		fallthrough
	case 'd','e','f','g','h':
		fallthrough
	case 'j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy7
	case 'c':
		goto yy10
	case 'i':
		goto yy11
	default:
		goto yy2
	}
yy1:
	yycursor += 1
	{ return END, yycursor }
yy2:
	yycursor += 1
	{ return ERR, yycursor }
yy3:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case ' ':
		goto yy3
	default:
		goto yy4
	}
yy4:
	{ return SPACE, yycursor }
yy5:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case '0','1','2','3','4','5','6','7','8','9':
		goto yy5
	default:
		goto yy6
	}
yy6:
	{ return NUM, yycursor }
yy7:
	yycursor += 1
	yych = yyinput[yycursor]
yy8:
	switch (yych) {
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy7
	default:
		goto yy9
	}
yy9:
	switch (yykw0(yyinput[tok:yycursor])) {
	case 1:
		{ return KW_X, yycursor }
	case 2:
		{ return KW_AB, yycursor }
	case 3:
		{ return KW_ABC, yycursor }
	case 4:
		{ return KW_FROM, yycursor }
	case 5:
		{ return KW_WHERE, yycursor }
	case 6:
		{ return KW_SELECT, yycursor }
	case 7:
		{ return KW_BETWEEN, yycursor }
	case 8:
		{ return KW_DISTINCT, yycursor }
	case 9:
		{ return KW_EXCLUSIVE, yycursor }
	case 10:
		{ return KW_CURRENT_DATE, yycursor }
	case 11:
		{ return KW_CURRENT_TIME, yycursor }
	case 12:
		{ return KW_AUTO_INCREMENT, yycursor }
	case 13:
		{ return KW_TRANSACTION_ID, yycursor }
	default:
		{ return ID, yycursor }
	}
yy10:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'u':
		goto yy12
	default:
		goto yy8
	}
yy11:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m':
		fallthrough
	case 'o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy13
	case 'n':
		goto yy16
	default:
		goto yy8
	}
yy12:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'r':
		goto yy17
	default:
		goto yy8
	}
yy13:
	yycursor += 1
	yych = yyinput[yycursor]
yy14:
	switch (yych) {
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case '_':
		goto yy7
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy13
	default:
		goto yy15
	}
yy15:
	{ return IN_PREFIX, yycursor }
yy16:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 't':
		goto yy18
	default:
		goto yy14
	}
yy17:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'r':
		goto yy20
	default:
		goto yy8
	}
yy18:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case '_':
		goto yy7
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy13
	default:
		goto yy19
	}
yy19:
	{ return KW_INT, yycursor }
yy20:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'e':
		goto yy21
	default:
		goto yy8
	}
yy21:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'n':
		goto yy22
	default:
		goto yy8
	}
yy22:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 't':
		goto yy23
	default:
		goto yy8
	}
yy23:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case '_':
		goto yy24
	default:
		goto yy8
	}
yy24:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 't':
		goto yy25
	default:
		goto yy8
	}
yy25:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'i':
		goto yy26
	default:
		goto yy8
	}
yy26:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'm':
		goto yy27
	default:
		goto yy8
	}
yy27:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'e':
		goto yy28
	default:
		goto yy8
	}
yy28:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 's':
		goto yy29
	default:
		goto yy8
	}
yy29:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 't':
		goto yy30
	default:
		goto yy8
	}
yy30:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'a':
		goto yy31
	default:
		goto yy8
	}
yy31:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'm':
		goto yy32
	default:
		goto yy8
	}
yy32:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'p':
		goto yy33
	default:
		goto yy8
	}
yy33:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy7
	default:
		goto yy34
	}
yy34:
	{ return KW_CURRENT_TIMESTAMP, yycursor }
}

}

func main() {
	tests := []struct {
		str  string
		kind int
	}{
		{"x", KW_X}, {"xx", ID}, {"a", ID}, {"ab", KW_AB}, {"abc", KW_ABC}, {"abcd", ID},
		{"fro", ID}, {"from", KW_FROM}, {"froma", ID}, {"where", KW_WHERE}, {"wherex", ID},
		{"select", KW_SELECT}, {"selec", ID}, {"selecta", ID}, {"between", KW_BETWEEN},
		{"distinct", KW_DISTINCT}, {"distinc", ID}, {"distincts", ID},
		{"exclusive", KW_EXCLUSIVE}, {"exclusiv", ID}, {"exclusives", ID},
		{"current_date", KW_CURRENT_DATE}, {"current_time", KW_CURRENT_TIME},
		{"current_dat", ID}, {"current_datex", ID}, {"current_timestamp", KW_CURRENT_TIMESTAMP},
		{"current_timestampx", ID}, {"current_times", ID},
		{"auto_increment", KW_AUTO_INCREMENT}, {"auto_incremenu", ID},
		{"transaction_id", KW_TRANSACTION_ID}, {"transaction_ids", ID},
		{"int", KW_INT}, {"into", IN_PREFIX}, {"in", IN_PREFIX}, {"i", ID},
		{"abcdefghijklmnop", ID}, {"abcdefghijklmnopq", ID}, {"42", NUM}, {"-", ERR},
	}
	for _, t := range tests {
		in := []byte(t.str + " \x00")
		kind, end := lex(in, 0)
		if kind != t.kind || end != len(t.str) {
			panic(fmt.Sprintf("%q: got kind %d end %d, want kind %d end %d",
				t.str, kind, end, t.kind, len(t.str)))
		}
	}
	// A token at the very end of the input: the lookup must not read past it.
	for _, t := range tests {
		in := append([]byte(t.str), 0)
		in = in[:len(in):len(in)]
		if kind, end := lex(in, 0); kind != t.kind || end != len(t.str) {
			panic(t.str)
		}
	}
}
