// Code generated by re2go, DO NOT EDIT.
//go:generate re2go $INPUT -o $OUTPUT -i --api simple
package main



// No literal rule is subsumed by a later rule: the keyword table is not used, the lexer is the
// plain DFA and re2c warns about it.
func lex(yyinput []byte) int {
	var yycursor int
	
{
	var yych byte
	yych = yyinput[yycursor]
	switch (yych) {
	case '0','1','2','3','4','5','6','7','8','9':
		goto yy3
	case 'i':
		goto yy5
	default:
		goto yy1
	}
yy1:
	yycursor += 1
yy2:
	{ return 3 }
yy3:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case '0','1','2','3','4','5','6','7','8','9':
		goto yy3
	default:
		goto yy4
	}
yy4:
	{ return 2 }
yy5:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'f':
		goto yy6
	default:
		goto yy2
	}
yy6:
	yycursor += 1
	{ return 1 }
}

}

func main() {
	if lex([]byte("if\x00")) != 1 || lex([]byte("12\x00")) != 2 || lex([]byte("i\x00")) != 3 {
		panic("error")
	}
}
codegen/go/013_keywords_fallback.re:10:1: warning: keyword table is not used: no literal rule is subsumed by a later rule [-Wkeyword-table]
