// Code generated by re2go, DO NOT EDIT.
//go:generate re2go $INPUT -o $OUTPUT -i
// Parity of --vectorize-linear with the ordinary DFA for the simple API without YYFILL.
// Each rule set is compiled twice, with and without the option; both lexers must return the same
// rule and the same cursor for every prefix and near miss of the literals, with and without
// trailing padding after the sentinel. An out-of-range read panics.
package main

import (
	"fmt"
	"os"
)



func headers_0(yyinput string) (int, int) {
	yycursor, yymarker := 0, 0
	_ = yymarker
	
{
	var yych byte
	yych = yyinput[yycursor]
	switch (yych) {
	case '-':
		fallthrough
	case 'B':
		fallthrough
	case 'D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S':
		fallthrough
	case 'V','W','X','Y','Z':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy3
	case 'A':
		goto yy4
	case 'C':
		goto yy5
	case 'T':
		goto yy6
	case 'U':
		goto yy7
	default:
		goto yy1
	}
yy1:
	yycursor += 1
yy2:
	{ return 0, yycursor }
yy3:
	yycursor += 1
	yymarker = yycursor
	yych = yyinput[yycursor]
	switch (yych) {
	case '-':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy8
	case ':':
		goto yy11
	default:
		goto yy2
	}
yy4:
	yycursor += 1
	yymarker = yycursor
	yych = yyinput[yycursor]
	switch (yych) {
	case '-':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case 'a','b':
		fallthrough
	case 'd','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t':
		fallthrough
	case 'v','w','x','y','z':
		goto yy8
	case ':':
		goto yy11
	case 'c':
		goto yy12
	case 'u':
		goto yy13
	default:
		goto yy2
	}
yy5:
	yycursor += 1
	yymarker = yycursor
	yych = yyinput[yycursor]
	switch (yych) {
	case '-':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case 'b','c','d','e','f','g','h','i','j','k','l','m','n':
		fallthrough
	case 'p','q','r','s','t','u','v','w','x','y','z':
		goto yy8
	case ':':
		goto yy11
	case 'a':
		goto yy14
	case 'o':
		goto yy15
	default:
		goto yy2
	}
yy6:
	yycursor += 1
	yymarker = yycursor
	yych = yyinput[yycursor]
	switch (yych) {
	case '-':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q':
		fallthrough
	case 's','t','u','v','w','x','y','z':
		goto yy8
	case ':':
		goto yy11
	case 'r':
		goto yy16
	default:
		goto yy2
	}
yy7:
	yycursor += 1
	yymarker = yycursor
	yych = yyinput[yycursor]
	switch (yych) {
	case '-':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r':
		fallthrough
	case 't','u','v','w','x','y','z':
		goto yy8
	case ':':
		goto yy11
	case 's':
		goto yy17
	default:
		goto yy2
	}
yy8:
	yycursor += 1
	yych = yyinput[yycursor]
yy9:
	switch (yych) {
	case '-':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy8
	case ':':
		goto yy11
	default:
		goto yy10
	}
yy10:
	yycursor = yymarker
	goto yy2
yy11:
	yycursor += 1
	{ return 9, yycursor }
yy12:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'c':
		goto yy18
	default:
		goto yy9
	}
yy13:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 't':
		goto yy19
	default:
		goto yy9
	}
yy14:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'c':
		goto yy20
	default:
		goto yy9
	}
yy15:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'n':
		goto yy21
	default:
		goto yy9
	}
yy16:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'a':
		goto yy22
	default:
		goto yy9
	}
yy17:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'e':
		goto yy23
	default:
		goto yy9
	}
yy18:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'e':
		goto yy24
	default:
		goto yy9
	}
yy19:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'h':
		goto yy25
	default:
		goto yy9
	}
yy20:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'h':
		goto yy26
	default:
		goto yy9
	}
yy21:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'n':
		goto yy27
	case 't':
		goto yy28
	default:
		goto yy9
	}
yy22:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'n':
		goto yy29
	default:
		goto yy9
	}
yy23:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'r':
		goto yy30
	default:
		goto yy9
	}
yy24:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'p':
		goto yy31
	default:
		goto yy9
	}
yy25:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'o':
		goto yy32
	default:
		goto yy9
	}
yy26:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'e':
		goto yy33
	default:
		goto yy9
	}
yy27:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'e':
		goto yy34
	default:
		goto yy9
	}
yy28:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'e':
		goto yy35
	default:
		goto yy9
	}
yy29:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 's':
		goto yy36
	default:
		goto yy9
	}
yy30:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case '-':
		goto yy37
	default:
		goto yy9
	}
yy31:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 't':
		goto yy38
	default:
		goto yy9
	}
yy32:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'r':
		goto yy39
	default:
		goto yy9
	}
yy33:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case '-':
		goto yy40
	default:
		goto yy9
	}
yy34:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'c':
		goto yy41
	default:
		goto yy9
	}
yy35:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'n':
		goto yy42
	default:
		goto yy9
	}
yy36:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'f':
		goto yy43
	default:
		goto yy9
	}
yy37:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'A':
		goto yy44
	default:
		goto yy9
	}
yy38:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case '-':
		goto yy45
	default:
		goto yy9
	}
yy39:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'i':
		goto yy46
	default:
		goto yy9
	}
yy40:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'C':
		goto yy47
	default:
		goto yy9
	}
yy41:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 't':
		goto yy48
	default:
		goto yy9
	}
yy42:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 't':
		goto yy49
	default:
		goto yy9
	}
yy43:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'e':
		goto yy50
	default:
		goto yy9
	}
yy44:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'g':
		goto yy51
	default:
		goto yy9
	}
yy45:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'E':
		goto yy52
	default:
		goto yy9
	}
yy46:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'z':
		goto yy53
	default:
		goto yy9
	}
yy47:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'o':
		goto yy54
	default:
		goto yy9
	}
yy48:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'i':
		goto yy55
	default:
		goto yy9
	}
yy49:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case '-':
		goto yy56
	default:
		goto yy9
	}
yy50:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'r':
		goto yy57
	default:
		goto yy9
	}
yy51:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'e':
		goto yy58
	default:
		goto yy9
	}
yy52:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'n':
		goto yy59
	default:
		goto yy9
	}
yy53:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'a':
		goto yy60
	default:
		goto yy9
	}
yy54:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'n':
		goto yy61
	default:
		goto yy9
	}
yy55:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'o':
		goto yy62
	default:
		goto yy9
	}
yy56:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'L':
		goto yy63
	case 'T':
		goto yy64
	default:
		goto yy9
	}
yy57:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case '-':
		goto yy65
	default:
		goto yy9
	}
yy58:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'n':
		goto yy66
	default:
		goto yy9
	}
yy59:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'c':
		goto yy67
	default:
		goto yy9
	}
yy60:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 't':
		goto yy68
	default:
		goto yy9
	}
yy61:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 't':
		goto yy69
	default:
		goto yy9
	}
yy62:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'n':
		goto yy70
	default:
		goto yy9
	}
yy63:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'e':
		goto yy71
	default:
		goto yy9
	}
yy64:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'y':
		goto yy72
	default:
		goto yy9
	}
yy65:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'E':
		goto yy73
	default:
		goto yy9
	}
yy66:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 't':
		goto yy74
	default:
		goto yy9
	}
yy67:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'o':
		goto yy75
	default:
		goto yy9
	}
yy68:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'i':
		goto yy76
	default:
		goto yy9
	}
yy69:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'r':
		goto yy77
	default:
		goto yy9
	}
yy70:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case ':':
		goto yy78
	default:
		goto yy9
	}
yy71:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'n':
		goto yy79
	default:
		goto yy9
	}
yy72:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'p':
		goto yy80
	default:
		goto yy9
	}
yy73:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'n':
		goto yy81
	default:
		goto yy9
	}
yy74:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case ':':
		goto yy82
	default:
		goto yy9
	}
yy75:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'd':
		goto yy83
	default:
		goto yy9
	}
yy76:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'o':
		goto yy84
	default:
		goto yy9
	}
yy77:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'o':
		goto yy85
	default:
		goto yy9
	}
yy78:
	yycursor += 1
	{ return 8, yycursor }
yy79:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'g':
		goto yy86
	default:
		goto yy9
	}
yy80:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'e':
		goto yy87
	default:
		goto yy9
	}
yy81:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'c':
		goto yy88
	default:
		goto yy9
	}
yy82:
	yycursor += 1
	{ return 6, yycursor }
yy83:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'i':
		goto yy89
	default:
		goto yy9
	}
yy84:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'n':
		goto yy90
	default:
		goto yy9
	}
yy85:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'l':
		goto yy91
	default:
		goto yy9
	}
yy86:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 't':
		goto yy92
	default:
		goto yy9
	}
yy87:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case ':':
		goto yy93
	default:
		goto yy9
	}
yy88:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'o':
		goto yy94
	default:
		goto yy9
	}
yy89:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'n':
		goto yy95
	default:
		goto yy9
	}
yy90:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case ':':
		goto yy96
	default:
		goto yy9
	}
yy91:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case ':':
		goto yy97
	default:
		goto yy9
	}
yy92:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'h':
		goto yy98
	default:
		goto yy9
	}
yy93:
	yycursor += 1
	{ return 2, yycursor }
yy94:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'd':
		goto yy99
	default:
		goto yy9
	}
yy95:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'g':
		goto yy100
	default:
		goto yy9
	}
yy96:
	yycursor += 1
	{ return 4, yycursor }
yy97:
	yycursor += 1
	{ return 7, yycursor }
yy98:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case ':':
		goto yy101
	default:
		goto yy9
	}
yy99:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'i':
		goto yy102
	default:
		goto yy9
	}
yy100:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case ':':
		goto yy103
	default:
		goto yy9
	}
yy101:
	yycursor += 1
	{ return 1, yycursor }
yy102:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'n':
		goto yy104
	default:
		goto yy9
	}
yy103:
	yycursor += 1
	{ return 5, yycursor }
yy104:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'g':
		goto yy105
	default:
		goto yy9
	}
yy105:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case ':':
		goto yy106
	default:
		goto yy9
	}
yy106:
	yycursor += 1
	{ return 3, yycursor }
}

}

func headers_1(yyinput string) (int, int) {
	yycursor, yymarker := 0, 0
	_ = yymarker
	
{
	var yych byte
	yych = yyinput[yycursor]
	switch (yych) {
	case '-':
		fallthrough
	case 'B':
		fallthrough
	case 'D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S':
		fallthrough
	case 'V','W','X','Y','Z':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy110
	case 'A':
		goto yy111
	case 'C':
		goto yy112
	case 'T':
		goto yy113
	case 'U':
		goto yy114
	default:
		goto yy108
	}
yy108:
	yycursor += 1
yy109:
	{ return 0, yycursor }
yy110:
	yycursor += 1
	yymarker = yycursor
	yych = yyinput[yycursor]
	switch (yych) {
	case '-':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy115
	case ':':
		goto yy118
	default:
		goto yy109
	}
yy111:
	yycursor += 1
	yymarker = yycursor
	yych = yyinput[yycursor]
	switch (yych) {
	case '-':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case 'a','b':
		fallthrough
	case 'd','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t':
		fallthrough
	case 'v','w','x','y','z':
		goto yy115
	case ':':
		goto yy118
	case 'c':
		goto yy119
	case 'u':
		goto yy120
	default:
		goto yy109
	}
yy112:
	yycursor += 1
	yymarker = yycursor
	yych = yyinput[yycursor]
	switch (yych) {
	case '-':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case 'b','c','d','e','f','g','h','i','j','k','l','m','n':
		fallthrough
	case 'p','q','r','s','t','u','v','w','x','y','z':
		goto yy115
	case ':':
		goto yy118
	case 'a':
		goto yy121
	case 'o':
		goto yy122
	default:
		goto yy109
	}
yy113:
	yycursor += 1
	yymarker = yycursor
	yych = yyinput[yycursor]
	switch (yych) {
	case '-':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q':
		fallthrough
	case 's','t','u','v','w','x','y','z':
		goto yy115
	case ':':
		goto yy118
	case 'r':
		goto yy123
	default:
		goto yy109
	}
yy114:
	yycursor += 1
	yymarker = yycursor
	yych = yyinput[yycursor]
	switch (yych) {
	case '-':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r':
		fallthrough
	case 't','u','v','w','x','y','z':
		goto yy115
	case ':':
		goto yy118
	case 's':
		goto yy124
	default:
		goto yy109
	}
yy115:
	yycursor += 1
	yych = yyinput[yycursor]
yy116:
	switch (yych) {
	case '-':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy115
	case ':':
		goto yy118
	default:
		goto yy117
	}
yy117:
	yycursor = yymarker
	goto yy109
yy118:
	yycursor += 1
	{ return 9, yycursor }
yy119:
	yycursor += 1
	yych = yyinput[yycursor]
	if (len(yyinput)-yycursor >= 8) {
		if (uint64(yyinput[yycursor:][7])<<(8*7) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) | uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][4])<<(8*4) | uint64(yyinput[yycursor:][5])<<(8*5) | uint64(yyinput[yycursor:][6])<<(8*6) == 0x636e452d74706563) {
			yycursor += 7
			goto yy174
		} else {
			switch (((((((uint64(yyinput[yycursor:][7])<<(8*7) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) | uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][4])<<(8*4) | uint64(yyinput[yycursor:][5])<<(8*5) | uint64(yyinput[yycursor:][6])<<(8*6) ^ 0x636e452d74706563) - 1) &^ (uint64(yyinput[yycursor:][7])<<(8*7) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) | uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][4])<<(8*4) | uint64(yyinput[yycursor:][5])<<(8*5) | uint64(yyinput[yycursor:][6])<<(8*6) ^ 0x636e452d74706563)) >> 7) & 0x0101010101010101) * 0x0101010101010101) >> 56) {
			case 1:
				goto yy125
			case 2:
				yycursor += 1
				goto yy131
			case 3:
				yycursor += 2
				goto yy138
			case 4:
				yycursor += 3
				goto yy145
			case 5:
				yycursor += 4
				goto yy152
			case 6:
				yycursor += 5
				goto yy159
			case 7:
				yycursor += 6
				goto yy166
			}
		}
	}
	switch (yych) {
	case 'c':
		goto yy125
	default:
		goto yy116
	}
yy120:
	yycursor += 1
	yych = yyinput[yycursor]
	if (len(yyinput)-yycursor >= 8) {
		if (uint64(yyinput[yycursor:][7])<<(8*7) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) | uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][4])<<(8*4) | uint64(yyinput[yycursor:][5])<<(8*5) | uint64(yyinput[yycursor:][6])<<(8*6) == 0x74617a69726f6874) {
			yycursor += 7
			goto yy175
		} else {
			switch (((((((uint64(yyinput[yycursor:][7])<<(8*7) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) | uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][4])<<(8*4) | uint64(yyinput[yycursor:][5])<<(8*5) | uint64(yyinput[yycursor:][6])<<(8*6) ^ 0x74617a69726f6874) - 1) &^ (uint64(yyinput[yycursor:][7])<<(8*7) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) | uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][4])<<(8*4) | uint64(yyinput[yycursor:][5])<<(8*5) | uint64(yyinput[yycursor:][6])<<(8*6) ^ 0x74617a69726f6874)) >> 7) & 0x0101010101010101) * 0x0101010101010101) >> 56) {
			case 1:
				goto yy126
			case 2:
				yycursor += 1
				goto yy132
			case 3:
				yycursor += 2
				goto yy139
			case 4:
				yycursor += 3
				goto yy146
			case 5:
				yycursor += 4
				goto yy153
			case 6:
				yycursor += 5
				goto yy160
			case 7:
				yycursor += 6
				goto yy167
			}
		}
	}
	switch (yych) {
	case 't':
		goto yy126
	default:
		goto yy116
	}
yy121:
	yycursor += 1
	yych = yyinput[yycursor]
	if (len(yyinput)-yycursor >= 8) {
		if (uint64(yyinput[yycursor:][7])<<(8*7) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) | uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][4])<<(8*4) | uint64(yyinput[yycursor:][5])<<(8*5) | uint64(yyinput[yycursor:][6])<<(8*6) == 0x746e6f432d656863) {
			yycursor += 7
			goto yy176
		} else {
			switch (((((((uint64(yyinput[yycursor:][7])<<(8*7) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) | uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][4])<<(8*4) | uint64(yyinput[yycursor:][5])<<(8*5) | uint64(yyinput[yycursor:][6])<<(8*6) ^ 0x746e6f432d656863) - 1) &^ (uint64(yyinput[yycursor:][7])<<(8*7) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) | uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][4])<<(8*4) | uint64(yyinput[yycursor:][5])<<(8*5) | uint64(yyinput[yycursor:][6])<<(8*6) ^ 0x746e6f432d656863)) >> 7) & 0x0101010101010101) * 0x0101010101010101) >> 56) {
			case 1:
				goto yy127
			case 2:
				yycursor += 1
				goto yy133
			case 3:
				yycursor += 2
				goto yy140
			case 4:
				yycursor += 3
				goto yy147
			case 5:
				yycursor += 4
				goto yy154
			case 6:
				yycursor += 5
				goto yy161
			case 7:
				yycursor += 6
				goto yy168
			}
		}
	}
	switch (yych) {
	case 'c':
		goto yy127
	default:
		goto yy116
	}
yy122:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'n':
		goto yy128
	default:
		goto yy116
	}
yy123:
	yycursor += 1
	yych = yyinput[yycursor]
	if (len(yyinput)-yycursor >= 8) {
		if (uint64(yyinput[yycursor:][7])<<(8*7) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) | uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][4])<<(8*4) | uint64(yyinput[yycursor:][5])<<(8*5) | uint64(yyinput[yycursor:][6])<<(8*6) == 0x452d726566736e61) {
			yycursor += 7
			goto yy180
		} else {
			switch (((((((uint64(yyinput[yycursor:][7])<<(8*7) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) | uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][4])<<(8*4) | uint64(yyinput[yycursor:][5])<<(8*5) | uint64(yyinput[yycursor:][6])<<(8*6) ^ 0x452d726566736e61) - 1) &^ (uint64(yyinput[yycursor:][7])<<(8*7) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) | uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][4])<<(8*4) | uint64(yyinput[yycursor:][5])<<(8*5) | uint64(yyinput[yycursor:][6])<<(8*6) ^ 0x452d726566736e61)) >> 7) & 0x0101010101010101) * 0x0101010101010101) >> 56) {
			case 1:
				goto yy129
			case 2:
				yycursor += 1
				goto yy136
			case 3:
				yycursor += 2
				goto yy143
			case 4:
				yycursor += 3
				goto yy150
			case 5:
				yycursor += 4
				goto yy157
			case 6:
				yycursor += 5
				goto yy164
			case 7:
				yycursor += 6
				goto yy172
			}
		}
	}
	switch (yych) {
	case 'a':
		goto yy129
	default:
		goto yy116
	}
yy124:
	yycursor += 1
	yych = yyinput[yycursor]
	if (len(yyinput)-yycursor >= 8) {
		if (uint64(yyinput[yycursor:][7])<<(8*7) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) | uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][4])<<(8*4) | uint64(yyinput[yycursor:][5])<<(8*5) | uint64(yyinput[yycursor:][6])<<(8*6) == 0x746e6567412d7265) {
			yycursor += 7
			goto yy181
		} else {
			switch (((((((uint64(yyinput[yycursor:][7])<<(8*7) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) | uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][4])<<(8*4) | uint64(yyinput[yycursor:][5])<<(8*5) | uint64(yyinput[yycursor:][6])<<(8*6) ^ 0x746e6567412d7265) - 1) &^ (uint64(yyinput[yycursor:][7])<<(8*7) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) | uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][4])<<(8*4) | uint64(yyinput[yycursor:][5])<<(8*5) | uint64(yyinput[yycursor:][6])<<(8*6) ^ 0x746e6567412d7265)) >> 7) & 0x0101010101010101) * 0x0101010101010101) >> 56) {
			case 1:
				goto yy130
			case 2:
				yycursor += 1
				goto yy137
			case 3:
				yycursor += 2
				goto yy144
			case 4:
				yycursor += 3
				goto yy151
			case 5:
				yycursor += 4
				goto yy158
			case 6:
				yycursor += 5
				goto yy165
			case 7:
				yycursor += 6
				goto yy173
			}
		}
	}
	switch (yych) {
	case 'e':
		goto yy130
	default:
		goto yy116
	}
yy125:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'e':
		goto yy131
	default:
		goto yy116
	}
yy126:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'h':
		goto yy132
	default:
		goto yy116
	}
yy127:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'h':
		goto yy133
	default:
		goto yy116
	}
yy128:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'n':
		goto yy134
	case 't':
		goto yy135
	default:
		goto yy116
	}
yy129:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'n':
		goto yy136
	default:
		goto yy116
	}
yy130:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'r':
		goto yy137
	default:
		goto yy116
	}
yy131:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'p':
		goto yy138
	default:
		goto yy116
	}
yy132:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'o':
		goto yy139
	default:
		goto yy116
	}
yy133:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'e':
		goto yy140
	default:
		goto yy116
	}
yy134:
	yycursor += 1
	yych = yyinput[yycursor]
	if (len(yyinput)-yycursor >= 4) {
		if (uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) == 0x69746365) {
			yycursor += 3
			goto yy162
		} else {
			switch (((((((uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) ^ 0x69746365) - 1) &^ (uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) ^ 0x69746365)) >> 7) & 0x0101010101010101) * 0x0101010101010101) >> 56) {
			case 1:
				goto yy141
			case 2:
				yycursor += 1
				goto yy148
			case 3:
				yycursor += 2
				goto yy155
			}
		}
	}
	switch (yych) {
	case 'e':
		goto yy141
	default:
		goto yy116
	}
yy135:
	yycursor += 1
	yych = yyinput[yycursor]
	if (len(yyinput)-yycursor >= 4) {
		if (uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) == 0x2d746e65) {
			yycursor += 3
			goto yy163
		} else {
			switch (((((((uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) ^ 0x2d746e65) - 1) &^ (uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) ^ 0x2d746e65)) >> 7) & 0x0101010101010101) * 0x0101010101010101) >> 56) {
			case 1:
				goto yy142
			case 2:
				yycursor += 1
				goto yy149
			case 3:
				yycursor += 2
				goto yy156
			}
		}
	}
	switch (yych) {
	case 'e':
		goto yy142
	default:
		goto yy116
	}
yy136:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 's':
		goto yy143
	default:
		goto yy116
	}
yy137:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case '-':
		goto yy144
	default:
		goto yy116
	}
yy138:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 't':
		goto yy145
	default:
		goto yy116
	}
yy139:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'r':
		goto yy146
	default:
		goto yy116
	}
yy140:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case '-':
		goto yy147
	default:
		goto yy116
	}
yy141:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'c':
		goto yy148
	default:
		goto yy116
	}
yy142:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'n':
		goto yy149
	default:
		goto yy116
	}
yy143:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'f':
		goto yy150
	default:
		goto yy116
	}
yy144:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'A':
		goto yy151
	default:
		goto yy116
	}
yy145:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case '-':
		goto yy152
	default:
		goto yy116
	}
yy146:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'i':
		goto yy153
	default:
		goto yy116
	}
yy147:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'C':
		goto yy154
	default:
		goto yy116
	}
yy148:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 't':
		goto yy155
	default:
		goto yy116
	}
yy149:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 't':
		goto yy156
	default:
		goto yy116
	}
yy150:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'e':
		goto yy157
	default:
		goto yy116
	}
yy151:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'g':
		goto yy158
	default:
		goto yy116
	}
yy152:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'E':
		goto yy159
	default:
		goto yy116
	}
yy153:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'z':
		goto yy160
	default:
		goto yy116
	}
yy154:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'o':
		goto yy161
	default:
		goto yy116
	}
yy155:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'i':
		goto yy162
	default:
		goto yy116
	}
yy156:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case '-':
		goto yy163
	default:
		goto yy116
	}
yy157:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'r':
		goto yy164
	default:
		goto yy116
	}
yy158:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'e':
		goto yy165
	default:
		goto yy116
	}
yy159:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'n':
		goto yy166
	default:
		goto yy116
	}
yy160:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'a':
		goto yy167
	default:
		goto yy116
	}
yy161:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'n':
		goto yy168
	default:
		goto yy116
	}
yy162:
	yycursor += 1
	yych = yyinput[yycursor]
	if (len(yyinput)-yycursor >= 2) {
		if (uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][0]) == 0x6e6f) {
			yycursor += 1
			goto yy177
		} else {
			switch (((((((uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][0]) ^ 0x6e6f) - 1) &^ (uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][0]) ^ 0x6e6f)) >> 7) & 0x0101010101010101) * 0x0101010101010101) >> 56) {
			case 1:
				goto yy169
			}
		}
	}
	switch (yych) {
	case 'o':
		goto yy169
	default:
		goto yy116
	}
yy163:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'L':
		goto yy170
	case 'T':
		goto yy171
	default:
		goto yy116
	}
yy164:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case '-':
		goto yy172
	default:
		goto yy116
	}
yy165:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'n':
		goto yy173
	default:
		goto yy116
	}
yy166:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'c':
		goto yy174
	default:
		goto yy116
	}
yy167:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 't':
		goto yy175
	default:
		goto yy116
	}
yy168:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 't':
		goto yy176
	default:
		goto yy116
	}
yy169:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'n':
		goto yy177
	default:
		goto yy116
	}
yy170:
	yycursor += 1
	yych = yyinput[yycursor]
	if (len(yyinput)-yycursor >= 4) {
		if (uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) == 0x74676e65) {
			yycursor += 3
			goto yy199
		} else {
			switch (((((((uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) ^ 0x74676e65) - 1) &^ (uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) ^ 0x74676e65)) >> 7) & 0x0101010101010101) * 0x0101010101010101) >> 56) {
			case 1:
				goto yy178
			case 2:
				yycursor += 1
				goto yy186
			case 3:
				yycursor += 2
				goto yy193
			}
		}
	}
	switch (yych) {
	case 'e':
		goto yy178
	default:
		goto yy116
	}
yy171:
	yycursor += 1
	yych = yyinput[yycursor]
	if (len(yyinput)-yycursor >= 4) {
		if (uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) == 0x3a657079) {
			yycursor += 3
			goto yy200
		} else {
			switch (((((((uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) ^ 0x3a657079) - 1) &^ (uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) ^ 0x3a657079)) >> 7) & 0x0101010101010101) * 0x0101010101010101) >> 56) {
			case 1:
				goto yy179
			case 2:
				yycursor += 1
				goto yy187
			case 3:
				yycursor += 2
				goto yy194
			}
		}
	}
	switch (yych) {
	case 'y':
		goto yy179
	default:
		goto yy116
	}
yy172:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'E':
		goto yy180
	default:
		goto yy116
	}
yy173:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 't':
		goto yy181
	default:
		goto yy116
	}
yy174:
	yycursor += 1
	yych = yyinput[yycursor]
	if (len(yyinput)-yycursor >= 4) {
		if (uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) == 0x6e69646f) {
			yycursor += 3
			goto yy202
		} else {
			switch (((((((uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) ^ 0x6e69646f) - 1) &^ (uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) ^ 0x6e69646f)) >> 7) & 0x0101010101010101) * 0x0101010101010101) >> 56) {
			case 1:
				goto yy182
			case 2:
				yycursor += 1
				goto yy190
			case 3:
				yycursor += 2
				goto yy196
			}
		}
	}
	switch (yych) {
	case 'o':
		goto yy182
	default:
		goto yy116
	}
yy175:
	yycursor += 1
	yych = yyinput[yycursor]
	if (len(yyinput)-yycursor >= 4) {
		if (uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) == 0x3a6e6f69) {
			yycursor += 3
			goto yy203
		} else {
			switch (((((((uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) ^ 0x3a6e6f69) - 1) &^ (uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) ^ 0x3a6e6f69)) >> 7) & 0x0101010101010101) * 0x0101010101010101) >> 56) {
			case 1:
				goto yy183
			case 2:
				yycursor += 1
				goto yy191
			case 3:
				yycursor += 2
				goto yy197
			}
		}
	}
	switch (yych) {
	case 'i':
		goto yy183
	default:
		goto yy116
	}
yy176:
	yycursor += 1
	yych = yyinput[yycursor]
	if (len(yyinput)-yycursor >= 4) {
		if (uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) == 0x3a6c6f72) {
			yycursor += 3
			goto yy204
		} else {
			switch (((((((uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) ^ 0x3a6c6f72) - 1) &^ (uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) ^ 0x3a6c6f72)) >> 7) & 0x0101010101010101) * 0x0101010101010101) >> 56) {
			case 1:
				goto yy184
			case 2:
				yycursor += 1
				goto yy192
			case 3:
				yycursor += 2
				goto yy198
			}
		}
	}
	switch (yych) {
	case 'r':
		goto yy184
	default:
		goto yy116
	}
yy177:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case ':':
		goto yy185
	default:
		goto yy116
	}
yy178:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'n':
		goto yy186
	default:
		goto yy116
	}
yy179:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'p':
		goto yy187
	default:
		goto yy116
	}
yy180:
	yycursor += 1
	yych = yyinput[yycursor]
	if (len(yyinput)-yycursor >= 8) {
		if (uint64(yyinput[yycursor:][7])<<(8*7) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) | uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][4])<<(8*4) | uint64(yyinput[yycursor:][5])<<(8*5) | uint64(yyinput[yycursor:][6])<<(8*6) == 0x3a676e69646f636e) {
			yycursor += 7
			goto yy213
		} else {
			switch (((((((uint64(yyinput[yycursor:][7])<<(8*7) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) | uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][4])<<(8*4) | uint64(yyinput[yycursor:][5])<<(8*5) | uint64(yyinput[yycursor:][6])<<(8*6) ^ 0x3a676e69646f636e) - 1) &^ (uint64(yyinput[yycursor:][7])<<(8*7) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) | uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][4])<<(8*4) | uint64(yyinput[yycursor:][5])<<(8*5) | uint64(yyinput[yycursor:][6])<<(8*6) ^ 0x3a676e69646f636e)) >> 7) & 0x0101010101010101) * 0x0101010101010101) >> 56) {
			case 1:
				goto yy188
			case 2:
				yycursor += 1
				goto yy195
			case 3:
				yycursor += 2
				goto yy201
			case 4:
				yycursor += 3
				goto yy206
			case 5:
				yycursor += 4
				goto yy209
			case 6:
				yycursor += 5
				goto yy211
			case 7:
				yycursor += 6
				goto yy212
			}
		}
	}
	switch (yych) {
	case 'n':
		goto yy188
	default:
		goto yy116
	}
yy181:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case ':':
		goto yy189
	default:
		goto yy116
	}
yy182:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'd':
		goto yy190
	default:
		goto yy116
	}
yy183:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'o':
		goto yy191
	default:
		goto yy116
	}
yy184:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'o':
		goto yy192
	default:
		goto yy116
	}
yy185:
	yycursor += 1
	{ return 8, yycursor }
yy186:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'g':
		goto yy193
	default:
		goto yy116
	}
yy187:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'e':
		goto yy194
	default:
		goto yy116
	}
yy188:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'c':
		goto yy195
	default:
		goto yy116
	}
yy189:
	yycursor += 1
	{ return 6, yycursor }
yy190:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'i':
		goto yy196
	default:
		goto yy116
	}
yy191:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'n':
		goto yy197
	default:
		goto yy116
	}
yy192:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'l':
		goto yy198
	default:
		goto yy116
	}
yy193:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 't':
		goto yy199
	default:
		goto yy116
	}
yy194:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case ':':
		goto yy200
	default:
		goto yy116
	}
yy195:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'o':
		goto yy201
	default:
		goto yy116
	}
yy196:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'n':
		goto yy202
	default:
		goto yy116
	}
yy197:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case ':':
		goto yy203
	default:
		goto yy116
	}
yy198:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case ':':
		goto yy204
	default:
		goto yy116
	}
yy199:
	yycursor += 1
	yych = yyinput[yycursor]
	if (len(yyinput)-yycursor >= 2) {
		if (uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][0]) == 0x3a68) {
			yycursor += 1
			goto yy208
		} else {
			switch (((((((uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][0]) ^ 0x3a68) - 1) &^ (uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][0]) ^ 0x3a68)) >> 7) & 0x0101010101010101) * 0x0101010101010101) >> 56) {
			case 1:
				goto yy205
			}
		}
	}
	switch (yych) {
	case 'h':
		goto yy205
	default:
		goto yy116
	}
yy200:
	yycursor += 1
	{ return 2, yycursor }
yy201:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'd':
		goto yy206
	default:
		goto yy116
	}
yy202:
	yycursor += 1
	yych = yyinput[yycursor]
	if (len(yyinput)-yycursor >= 2) {
		if (uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][0]) == 0x3a67) {
			yycursor += 1
			goto yy210
		} else {
			switch (((((((uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][0]) ^ 0x3a67) - 1) &^ (uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][0]) ^ 0x3a67)) >> 7) & 0x0101010101010101) * 0x0101010101010101) >> 56) {
			case 1:
				goto yy207
			}
		}
	}
	switch (yych) {
	case 'g':
		goto yy207
	default:
		goto yy116
	}
yy203:
	yycursor += 1
	{ return 4, yycursor }
yy204:
	yycursor += 1
	{ return 7, yycursor }
yy205:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case ':':
		goto yy208
	default:
		goto yy116
	}
yy206:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'i':
		goto yy209
	default:
		goto yy116
	}
yy207:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case ':':
		goto yy210
	default:
		goto yy116
	}
yy208:
	yycursor += 1
	{ return 1, yycursor }
yy209:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'n':
		goto yy211
	default:
		goto yy116
	}
yy210:
	yycursor += 1
	{ return 5, yycursor }
yy211:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'g':
		goto yy212
	default:
		goto yy116
	}
yy212:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case ':':
		goto yy213
	default:
		goto yy116
	}
yy213:
	yycursor += 1
	{ return 3, yycursor }
}

}

var headers_words = []string{
	"\x43\x6f\x6e\x74\x65\x6e\x74\x2d\x4c\x65\x6e\x67\x74\x68\x3a",
	"\x43\x6f\x6e\x74\x65\x6e\x74\x2d\x54\x79\x70\x65\x3a",
	"\x54\x72\x61\x6e\x73\x66\x65\x72\x2d\x45\x6e\x63\x6f\x64\x69\x6e\x67\x3a",
	"\x41\x75\x74\x68\x6f\x72\x69\x7a\x61\x74\x69\x6f\x6e\x3a",
	"\x41\x63\x63\x65\x70\x74\x2d\x45\x6e\x63\x6f\x64\x69\x6e\x67\x3a",
	"\x55\x73\x65\x72\x2d\x41\x67\x65\x6e\x74\x3a",
	"\x43\x61\x63\x68\x65\x2d\x43\x6f\x6e\x74\x72\x6f\x6c\x3a",
	"\x43\x6f\x6e\x6e\x65\x63\x74\x69\x6f\x6e\x3a",
	"\x43\x6f\x6e\x74\x65\x6e\x74\x2d\x4c\x61\x6e\x67\x75\x61\x67\x65\x3a",
	"\x41\x63\x63\x65\x70\x74\x3a",
	"\x43\x6f\x6e\x6e\x65\x63\x74\x69\x6f\x6e\x2d\x49\x64\x3a",
	"\x43\x61\x63\x68\x65\x2d\x53\x74\x61\x74\x75\x73\x3a",
}



func keywords_0(yyinput string) (int, int) {
	yycursor, yymarker := 0, 0
	_ = yymarker
	
{
	var yych byte
	yych = yyinput[yycursor]
	switch (yych) {
	case ' ':
		goto yy216
	case 'A':
		fallthrough
	case 'C':
		fallthrough
	case 'E':
		fallthrough
	case 'G','H':
		fallthrough
	case 'J','K','L','M','N','O','P','Q','R':
		fallthrough
	case 'T':
		fallthrough
	case 'V':
		fallthrough
	case 'X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy218
	case 'B':
		goto yy221
	case 'D':
		goto yy222
	case 'F':
		goto yy223
	case 'I':
		goto yy224
	case 'S':
		goto yy225
	case 'U':
		goto yy226
	case 'W':
		goto yy227
	default:
		goto yy215
	}
yy215:
	yycursor += 1
	{ return 0, yycursor }
yy216:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case ' ':
		goto yy216
	default:
		goto yy217
	}
yy217:
	{ return 10, yycursor }
yy218:
	yycursor += 1
	yych = yyinput[yycursor]
yy219:
	switch (yych) {
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy218
	default:
		goto yy220
	}
yy220:
	{ return 9, yycursor }
yy221:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'E':
		goto yy228
	default:
		goto yy219
	}
yy222:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'E':
		goto yy229
	case 'I':
		goto yy230
	default:
		goto yy219
	}
yy223:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'R':
		goto yy231
	default:
		goto yy219
	}
yy224:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'N':
		goto yy232
	default:
		goto yy219
	}
yy225:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'E':
		goto yy233
	default:
		goto yy219
	}
yy226:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'P':
		goto yy234
	default:
		goto yy219
	}
yy227:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'H':
		goto yy235
	default:
		goto yy219
	}
yy228:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'T':
		goto yy236
	default:
		goto yy219
	}
yy229:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'L':
		goto yy237
	default:
		goto yy219
	}
yy230:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'S':
		goto yy238
	default:
		goto yy219
	}
yy231:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'O':
		goto yy239
	default:
		goto yy219
	}
yy232:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'S':
		goto yy240
	default:
		goto yy219
	}
yy233:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'L':
		goto yy241
	default:
		goto yy219
	}
yy234:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'D':
		goto yy242
	default:
		goto yy219
	}
yy235:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'E':
		goto yy243
	default:
		goto yy219
	}
yy236:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'W':
		goto yy244
	default:
		goto yy219
	}
yy237:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'E':
		goto yy245
	default:
		goto yy219
	}
yy238:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'T':
		goto yy246
	default:
		goto yy219
	}
yy239:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'M':
		goto yy247
	default:
		goto yy219
	}
yy240:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'E':
		goto yy249
	default:
		goto yy219
	}
yy241:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'E':
		goto yy250
	default:
		goto yy219
	}
yy242:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'A':
		goto yy251
	default:
		goto yy219
	}
yy243:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'R':
		goto yy252
	default:
		goto yy219
	}
yy244:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'E':
		goto yy253
	default:
		goto yy219
	}
yy245:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'T':
		goto yy254
	default:
		goto yy219
	}
yy246:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'I':
		goto yy255
	default:
		goto yy219
	}
yy247:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy218
	default:
		goto yy248
	}
yy248:
	{ return 5, yycursor }
yy249:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'R':
		goto yy256
	default:
		goto yy219
	}
yy250:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'C':
		goto yy257
	default:
		goto yy219
	}
yy251:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'T':
		goto yy258
	default:
		goto yy219
	}
yy252:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'E':
		goto yy259
	default:
		goto yy219
	}
yy253:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'E':
		goto yy261
	default:
		goto yy219
	}
yy254:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'E':
		goto yy262
	default:
		goto yy219
	}
yy255:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'N':
		goto yy264
	default:
		goto yy219
	}
yy256:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'T':
		goto yy265
	default:
		goto yy219
	}
yy257:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'T':
		goto yy267
	default:
		goto yy219
	}
yy258:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'E':
		goto yy269
	default:
		goto yy219
	}
yy259:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy218
	default:
		goto yy260
	}
yy260:
	{ return 6, yycursor }
yy261:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'N':
		goto yy271
	default:
		goto yy219
	}
yy262:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy218
	default:
		goto yy263
	}
yy263:
	{ return 4, yycursor }
yy264:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'C':
		goto yy273
	default:
		goto yy219
	}
yy265:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy218
	default:
		goto yy266
	}
yy266:
	{ return 2, yycursor }
yy267:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy218
	default:
		goto yy268
	}
yy268:
	{ return 1, yycursor }
yy269:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy218
	default:
		goto yy270
	}
yy270:
	{ return 3, yycursor }
yy271:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy218
	default:
		goto yy272
	}
yy272:
	{ return 7, yycursor }
yy273:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'T':
		goto yy274
	default:
		goto yy219
	}
yy274:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy218
	default:
		goto yy275
	}
yy275:
	{ return 8, yycursor }
}

}

func keywords_1(yyinput string) (int, int) {
	yycursor, yymarker := 0, 0
	_ = yymarker
	
{
	var yych byte
	yych = yyinput[yycursor]
	switch (yych) {
	case ' ':
		goto yy278
	case 'A':
		fallthrough
	case 'C':
		fallthrough
	case 'E':
		fallthrough
	case 'G','H':
		fallthrough
	case 'J','K','L','M','N','O','P','Q','R':
		fallthrough
	case 'T':
		fallthrough
	case 'V':
		fallthrough
	case 'X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy280
	case 'B':
		goto yy283
	case 'D':
		goto yy284
	case 'F':
		goto yy285
	case 'I':
		goto yy286
	case 'S':
		goto yy287
	case 'U':
		goto yy288
	case 'W':
		goto yy289
	default:
		goto yy277
	}
yy277:
	yycursor += 1
	{ return 0, yycursor }
yy278:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case ' ':
		goto yy278
	default:
		goto yy279
	}
yy279:
	{ return 10, yycursor }
yy280:
	yycursor += 1
	yych = yyinput[yycursor]
yy281:
	switch (yych) {
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy280
	default:
		goto yy282
	}
yy282:
	{ return 9, yycursor }
yy283:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'E':
		goto yy290
	default:
		goto yy281
	}
yy284:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'E':
		goto yy291
	case 'I':
		goto yy292
	default:
		goto yy281
	}
yy285:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'R':
		goto yy293
	default:
		goto yy281
	}
yy286:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'N':
		goto yy294
	default:
		goto yy281
	}
yy287:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'E':
		goto yy295
	default:
		goto yy281
	}
yy288:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'P':
		goto yy296
	default:
		goto yy281
	}
yy289:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'H':
		goto yy297
	default:
		goto yy281
	}
yy290:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'T':
		goto yy298
	default:
		goto yy281
	}
yy291:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'L':
		goto yy299
	default:
		goto yy281
	}
yy292:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'S':
		goto yy300
	default:
		goto yy281
	}
yy293:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'O':
		goto yy301
	default:
		goto yy281
	}
yy294:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'S':
		goto yy302
	default:
		goto yy281
	}
yy295:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'L':
		goto yy303
	default:
		goto yy281
	}
yy296:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'D':
		goto yy304
	default:
		goto yy281
	}
yy297:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'E':
		goto yy305
	default:
		goto yy281
	}
yy298:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'W':
		goto yy306
	default:
		goto yy281
	}
yy299:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'E':
		goto yy307
	default:
		goto yy281
	}
yy300:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'T':
		goto yy308
	default:
		goto yy281
	}
yy301:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'M':
		goto yy309
	default:
		goto yy281
	}
yy302:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'E':
		goto yy311
	default:
		goto yy281
	}
yy303:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'E':
		goto yy312
	default:
		goto yy281
	}
yy304:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'A':
		goto yy313
	default:
		goto yy281
	}
yy305:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'R':
		goto yy314
	default:
		goto yy281
	}
yy306:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'E':
		goto yy315
	default:
		goto yy281
	}
yy307:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'T':
		goto yy316
	default:
		goto yy281
	}
yy308:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'I':
		goto yy317
	default:
		goto yy281
	}
yy309:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy280
	default:
		goto yy310
	}
yy310:
	{ return 5, yycursor }
yy311:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'R':
		goto yy318
	default:
		goto yy281
	}
yy312:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'C':
		goto yy319
	default:
		goto yy281
	}
yy313:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'T':
		goto yy320
	default:
		goto yy281
	}
yy314:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'E':
		goto yy321
	default:
		goto yy281
	}
yy315:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'E':
		goto yy323
	default:
		goto yy281
	}
yy316:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'E':
		goto yy324
	default:
		goto yy281
	}
yy317:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'N':
		goto yy326
	default:
		goto yy281
	}
yy318:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'T':
		goto yy327
	default:
		goto yy281
	}
yy319:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'T':
		goto yy329
	default:
		goto yy281
	}
yy320:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'E':
		goto yy331
	default:
		goto yy281
	}
yy321:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy280
	default:
		goto yy322
	}
yy322:
	{ return 6, yycursor }
yy323:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'N':
		goto yy333
	default:
		goto yy281
	}
yy324:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy280
	default:
		goto yy325
	}
yy325:
	{ return 4, yycursor }
yy326:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'C':
		goto yy335
	default:
		goto yy281
	}
yy327:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy280
	default:
		goto yy328
	}
yy328:
	{ return 2, yycursor }
yy329:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy280
	default:
		goto yy330
	}
yy330:
	{ return 1, yycursor }
yy331:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy280
	default:
		goto yy332
	}
yy332:
	{ return 3, yycursor }
yy333:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy280
	default:
		goto yy334
	}
yy334:
	{ return 7, yycursor }
yy335:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'T':
		goto yy336
	default:
		goto yy281
	}
yy336:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy280
	default:
		goto yy337
	}
yy337:
	{ return 8, yycursor }
}

}

var keywords_words = []string{
	"\x53\x45\x4c\x45\x43\x54",
	"\x49\x4e\x53\x45\x52\x54",
	"\x55\x50\x44\x41\x54\x45",
	"\x44\x45\x4c\x45\x54\x45",
	"\x46\x52\x4f\x4d",
	"\x57\x48\x45\x52\x45",
	"\x42\x45\x54\x57\x45\x45\x4e",
	"\x44\x49\x53\x54\x49\x4e\x43\x54",
	"\x53\x45\x4c\x45\x43\x54\x45\x44",
	"\x44\x49\x53\x54\x49\x4e\x43\x54\x49\x4f\x4e",
	"\x46\x52\x4f\x4d\x41\x47\x45",
	"\x57\x48\x45\x52\x45\x41\x53",
}



func backtrack_0(yyinput string) (int, int) {
	yycursor, yymarker := 0, 0
	_ = yymarker
	
{
	var yych byte
	yyaccept := 0
	yych = yyinput[yycursor]
	switch (yych) {
	case 'a':
		goto yy341
	case 'b':
		goto yy342
	case 'q':
		goto yy343
	case 'x':
		goto yy344
	default:
		goto yy339
	}
yy339:
	yycursor += 1
yy340:
	{ return 0, yycursor }
yy341:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'b':
		goto yy345
	default:
		goto yy340
	}
yy342:
	yyaccept = 0
	yycursor += 1
	yymarker = yycursor
	yych = yyinput[yycursor]
	switch (yych) {
	case 'c':
		goto yy347
	default:
		goto yy340
	}
yy343:
	yyaccept = 0
	yycursor += 1
	yymarker = yycursor
	yych = yyinput[yycursor]
	switch (yych) {
	case '0','1','2','3','4','5','6','7','8','9':
		goto yy349
	default:
		goto yy340
	}
yy344:
	yyaccept = 0
	yycursor += 1
	yymarker = yycursor
	yych = yyinput[yycursor]
	switch (yych) {
	case 'y':
		goto yy350
	default:
		goto yy340
	}
yy345:
	yyaccept = 1
	yycursor += 1
	yymarker = yycursor
	yych = yyinput[yycursor]
	switch (yych) {
	case 'c':
		goto yy351
	default:
		goto yy346
	}
yy346:
	{ return 1, yycursor }
yy347:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'd':
		goto yy352
	default:
		goto yy348
	}
yy348:
	yycursor = yymarker
	switch (yyaccept) {
	case 0:
		goto yy340
	case 1:
		goto yy346
	case 2:
		goto yy356
	default:
		goto yy372
	}
yy349:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case '0','1','2','3','4','5','6','7','8','9':
		goto yy349
	case 'e':
		goto yy353
	default:
		goto yy348
	}
yy350:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'z':
		goto yy354
	default:
		goto yy348
	}
yy351:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'd':
		goto yy355
	case 'x':
		goto yy357
	default:
		goto yy348
	}
yy352:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'e':
		goto yy358
	default:
		goto yy348
	}
yy353:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'n':
		goto yy359
	default:
		goto yy348
	}
yy354:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'z':
		goto yy360
	default:
		goto yy348
	}
yy355:
	yyaccept = 2
	yycursor += 1
	yymarker = yycursor
	yych = yyinput[yycursor]
	switch (yych) {
	case 'e':
		goto yy361
	default:
		goto yy356
	}
yy356:
	{ return 2, yycursor }
yy357:
	yycursor += 1
	{ return 5, yycursor }
yy358:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'f':
		goto yy362
	default:
		goto yy348
	}
yy359:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'd':
		goto yy363
	default:
		goto yy348
	}
yy360:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'y':
		goto yy364
	default:
		goto yy348
	}
yy361:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'f':
		goto yy365
	default:
		goto yy348
	}
yy362:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'g':
		goto yy366
	default:
		goto yy348
	}
yy363:
	yycursor += 1
	{ return 8, yycursor }
yy364:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'x':
		goto yy367
	default:
		goto yy348
	}
yy365:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'g':
		goto yy368
	default:
		goto yy348
	}
yy366:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'h':
		goto yy369
	default:
		goto yy348
	}
yy367:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'y':
		goto yy370
	default:
		goto yy348
	}
yy368:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'h':
		goto yy371
	default:
		goto yy348
	}
yy369:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'i':
		goto yy373
	default:
		goto yy348
	}
yy370:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'z':
		goto yy374
	default:
		goto yy348
	}
yy371:
	yyaccept = 3
	yycursor += 1
	yymarker = yycursor
	yych = yyinput[yycursor]
	switch (yych) {
	case 'i':
		goto yy375
	default:
		goto yy372
	}
yy372:
	{ return 3, yycursor }
yy373:
	yycursor += 1
	{ return 6, yycursor }
yy374:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'z':
		goto yy376
	default:
		goto yy348
	}
yy375:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'j':
		goto yy377
	default:
		goto yy348
	}
yy376:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'y':
		goto yy378
	default:
		goto yy348
	}
yy377:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'k':
		goto yy379
	default:
		goto yy348
	}
yy378:
	yycursor += 1
	{ return 7, yycursor }
yy379:
	yycursor += 1
	{ return 4, yycursor }
}

}

func backtrack_1(yyinput string) (int, int) {
	yycursor, yymarker := 0, 0
	_ = yymarker
	
{
	var yych byte
	yyaccept := 0
	yych = yyinput[yycursor]
	switch (yych) {
	case 'a':
		goto yy383
	case 'b':
		goto yy384
	case 'q':
		goto yy385
	case 'x':
		goto yy386
	default:
		goto yy381
	}
yy381:
	yycursor += 1
yy382:
	{ return 0, yycursor }
yy383:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'b':
		goto yy387
	default:
		goto yy382
	}
yy384:
	yyaccept = 0
	yycursor += 1
	yymarker = yycursor
	yych = yyinput[yycursor]
	if (len(yyinput)-yycursor >= 4) {
		if (uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) == 0x66656463) {
			yycursor += 3
			goto yy404
		} else {
			switch (((((((uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) ^ 0x66656463) - 1) &^ (uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) ^ 0x66656463)) >> 7) & 0x0101010101010101) * 0x0101010101010101) >> 56) {
			case 1:
				goto yy389
			case 2:
				yycursor += 1
				goto yy394
			case 3:
				yycursor += 2
				goto yy400
			}
		}
	}
	switch (yych) {
	case 'c':
		goto yy389
	default:
		goto yy382
	}
yy385:
	yyaccept = 0
	yycursor += 1
	yymarker = yycursor
	yych = yyinput[yycursor]
	switch (yych) {
	case '0','1','2','3','4','5','6','7','8','9':
		goto yy391
	default:
		goto yy382
	}
yy386:
	yyaccept = 0
	yycursor += 1
	yymarker = yycursor
	yych = yyinput[yycursor]
	if (len(yyinput)-yycursor >= 8) {
		if (uint64(yyinput[yycursor:][7])<<(8*7) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) | uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][4])<<(8*4) | uint64(yyinput[yycursor:][5])<<(8*5) | uint64(yyinput[yycursor:][6])<<(8*6) == 0x7a7a7978797a7a79) {
			yycursor += 7
			goto yy418
		} else {
			switch (((((((uint64(yyinput[yycursor:][7])<<(8*7) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) | uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][4])<<(8*4) | uint64(yyinput[yycursor:][5])<<(8*5) | uint64(yyinput[yycursor:][6])<<(8*6) ^ 0x7a7a7978797a7a79) - 1) &^ (uint64(yyinput[yycursor:][7])<<(8*7) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) | uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][4])<<(8*4) | uint64(yyinput[yycursor:][5])<<(8*5) | uint64(yyinput[yycursor:][6])<<(8*6) ^ 0x7a7a7978797a7a79)) >> 7) & 0x0101010101010101) * 0x0101010101010101) >> 56) {
			case 1:
				goto yy392
			case 2:
				yycursor += 1
				goto yy396
			case 3:
				yycursor += 2
				goto yy402
			case 4:
				yycursor += 3
				goto yy406
			case 5:
				yycursor += 4
				goto yy409
			case 6:
				yycursor += 5
				goto yy412
			case 7:
				yycursor += 6
				goto yy416
			}
		}
	}
	switch (yych) {
	case 'y':
		goto yy392
	default:
		goto yy382
	}
yy387:
	yyaccept = 1
	yycursor += 1
	yymarker = yycursor
	yych = yyinput[yycursor]
	switch (yych) {
	case 'c':
		goto yy393
	default:
		goto yy388
	}
yy388:
	{ return 1, yycursor }
yy389:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'd':
		goto yy394
	default:
		goto yy390
	}
yy390:
	yycursor = yymarker
	switch (yyaccept) {
	case 0:
		goto yy382
	case 1:
		goto yy388
	case 2:
		goto yy398
	default:
		goto yy414
	}
yy391:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case '0','1','2','3','4','5','6','7','8','9':
		goto yy391
	case 'e':
		goto yy395
	default:
		goto yy390
	}
yy392:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'z':
		goto yy396
	default:
		goto yy390
	}
yy393:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'd':
		goto yy397
	case 'x':
		goto yy399
	default:
		goto yy390
	}
yy394:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'e':
		goto yy400
	default:
		goto yy390
	}
yy395:
	yycursor += 1
	yych = yyinput[yycursor]
	if (len(yyinput)-yycursor >= 2) {
		if (uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][0]) == 0x646e) {
			yycursor += 1
			goto yy405
		} else {
			switch (((((((uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][0]) ^ 0x646e) - 1) &^ (uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][0]) ^ 0x646e)) >> 7) & 0x0101010101010101) * 0x0101010101010101) >> 56) {
			case 1:
				goto yy401
			}
		}
	}
	switch (yych) {
	case 'n':
		goto yy401
	default:
		goto yy390
	}
yy396:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'z':
		goto yy402
	default:
		goto yy390
	}
yy397:
	yyaccept = 2
	yycursor += 1
	yymarker = yycursor
	yych = yyinput[yycursor]
	if (len(yyinput)-yycursor >= 4) {
		if (uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) == 0x68676665) {
			yycursor += 3
			goto yy413
		} else {
			switch (((((((uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) ^ 0x68676665) - 1) &^ (uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) ^ 0x68676665)) >> 7) & 0x0101010101010101) * 0x0101010101010101) >> 56) {
			case 1:
				goto yy403
			case 2:
				yycursor += 1
				goto yy407
			case 3:
				yycursor += 2
				goto yy410
			}
		}
	}
	switch (yych) {
	case 'e':
		goto yy403
	default:
		goto yy398
	}
yy398:
	{ return 2, yycursor }
yy399:
	yycursor += 1
	{ return 5, yycursor }
yy400:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'f':
		goto yy404
	default:
		goto yy390
	}
yy401:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'd':
		goto yy405
	default:
		goto yy390
	}
yy402:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'y':
		goto yy406
	default:
		goto yy390
	}
yy403:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'f':
		goto yy407
	default:
		goto yy390
	}
yy404:
	yycursor += 1
	yych = yyinput[yycursor]
	if (len(yyinput)-yycursor >= 2) {
		if (uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][0]) == 0x6867) {
			yycursor += 1
			goto yy411
		} else {
			switch (((((((uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][0]) ^ 0x6867) - 1) &^ (uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][0]) ^ 0x6867)) >> 7) & 0x0101010101010101) * 0x0101010101010101) >> 56) {
			case 1:
				goto yy408
			}
		}
	}
	switch (yych) {
	case 'g':
		goto yy408
	default:
		goto yy390
	}
yy405:
	yycursor += 1
	{ return 8, yycursor }
yy406:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'x':
		goto yy409
	default:
		goto yy390
	}
yy407:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'g':
		goto yy410
	default:
		goto yy390
	}
yy408:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'h':
		goto yy411
	default:
		goto yy390
	}
yy409:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'y':
		goto yy412
	default:
		goto yy390
	}
yy410:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'h':
		goto yy413
	default:
		goto yy390
	}
yy411:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'i':
		goto yy415
	default:
		goto yy390
	}
yy412:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'z':
		goto yy416
	default:
		goto yy390
	}
yy413:
	yyaccept = 3
	yycursor += 1
	yymarker = yycursor
	yych = yyinput[yycursor]
	if (len(yyinput)-yycursor >= 2) {
		if (uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][0]) == 0x6a69) {
			yycursor += 1
			goto yy419
		} else {
			switch (((((((uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][0]) ^ 0x6a69) - 1) &^ (uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][0]) ^ 0x6a69)) >> 7) & 0x0101010101010101) * 0x0101010101010101) >> 56) {
			case 1:
				goto yy417
			}
		}
	}
	switch (yych) {
	case 'i':
		goto yy417
	default:
		goto yy414
	}
yy414:
	{ return 3, yycursor }
yy415:
	yycursor += 1
	{ return 6, yycursor }
yy416:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'z':
		goto yy418
	default:
		goto yy390
	}
yy417:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'j':
		goto yy419
	default:
		goto yy390
	}
yy418:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'y':
		goto yy420
	default:
		goto yy390
	}
yy419:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'k':
		goto yy421
	default:
		goto yy390
	}
yy420:
	yycursor += 1
	{ return 7, yycursor }
yy421:
	yycursor += 1
	{ return 4, yycursor }
}

}

var backtrack_words = []string{
	"\x61\x62",
	"\x61\x62\x63\x64",
	"\x61\x62\x63\x64\x65\x66\x67\x68",
	"\x61\x62\x63\x64\x65\x66\x67\x68\x69\x6a\x6b",
	"\x61\x62\x63\x78",
	"\x62\x63\x64\x65\x66\x67\x68\x69",
	"\x78\x79\x7a\x7a\x79\x78\x79\x7a\x7a\x79",
	"\x71\x31\x32\x33\x65\x6e\x64",
	"\x61\x62\x63\x64\x65\x66\x67\x68\x69\x6a",
	"\x78\x79\x7a\x7a\x79\x78\x79\x7a\x7a",
}



func binary_0(yyinput string) (int, int) {
	yycursor, yymarker := 0, 0
	_ = yymarker
	
{
	var yych byte
	yych = yyinput[yycursor]
	switch (yych) {
	case 0x00,0x01,0x02,0x03,0x04,0x05,0x06,0x07,0x08,'\t','\n','\v','\f','\r',0x0E,0x0F,0x10,0x11,0x12,0x13,0x14,0x15,0x16,0x17,0x18,0x19,0x1A,0x1B,0x1C,0x1D,0x1E,0x1F,' ','!','"','#','$':
		fallthrough
	case '&','\'','(',')','*','+',',','-','.','/','0','1','2','3','4','5','6','7','8','9',':',';','<','=','>','?','@','A','B','C','D','E','F':
		fallthrough
	case 'H','I','J','K','L','M','N','O':
		fallthrough
	case 'Q','R','S','T','U','V','W','X','Y','Z','[','\\',']','^','_','`','a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z','{','|','}','~',0x7F,0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88:
		fallthrough
	case 0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF,0xC0,0xC1,0xC2,0xC3,0xC4,0xC5,0xC6,0xC7,0xC8,0xC9,0xCA,0xCB,0xCC,0xCD,0xCE,0xCF,0xD0,0xD1,0xD2,0xD3,0xD4,0xD5,0xD6,0xD7,0xD8,0xD9,0xDA,0xDB,0xDC,0xDD,0xDE,0xDF,0xE0,0xE1,0xE2,0xE3,0xE4,0xE5,0xE6,0xE7,0xE8,0xE9,0xEA,0xEB,0xEC,0xED,0xEE:
		fallthrough
	case 0xF0,0xF1,0xF2,0xF3,0xF4,0xF5,0xF6,0xF7,0xF8,0xF9,0xFA,0xFB,0xFC,0xFD,0xFE:
		goto yy423
	case '%':
		goto yy425
	case 'G':
		goto yy426
	case 'P':
		goto yy427
	case 0x89:
		goto yy428
	case 0xEF:
		goto yy429
	default:
		goto yy430
	}
yy423:
	yycursor += 1
yy424:
	{ return 0, yycursor }
yy425:
	yycursor += 1
	yymarker = yycursor
	yych = yyinput[yycursor]
	switch (yych) {
	case 'P':
		goto yy431
	default:
		goto yy424
	}
yy426:
	yycursor += 1
	yymarker = yycursor
	yych = yyinput[yycursor]
	switch (yych) {
	case 'I':
		goto yy433
	default:
		goto yy424
	}
yy427:
	yycursor += 1
	yymarker = yycursor
	yych = yyinput[yycursor]
	switch (yych) {
	case 'K':
		goto yy434
	default:
		goto yy424
	}
yy428:
	yycursor += 1
	yymarker = yycursor
	yych = yyinput[yycursor]
	switch (yych) {
	case 'P':
		goto yy435
	default:
		goto yy424
	}
yy429:
	yycursor += 1
	yymarker = yycursor
	yych = yyinput[yycursor]
	switch (yych) {
	case 0xBB:
		goto yy436
	default:
		goto yy424
	}
yy430:
	yycursor += 1
	yymarker = yycursor
	yych = yyinput[yycursor]
	switch (yych) {
	case 0xD8:
		goto yy437
	default:
		goto yy424
	}
yy431:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'D':
		goto yy438
	default:
		goto yy432
	}
yy432:
	yycursor = yymarker
	goto yy424
yy433:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'F':
		goto yy439
	default:
		goto yy432
	}
yy434:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 0x03:
		goto yy440
	default:
		goto yy432
	}
yy435:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'N':
		goto yy441
	default:
		goto yy432
	}
yy436:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 0xBF:
		goto yy442
	default:
		goto yy432
	}
yy437:
	yycursor += 1
	yych = yyinput[yycursor]
	if (yych <= 0xFE) {
		goto yy432
	}
	goto yy443
yy438:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'F':
		goto yy444
	default:
		goto yy432
	}
yy439:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case '8':
		goto yy445
	default:
		goto yy432
	}
yy440:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 0x04:
		goto yy446
	default:
		goto yy432
	}
yy441:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'G':
		goto yy447
	default:
		goto yy432
	}
yy442:
	yycursor += 1
	{ return 3, yycursor }
yy443:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 0xE0:
		goto yy448
	default:
		goto yy432
	}
yy444:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case '-':
		goto yy449
	default:
		goto yy432
	}
yy445:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case '9':
		goto yy450
	default:
		goto yy432
	}
yy446:
	yycursor += 1
	{ return 4, yycursor }
yy447:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case '\r':
		goto yy451
	default:
		goto yy432
	}
yy448:
	yycursor += 1
	{ return 6, yycursor }
yy449:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case '1':
		goto yy452
	default:
		goto yy432
	}
yy450:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'a':
		goto yy453
	default:
		goto yy432
	}
yy451:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case '\n':
		goto yy454
	default:
		goto yy432
	}
yy452:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case '.':
		goto yy455
	default:
		goto yy432
	}
yy453:
	yycursor += 1
	{ return 2, yycursor }
yy454:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 0x1A:
		goto yy456
	default:
		goto yy432
	}
yy455:
	yycursor += 1
	{ return 5, yycursor }
yy456:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case '\n':
		goto yy457
	default:
		goto yy432
	}
yy457:
	yycursor += 1
	{ return 1, yycursor }
}

}

func binary_1(yyinput string) (int, int) {
	yycursor, yymarker := 0, 0
	_ = yymarker
	
{
	var yych byte
	yych = yyinput[yycursor]
	switch (yych) {
	case 0x00,0x01,0x02,0x03,0x04,0x05,0x06,0x07,0x08,'\t','\n','\v','\f','\r',0x0E,0x0F,0x10,0x11,0x12,0x13,0x14,0x15,0x16,0x17,0x18,0x19,0x1A,0x1B,0x1C,0x1D,0x1E,0x1F,' ','!','"','#','$':
		fallthrough
	case '&','\'','(',')','*','+',',','-','.','/','0','1','2','3','4','5','6','7','8','9',':',';','<','=','>','?','@','A','B','C','D','E','F':
		fallthrough
	case 'H','I','J','K','L','M','N','O':
		fallthrough
	case 'Q','R','S','T','U','V','W','X','Y','Z','[','\\',']','^','_','`','a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z','{','|','}','~',0x7F,0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88:
		fallthrough
	case 0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF,0xC0,0xC1,0xC2,0xC3,0xC4,0xC5,0xC6,0xC7,0xC8,0xC9,0xCA,0xCB,0xCC,0xCD,0xCE,0xCF,0xD0,0xD1,0xD2,0xD3,0xD4,0xD5,0xD6,0xD7,0xD8,0xD9,0xDA,0xDB,0xDC,0xDD,0xDE,0xDF,0xE0,0xE1,0xE2,0xE3,0xE4,0xE5,0xE6,0xE7,0xE8,0xE9,0xEA,0xEB,0xEC,0xED,0xEE:
		fallthrough
	case 0xF0,0xF1,0xF2,0xF3,0xF4,0xF5,0xF6,0xF7,0xF8,0xF9,0xFA,0xFB,0xFC,0xFD,0xFE:
		goto yy459
	case '%':
		goto yy461
	case 'G':
		goto yy462
	case 'P':
		goto yy463
	case 0x89:
		goto yy464
	case 0xEF:
		goto yy465
	default:
		goto yy466
	}
yy459:
	yycursor += 1
yy460:
	{ return 0, yycursor }
yy461:
	yycursor += 1
	yymarker = yycursor
	yych = yyinput[yycursor]
	if (len(yyinput)-yycursor >= 4) {
		if (uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) == 0x2d464450) {
			yycursor += 3
			goto yy485
		} else {
			switch (((((((uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) ^ 0x2d464450) - 1) &^ (uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) ^ 0x2d464450)) >> 7) & 0x0101010101010101) * 0x0101010101010101) >> 56) {
			case 1:
				goto yy467
			case 2:
				yycursor += 1
				goto yy474
			case 3:
				yycursor += 2
				goto yy480
			}
		}
	}
	switch (yych) {
	case 'P':
		goto yy467
	default:
		goto yy460
	}
yy462:
	yycursor += 1
	yymarker = yycursor
	yych = yyinput[yycursor]
	if (len(yyinput)-yycursor >= 4) {
		if (uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) == 0x39384649) {
			yycursor += 3
			goto yy486
		} else {
			switch (((((((uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) ^ 0x39384649) - 1) &^ (uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) ^ 0x39384649)) >> 7) & 0x0101010101010101) * 0x0101010101010101) >> 56) {
			case 1:
				goto yy469
			case 2:
				yycursor += 1
				goto yy475
			case 3:
				yycursor += 2
				goto yy481
			}
		}
	}
	switch (yych) {
	case 'I':
		goto yy469
	default:
		goto yy460
	}
yy463:
	yycursor += 1
	yymarker = yycursor
	yych = yyinput[yycursor]
	if (len(yyinput)-yycursor >= 2) {
		if (uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][0]) == 0x34b) {
			yycursor += 1
			goto yy476
		} else {
			switch (((((((uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][0]) ^ 0x34b) - 1) &^ (uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][0]) ^ 0x34b)) >> 7) & 0x0101010101010101) * 0x0101010101010101) >> 56) {
			case 1:
				goto yy470
			}
		}
	}
	switch (yych) {
	case 'K':
		goto yy470
	default:
		goto yy460
	}
yy464:
	yycursor += 1
	yymarker = yycursor
	yych = yyinput[yycursor]
	if (len(yyinput)-yycursor >= 4) {
		if (uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) == 0xd474e50) {
			yycursor += 3
			goto yy487
		} else {
			switch (((((((uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) ^ 0xd474e50) - 1) &^ (uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) ^ 0xd474e50)) >> 7) & 0x0101010101010101) * 0x0101010101010101) >> 56) {
			case 1:
				goto yy471
			case 2:
				yycursor += 1
				goto yy477
			case 3:
				yycursor += 2
				goto yy483
			}
		}
	}
	switch (yych) {
	case 'P':
		goto yy471
	default:
		goto yy460
	}
yy465:
	yycursor += 1
	yymarker = yycursor
	yych = yyinput[yycursor]
	if (len(yyinput)-yycursor >= 2) {
		if (uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][0]) == 0xbfbb) {
			yycursor += 1
			goto yy478
		} else {
			switch (((((((uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][0]) ^ 0xbfbb) - 1) &^ (uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][0]) ^ 0xbfbb)) >> 7) & 0x0101010101010101) * 0x0101010101010101) >> 56) {
			case 1:
				goto yy472
			}
		}
	}
	switch (yych) {
	case 0xBB:
		goto yy472
	default:
		goto yy460
	}
yy466:
	yycursor += 1
	yymarker = yycursor
	yych = yyinput[yycursor]
	if (len(yyinput)-yycursor >= 2) {
		if (uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][0]) == 0xffd8) {
			yycursor += 1
			goto yy479
		} else {
			switch (((((((uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][0]) ^ 0xffd8) - 1) &^ (uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][0]) ^ 0xffd8)) >> 7) & 0x0101010101010101) * 0x0101010101010101) >> 56) {
			case 1:
				goto yy473
			}
		}
	}
	switch (yych) {
	case 0xD8:
		goto yy473
	default:
		goto yy460
	}
yy467:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'D':
		goto yy474
	default:
		goto yy468
	}
yy468:
	yycursor = yymarker
	goto yy460
yy469:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'F':
		goto yy475
	default:
		goto yy468
	}
yy470:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 0x03:
		goto yy476
	default:
		goto yy468
	}
yy471:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'N':
		goto yy477
	default:
		goto yy468
	}
yy472:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 0xBF:
		goto yy478
	default:
		goto yy468
	}
yy473:
	yycursor += 1
	yych = yyinput[yycursor]
	if (yych <= 0xFE) {
		goto yy468
	}
	goto yy479
yy474:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'F':
		goto yy480
	default:
		goto yy468
	}
yy475:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case '8':
		goto yy481
	default:
		goto yy468
	}
yy476:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 0x04:
		goto yy482
	default:
		goto yy468
	}
yy477:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'G':
		goto yy483
	default:
		goto yy468
	}
yy478:
	yycursor += 1
	{ return 3, yycursor }
yy479:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 0xE0:
		goto yy484
	default:
		goto yy468
	}
yy480:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case '-':
		goto yy485
	default:
		goto yy468
	}
yy481:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case '9':
		goto yy486
	default:
		goto yy468
	}
yy482:
	yycursor += 1
	{ return 4, yycursor }
yy483:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case '\r':
		goto yy487
	default:
		goto yy468
	}
yy484:
	yycursor += 1
	{ return 6, yycursor }
yy485:
	yycursor += 1
	yych = yyinput[yycursor]
	if (len(yyinput)-yycursor >= 2) {
		if (uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][0]) == 0x2e31) {
			yycursor += 1
			goto yy491
		} else {
			switch (((((((uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][0]) ^ 0x2e31) - 1) &^ (uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][0]) ^ 0x2e31)) >> 7) & 0x0101010101010101) * 0x0101010101010101) >> 56) {
			case 1:
				goto yy488
			}
		}
	}
	switch (yych) {
	case '1':
		goto yy488
	default:
		goto yy468
	}
yy486:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'a':
		goto yy489
	default:
		goto yy468
	}
yy487:
	yycursor += 1
	yych = yyinput[yycursor]
	if (len(yyinput)-yycursor >= 2) {
		if (uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][0]) == 0x1a0a) {
			yycursor += 1
			goto yy492
		} else {
			switch (((((((uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][0]) ^ 0x1a0a) - 1) &^ (uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][0]) ^ 0x1a0a)) >> 7) & 0x0101010101010101) * 0x0101010101010101) >> 56) {
			case 1:
				goto yy490
			}
		}
	}
	switch (yych) {
	case '\n':
		goto yy490
	default:
		goto yy468
	}
yy488:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case '.':
		goto yy491
	default:
		goto yy468
	}
yy489:
	yycursor += 1
	{ return 2, yycursor }
yy490:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 0x1A:
		goto yy492
	default:
		goto yy468
	}
yy491:
	yycursor += 1
	{ return 5, yycursor }
yy492:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case '\n':
		goto yy493
	default:
		goto yy468
	}
yy493:
	yycursor += 1
	{ return 1, yycursor }
}

}

var binary_words = []string{
	"\x89\x50\x4e\x47\x0d\x0a\x1a\x0a",
	"\x47\x49\x46\x38\x39\x61",
	"\x47\x49\x46\x38\x37\x61",
	"\xef\xbb\xbf",
	"\x50\x4b\x03\x04",
	"\x25\x50\x44\x46\x2d\x31\x2e",
	"\xff\xd8\xff\xe0",
	"\xff\xd8\xff\xe1",
}



func anchored_0(yyinput string) (int, int) {
	yycursor, yymarker := 0, 0
	_ = yymarker
	
{
	var yych byte
	yych = yyinput[yycursor]
	switch (yych) {
	case 0x00,0x01:
		goto yy495
	case 'G':
		goto yy497
	default:
		goto yy496
	}
yy495:
	yycursor += 1
	{ return 3, yycursor }
yy496:
	yycursor += 1
	yych = yyinput[yycursor]
	if (yych <= 0x01) {
		goto yy498
	}
	goto yy499
yy497:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 0x00,0x01:
		goto yy498
	case 'I':
		goto yy501
	default:
		goto yy499
	}
yy498:
	yycursor += 1
	{ return 3, yycursor }
yy499:
	yycursor += 1
yy500:
	{ return 0, yycursor }
yy501:
	yycursor += 1
	yymarker = yycursor
	yych = yyinput[yycursor]
	switch (yych) {
	case 'F':
		goto yy502
	default:
		goto yy500
	}
yy502:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case '8':
		goto yy504
	default:
		goto yy503
	}
yy503:
	yycursor = yymarker
	goto yy500
yy504:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case '7':
		goto yy505
	case '9':
		goto yy506
	default:
		goto yy503
	}
yy505:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'a':
		goto yy507
	default:
		goto yy503
	}
yy506:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'a':
		goto yy508
	default:
		goto yy503
	}
yy507:
	yycursor += 1
	{ return 2, yycursor }
yy508:
	yycursor += 1
	{ return 1, yycursor }
}

}

func anchored_1(yyinput string) (int, int) {
	yycursor, yymarker := 0, 0
	_ = yymarker
	
{
	var yych byte
	yych = yyinput[yycursor]
	if (len(yyinput)-yycursor >= 2) {
		if (uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][0]) == 0x4947) {
			yycursor += 1
			goto yy516
		} else {
			switch (((((((uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][0]) ^ 0x4947) - 1) &^ (uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][0]) ^ 0x4947)) >> 7) & 0x0101010101010101) * 0x0101010101010101) >> 56) {
			case 1:
				goto yy512
			}
		}
	}
	switch (yych) {
	case 0x00,0x01:
		goto yy510
	case 'G':
		goto yy512
	default:
		goto yy511
	}
yy510:
	yycursor += 1
	{ return 3, yycursor }
yy511:
	yycursor += 1
	yych = yyinput[yycursor]
	if (yych <= 0x01) {
		goto yy513
	}
	goto yy514
yy512:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 0x00,0x01:
		goto yy513
	case 'I':
		goto yy516
	default:
		goto yy514
	}
yy513:
	yycursor += 1
	{ return 3, yycursor }
yy514:
	yycursor += 1
yy515:
	{ return 0, yycursor }
yy516:
	yycursor += 1
	yymarker = yycursor
	yych = yyinput[yycursor]
	if (len(yyinput)-yycursor >= 2) {
		if (uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][0]) == 0x3846) {
			yycursor += 1
			goto yy519
		} else {
			switch (((((((uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][0]) ^ 0x3846) - 1) &^ (uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][0]) ^ 0x3846)) >> 7) & 0x0101010101010101) * 0x0101010101010101) >> 56) {
			case 1:
				goto yy517
			}
		}
	}
	switch (yych) {
	case 'F':
		goto yy517
	default:
		goto yy515
	}
yy517:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case '8':
		goto yy519
	default:
		goto yy518
	}
yy518:
	yycursor = yymarker
	goto yy515
yy519:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case '7':
		goto yy520
	case '9':
		goto yy521
	default:
		goto yy518
	}
yy520:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'a':
		goto yy522
	default:
		goto yy518
	}
yy521:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'a':
		goto yy523
	default:
		goto yy518
	}
yy522:
	yycursor += 1
	{ return 2, yycursor }
yy523:
	yycursor += 1
	{ return 1, yycursor }
}

}

var anchored_words = []string{
	"\x47\x49\x46\x38\x39\x61",
	"\x47\x49\x46\x38\x37\x61",
	"\x47\x49\x46\x38",
	"\x47\x49",
	"\x47",
	"\x47\x4a",
}

var failures, checks int

func check1(f, g func(string) (int, int), in string) {
	r1, c1 := f(in)
	r2, c2 := g(in)
	checks++
	if r1 != r2 || c1 != c2 {
		fmt.Fprintf(os.Stderr, "mismatch on %q: rule %d/%d, cursor %d/%d\n", in, r1, r2, c1, c2)
		failures++
	}
}

func check(f, g func(string) (int, int), in string) {
	check1(f, g, in+"\x00")
	pad := in
	for len(pad) < 16 {
		pad += "a"
	}
	check1(f, g, in+"\x00"+pad[:16])
}

func checkSet(f, g func(string) (int, int), ws []string) {
	alt := []byte{0x00, 0x01, 'a', 'z', 'A', 'Z', ':', '-', ' ', '_', '0', 0x7f, 0x80, 0xfe, 0xff}
	for _, w := range ws {
		for i := 0; i <= len(w); i++ {
			check(f, g, w[:i])
			for _, a := range alt {
				check(f, g, w[:i]+string([]byte{a}))
			}
			if i < len(w) {
				check(f, g, w[:i]+string([]byte{w[i] + 1}))
				check(f, g, w[:i]+string([]byte{w[i] - 1}))
			}
		}
		for _, v := range ws {
			check(f, g, w+v)
		}
	}
}

func main() {
	checkSet(headers_0, headers_1, headers_words)
	checkSet(keywords_0, keywords_1, keywords_words)
	checkSet(backtrack_0, backtrack_1, backtrack_words)
	checkSet(binary_0, binary_1, binary_words)
	checkSet(anchored_0, anchored_1, anchored_words)
	if failures > 0 {
		panic(fmt.Sprintf("%d of %d checks failed", failures, checks))
	}
}
