/* Generated by re2c */
// re2c $INPUT -o $OUTPUT -i
// Parity of --vectorize-linear with the ordinary DFA with YYFILL: a stream of tokens is lexed
// through a small buffer refilled from memory, for many buffer sizes, so that tokens are split at
// every position by refills. The buffer is allocated with its exact size (BUFSIZE + YYMAXFILL) and
// padded with YYMAXFILL zeroes at the end of input, as YYFILL requires; an out-of-bounds read is
// detected by AddressSanitizer.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define YYMAXFILL 18


typedef struct {
    const unsigned char* src;
    size_t srclen, srcpos, bufsize;
    unsigned char *buf, *lim, *cur, *tok, *mar;
    int eof;
} Input;

static int fill(Input* in, size_t need) {
    if (in->eof) return 1;
    const size_t shift = (size_t)(in->tok - in->buf);
    const size_t used = (size_t)(in->lim - in->tok);
    if (shift < need) return 2;
    memmove(in->buf, in->tok, used);
    in->lim -= shift;
    in->cur -= shift;
    in->tok -= shift;
    in->mar -= shift;
    size_t n = in->bufsize - used;
    if (n > in->srclen - in->srcpos) n = in->srclen - in->srcpos;
    memcpy(in->lim, in->src + in->srcpos, n);
    in->srcpos += n;
    in->lim += n;
    if (in->lim < in->buf + in->bufsize) {
        in->eof = 1;
        memset(in->lim, 0, YYMAXFILL);
        in->lim += YYMAXFILL;
    }
    return 0;
}

// Returns the rule number, 100 at the end of input, -1 on error; `*len` is the token length.
typedef int (*lex_t)(Input*, size_t*);
struct word { const char* str; size_t len; };



static int headers_0(Input* in, size_t* len) {
    in->tok = in->cur;
    
{
	unsigned char yych;
	if ((in->lim - in->cur) < 18) if (fill(in, 18) != 0) return -1;
	yych = *in->cur;
	switch (yych) {
		case 0x00: goto yy1;
		case '-':
		case 'B':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy4;
		case 'A': goto yy5;
		case 'C': goto yy6;
		case 'T': goto yy7;
		case 'U': goto yy8;
		default: goto yy2;
	}
yy1:
	++in->cur;
	{ *len = 0; return in->tok == in->lim - YYMAXFILL ? 100 : -1; }
yy2:
	++in->cur;
yy3:
	{ *len = (size_t)(in->cur - in->tok); return 0; }
yy4:
	yych = *(in->mar = ++in->cur);
	switch (yych) {
		case '-':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy9;
		case ':': goto yy12;
		default: goto yy3;
	}
yy5:
	yych = *(in->mar = ++in->cur);
	switch (yych) {
		case '-':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy9;
		case ':': goto yy12;
		case 'c': goto yy13;
		case 'u': goto yy14;
		default: goto yy3;
	}
yy6:
	yych = *(in->mar = ++in->cur);
	switch (yych) {
		case '-':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy9;
		case ':': goto yy12;
		case 'a': goto yy15;
		case 'o': goto yy16;
		default: goto yy3;
	}
yy7:
	yych = *(in->mar = ++in->cur);
	switch (yych) {
		case '-':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy9;
		case ':': goto yy12;
		case 'r': goto yy17;
		default: goto yy3;
	}
yy8:
	yych = *(in->mar = ++in->cur);
	switch (yych) {
		case '-':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy9;
		case ':': goto yy12;
		case 's': goto yy18;
		default: goto yy3;
	}
yy9:
	++in->cur;
	if (in->lim <= in->cur) if (fill(in, 1) != 0) return -1;
	yych = *in->cur;
yy10:
	switch (yych) {
		case '-':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy9;
		case ':': goto yy12;
		default: goto yy11;
	}
yy11:
	in->cur = in->mar;
	goto yy3;
yy12:
	++in->cur;
	{ *len = (size_t)(in->cur - in->tok); return 9; }
yy13:
	yych = *++in->cur;
	switch (yych) {
		case 'c': goto yy19;
		default: goto yy10;
	}
yy14:
	yych = *++in->cur;
	switch (yych) {
		case 't': goto yy20;
		default: goto yy10;
	}
yy15:
	yych = *++in->cur;
	switch (yych) {
		case 'c': goto yy21;
		default: goto yy10;
	}
yy16:
	yych = *++in->cur;
	switch (yych) {
		case 'n': goto yy22;
		default: goto yy10;
	}
yy17:
	yych = *++in->cur;
	switch (yych) {
		case 'a': goto yy23;
		default: goto yy10;
	}
yy18:
	yych = *++in->cur;
	switch (yych) {
		case 'e': goto yy24;
		default: goto yy10;
	}
yy19:
	yych = *++in->cur;
	switch (yych) {
		case 'e': goto yy25;
		default: goto yy10;
	}
yy20:
	yych = *++in->cur;
	switch (yych) {
		case 'h': goto yy26;
		default: goto yy10;
	}
yy21:
	yych = *++in->cur;
	switch (yych) {
		case 'h': goto yy27;
		default: goto yy10;
	}
yy22:
	yych = *++in->cur;
	switch (yych) {
		case 'n': goto yy28;
		case 't': goto yy29;
		default: goto yy10;
	}
yy23:
	yych = *++in->cur;
	switch (yych) {
		case 'n': goto yy30;
		default: goto yy10;
	}
yy24:
	yych = *++in->cur;
	switch (yych) {
		case 'r': goto yy31;
		default: goto yy10;
	}
yy25:
	yych = *++in->cur;
	switch (yych) {
		case 'p': goto yy32;
		default: goto yy10;
	}
yy26:
	yych = *++in->cur;
	switch (yych) {
		case 'o': goto yy33;
		default: goto yy10;
	}
yy27:
	yych = *++in->cur;
	switch (yych) {
		case 'e': goto yy34;
		default: goto yy10;
	}
yy28:
	yych = *++in->cur;
	switch (yych) {
		case 'e': goto yy35;
		default: goto yy10;
	}
yy29:
	yych = *++in->cur;
	switch (yych) {
		case 'e': goto yy36;
		default: goto yy10;
	}
yy30:
	yych = *++in->cur;
	switch (yych) {
		case 's': goto yy37;
		default: goto yy10;
	}
yy31:
	yych = *++in->cur;
	switch (yych) {
		case '-': goto yy38;
		default: goto yy10;
	}
yy32:
	yych = *++in->cur;
	switch (yych) {
		case 't': goto yy39;
		default: goto yy10;
	}
yy33:
	yych = *++in->cur;
	switch (yych) {
		case 'r': goto yy40;
		default: goto yy10;
	}
yy34:
	yych = *++in->cur;
	switch (yych) {
		case '-': goto yy41;
		default: goto yy10;
	}
yy35:
	yych = *++in->cur;
	switch (yych) {
		case 'c': goto yy42;
		default: goto yy10;
	}
yy36:
	yych = *++in->cur;
	switch (yych) {
		case 'n': goto yy43;
		default: goto yy10;
	}
yy37:
	yych = *++in->cur;
	switch (yych) {
		case 'f': goto yy44;
		default: goto yy10;
	}
yy38:
	yych = *++in->cur;
	switch (yych) {
		case 'A': goto yy45;
		default: goto yy10;
	}
yy39:
	yych = *++in->cur;
	switch (yych) {
		case '-': goto yy46;
		default: goto yy10;
	}
yy40:
	yych = *++in->cur;
	switch (yych) {
		case 'i': goto yy47;
		default: goto yy10;
	}
yy41:
	yych = *++in->cur;
	switch (yych) {
		case 'C': goto yy48;
		default: goto yy10;
	}
yy42:
	yych = *++in->cur;
	switch (yych) {
		case 't': goto yy49;
		default: goto yy10;
	}
yy43:
	yych = *++in->cur;
	switch (yych) {
		case 't': goto yy50;
		default: goto yy10;
	}
yy44:
	yych = *++in->cur;
	switch (yych) {
		case 'e': goto yy51;
		default: goto yy10;
	}
yy45:
	yych = *++in->cur;
	switch (yych) {
		case 'g': goto yy52;
		default: goto yy10;
	}
yy46:
	yych = *++in->cur;
	switch (yych) {
		case 'E': goto yy53;
		default: goto yy10;
	}
yy47:
	yych = *++in->cur;
	switch (yych) {
		case 'z': goto yy54;
		default: goto yy10;
	}
yy48:
	yych = *++in->cur;
	switch (yych) {
		case 'o': goto yy55;
		default: goto yy10;
	}
yy49:
	yych = *++in->cur;
	switch (yych) {
		case 'i': goto yy56;
		default: goto yy10;
	}
yy50:
	yych = *++in->cur;
	switch (yych) {
		case '-': goto yy57;
		default: goto yy10;
	}
yy51:
	yych = *++in->cur;
	switch (yych) {
		case 'r': goto yy58;
		default: goto yy10;
	}
yy52:
	yych = *++in->cur;
	switch (yych) {
		case 'e': goto yy59;
		default: goto yy10;
	}
yy53:
	yych = *++in->cur;
	switch (yych) {
		case 'n': goto yy60;
		default: goto yy10;
	}
yy54:
	yych = *++in->cur;
	switch (yych) {
		case 'a': goto yy61;
		default: goto yy10;
	}
yy55:
	yych = *++in->cur;
	switch (yych) {
		case 'n': goto yy62;
		default: goto yy10;
	}
yy56:
	yych = *++in->cur;
	switch (yych) {
		case 'o': goto yy63;
		default: goto yy10;
	}
yy57:
	yych = *++in->cur;
	switch (yych) {
		case 'L': goto yy64;
		case 'T': goto yy65;
		default: goto yy10;
	}
yy58:
	yych = *++in->cur;
	switch (yych) {
		case '-': goto yy66;
		default: goto yy10;
	}
yy59:
	yych = *++in->cur;
	switch (yych) {
		case 'n': goto yy67;
		default: goto yy10;
	}
yy60:
	yych = *++in->cur;
	switch (yych) {
		case 'c': goto yy68;
		default: goto yy10;
	}
yy61:
	yych = *++in->cur;
	switch (yych) {
		case 't': goto yy69;
		default: goto yy10;
	}
yy62:
	yych = *++in->cur;
	switch (yych) {
		case 't': goto yy70;
		default: goto yy10;
	}
yy63:
	yych = *++in->cur;
	switch (yych) {
		case 'n': goto yy71;
		default: goto yy10;
	}
yy64:
	yych = *++in->cur;
	switch (yych) {
		case 'e': goto yy72;
		default: goto yy10;
	}
yy65:
	yych = *++in->cur;
	switch (yych) {
		case 'y': goto yy73;
		default: goto yy10;
	}
yy66:
	yych = *++in->cur;
	switch (yych) {
		case 'E': goto yy74;
		default: goto yy10;
	}
yy67:
	yych = *++in->cur;
	switch (yych) {
		case 't': goto yy75;
		default: goto yy10;
	}
yy68:
	yych = *++in->cur;
	switch (yych) {
		case 'o': goto yy76;
		default: goto yy10;
	}
yy69:
	yych = *++in->cur;
	switch (yych) {
		case 'i': goto yy77;
		default: goto yy10;
	}
yy70:
	yych = *++in->cur;
	switch (yych) {
		case 'r': goto yy78;
		default: goto yy10;
	}
yy71:
	yych = *++in->cur;
	switch (yych) {
		case ':': goto yy79;
		default: goto yy10;
	}
yy72:
	yych = *++in->cur;
	switch (yych) {
		case 'n': goto yy80;
		default: goto yy10;
	}
yy73:
	yych = *++in->cur;
	switch (yych) {
		case 'p': goto yy81;
		default: goto yy10;
	}
yy74:
	yych = *++in->cur;
	switch (yych) {
		case 'n': goto yy82;
		default: goto yy10;
	}
yy75:
	yych = *++in->cur;
	switch (yych) {
		case ':': goto yy83;
		default: goto yy10;
	}
yy76:
	yych = *++in->cur;
	switch (yych) {
		case 'd': goto yy84;
		default: goto yy10;
	}
yy77:
	yych = *++in->cur;
	switch (yych) {
		case 'o': goto yy85;
		default: goto yy10;
	}
yy78:
	yych = *++in->cur;
	switch (yych) {
		case 'o': goto yy86;
		default: goto yy10;
	}
yy79:
	++in->cur;
	{ *len = (size_t)(in->cur - in->tok); return 8; }
yy80:
	yych = *++in->cur;
	switch (yych) {
		case 'g': goto yy87;
		default: goto yy10;
	}
yy81:
	yych = *++in->cur;
	switch (yych) {
		case 'e': goto yy88;
		default: goto yy10;
	}
yy82:
	yych = *++in->cur;
	switch (yych) {
		case 'c': goto yy89;
		default: goto yy10;
	}
yy83:
	++in->cur;
	{ *len = (size_t)(in->cur - in->tok); return 6; }
yy84:
	yych = *++in->cur;
	switch (yych) {
		case 'i': goto yy90;
		default: goto yy10;
	}
yy85:
	yych = *++in->cur;
	switch (yych) {
		case 'n': goto yy91;
		default: goto yy10;
	}
yy86:
	yych = *++in->cur;
	switch (yych) {
		case 'l': goto yy92;
		default: goto yy10;
	}
yy87:
	yych = *++in->cur;
	switch (yych) {
		case 't': goto yy93;
		default: goto yy10;
	}
yy88:
	yych = *++in->cur;
	switch (yych) {
		case ':': goto yy94;
		default: goto yy10;
	}
yy89:
	yych = *++in->cur;
	switch (yych) {
		case 'o': goto yy95;
		default: goto yy10;
	}
yy90:
	yych = *++in->cur;
	switch (yych) {
		case 'n': goto yy96;
		default: goto yy10;
	}
yy91:
	yych = *++in->cur;
	switch (yych) {
		case ':': goto yy97;
		default: goto yy10;
	}
yy92:
	yych = *++in->cur;
	switch (yych) {
		case ':': goto yy98;
		default: goto yy10;
	}
yy93:
	yych = *++in->cur;
	switch (yych) {
		case 'h': goto yy99;
		default: goto yy10;
	}
yy94:
	++in->cur;
	{ *len = (size_t)(in->cur - in->tok); return 2; }
yy95:
	yych = *++in->cur;
	switch (yych) {
		case 'd': goto yy100;
		default: goto yy10;
	}
yy96:
	yych = *++in->cur;
	switch (yych) {
		case 'g': goto yy101;
		default: goto yy10;
	}
yy97:
	++in->cur;
	{ *len = (size_t)(in->cur - in->tok); return 4; }
yy98:
	++in->cur;
	{ *len = (size_t)(in->cur - in->tok); return 7; }
yy99:
	yych = *++in->cur;
	switch (yych) {
		case ':': goto yy102;
		default: goto yy10;
	}
yy100:
	yych = *++in->cur;
	switch (yych) {
		case 'i': goto yy103;
		default: goto yy10;
	}
yy101:
	yych = *++in->cur;
	switch (yych) {
		case ':': goto yy104;
		default: goto yy10;
	}
yy102:
	++in->cur;
	{ *len = (size_t)(in->cur - in->tok); return 1; }
yy103:
	yych = *++in->cur;
	switch (yych) {
		case 'n': goto yy105;
		default: goto yy10;
	}
yy104:
	++in->cur;
	{ *len = (size_t)(in->cur - in->tok); return 5; }
yy105:
	yych = *++in->cur;
	switch (yych) {
		case 'g': goto yy106;
		default: goto yy10;
	}
yy106:
	yych = *++in->cur;
	switch (yych) {
		case ':': goto yy107;
		default: goto yy10;
	}
yy107:
	++in->cur;
	{ *len = (size_t)(in->cur - in->tok); return 3; }
}

}

static int headers_1(Input* in, size_t* len) {
    in->tok = in->cur;
    
{
	unsigned char yych;
	if ((in->lim - in->cur) < 18) if (fill(in, 18) != 0) return -1;
	yych = *in->cur;
	switch (yych) {
		case 0x00: goto yy109;
		case '-':
		case 'B':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy112;
		case 'A': goto yy113;
		case 'C': goto yy114;
		case 'T': goto yy115;
		case 'U': goto yy116;
		default: goto yy110;
	}
yy109:
	++in->cur;
	{ *len = 0; return in->tok == in->lim - YYMAXFILL ? 100 : -1; }
yy110:
	++in->cur;
yy111:
	{ *len = (size_t)(in->cur - in->tok); return 0; }
yy112:
	yych = *(in->mar = ++in->cur);
	switch (yych) {
		case '-':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy117;
		case ':': goto yy120;
		default: goto yy111;
	}
yy113:
	yych = *(in->mar = ++in->cur);
	switch (yych) {
		case '-':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy117;
		case ':': goto yy120;
		case 'c': goto yy121;
		case 'u': goto yy122;
		default: goto yy111;
	}
yy114:
	yych = *(in->mar = ++in->cur);
	switch (yych) {
		case '-':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy117;
		case ':': goto yy120;
		case 'a': goto yy123;
		case 'o': goto yy124;
		default: goto yy111;
	}
yy115:
	yych = *(in->mar = ++in->cur);
	if (((unsigned long long)(unsigned char)in->cur[0] | (unsigned long long)(unsigned char)in->cur[1] << 8 * 1 | (unsigned long long)(unsigned char)in->cur[2] << 8 * 2 | (unsigned long long)(unsigned char)in->cur[3] << 8 * 3 | (unsigned long long)(unsigned char)in->cur[4] << 8 * 4 | (unsigned long long)(unsigned char)in->cur[5] << 8 * 5 | (unsigned long long)(unsigned char)in->cur[6] << 8 * 6 | (unsigned long long)(unsigned char)in->cur[7] << 8 * 7) == 0x2d726566736e6172) {
		in->cur += 7;
		goto yy174;
	} else {
		switch ((((((((((unsigned long long)(unsigned char)in->cur[0] | (unsigned long long)(unsigned char)in->cur[1] << 8 * 1 | (unsigned long long)(unsigned char)in->cur[2] << 8 * 2 | (unsigned long long)(unsigned char)in->cur[3] << 8 * 3 | (unsigned long long)(unsigned char)in->cur[4] << 8 * 4 | (unsigned long long)(unsigned char)in->cur[5] << 8 * 5 | (unsigned long long)(unsigned char)in->cur[6] << 8 * 6 | (unsigned long long)(unsigned char)in->cur[7] << 8 * 7) ^ 0x2d726566736e6172) - 1) & ~(((unsigned long long)(unsigned char)in->cur[0] | (unsigned long long)(unsigned char)in->cur[1] << 8 * 1 | (unsigned long long)(unsigned char)in->cur[2] << 8 * 2 | (unsigned long long)(unsigned char)in->cur[3] << 8 * 3 | (unsigned long long)(unsigned char)in->cur[4] << 8 * 4 | (unsigned long long)(unsigned char)in->cur[5] << 8 * 5 | (unsigned long long)(unsigned char)in->cur[6] << 8 * 6 | (unsigned long long)(unsigned char)in->cur[7] << 8 * 7) ^ 0x2d726566736e6172)) >> 7) & 0x0101010101010101ULL) * 0x0101010101010101ULL) >> 56)) {
			case 1: goto yy125;
			case 2:
				in->cur += 1;
				goto yy131;
			case 3:
				in->cur += 2;
				goto yy138;
			case 4:
				in->cur += 3;
				goto yy145;
			case 5:
				in->cur += 4;
				goto yy152;
			case 6:
				in->cur += 5;
				goto yy159;
			case 7:
				in->cur += 6;
				goto yy166;
		}
	}
	switch (yych) {
		case '-':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy117;
		case ':': goto yy120;
		case 'r': goto yy125;
		default: goto yy111;
	}
yy116:
	yych = *(in->mar = ++in->cur);
	if (((unsigned long long)(unsigned char)in->cur[0] | (unsigned long long)(unsigned char)in->cur[1] << 8 * 1 | (unsigned long long)(unsigned char)in->cur[2] << 8 * 2 | (unsigned long long)(unsigned char)in->cur[3] << 8 * 3 | (unsigned long long)(unsigned char)in->cur[4] << 8 * 4 | (unsigned long long)(unsigned char)in->cur[5] << 8 * 5 | (unsigned long long)(unsigned char)in->cur[6] << 8 * 6 | (unsigned long long)(unsigned char)in->cur[7] << 8 * 7) == 0x6e6567412d726573) {
		in->cur += 7;
		goto yy175;
	} else {
		switch ((((((((((unsigned long long)(unsigned char)in->cur[0] | (unsigned long long)(unsigned char)in->cur[1] << 8 * 1 | (unsigned long long)(unsigned char)in->cur[2] << 8 * 2 | (unsigned long long)(unsigned char)in->cur[3] << 8 * 3 | (unsigned long long)(unsigned char)in->cur[4] << 8 * 4 | (unsigned long long)(unsigned char)in->cur[5] << 8 * 5 | (unsigned long long)(unsigned char)in->cur[6] << 8 * 6 | (unsigned long long)(unsigned char)in->cur[7] << 8 * 7) ^ 0x6e6567412d726573) - 1) & ~(((unsigned long long)(unsigned char)in->cur[0] | (unsigned long long)(unsigned char)in->cur[1] << 8 * 1 | (unsigned long long)(unsigned char)in->cur[2] << 8 * 2 | (unsigned long long)(unsigned char)in->cur[3] << 8 * 3 | (unsigned long long)(unsigned char)in->cur[4] << 8 * 4 | (unsigned long long)(unsigned char)in->cur[5] << 8 * 5 | (unsigned long long)(unsigned char)in->cur[6] << 8 * 6 | (unsigned long long)(unsigned char)in->cur[7] << 8 * 7) ^ 0x6e6567412d726573)) >> 7) & 0x0101010101010101ULL) * 0x0101010101010101ULL) >> 56)) {
			case 1: goto yy126;
			case 2:
				in->cur += 1;
				goto yy132;
			case 3:
				in->cur += 2;
				goto yy139;
			case 4:
				in->cur += 3;
				goto yy146;
			case 5:
				in->cur += 4;
				goto yy153;
			case 6:
				in->cur += 5;
				goto yy160;
			case 7:
				in->cur += 6;
				goto yy167;
		}
	}
	switch (yych) {
		case '-':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy117;
		case ':': goto yy120;
		case 's': goto yy126;
		default: goto yy111;
	}
yy117:
	++in->cur;
	if (in->lim <= in->cur) if (fill(in, 1) != 0) return -1;
	yych = *in->cur;
yy118:
	switch (yych) {
		case '-':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy117;
		case ':': goto yy120;
		default: goto yy119;
	}
yy119:
	in->cur = in->mar;
	goto yy111;
yy120:
	++in->cur;
	{ *len = (size_t)(in->cur - in->tok); return 9; }
yy121:
	yych = *++in->cur;
	if (((unsigned long long)(unsigned char)in->cur[0] | (unsigned long long)(unsigned char)in->cur[1] << 8 * 1 | (unsigned long long)(unsigned char)in->cur[2] << 8 * 2 | (unsigned long long)(unsigned char)in->cur[3] << 8 * 3 | (unsigned long long)(unsigned char)in->cur[4] << 8 * 4 | (unsigned long long)(unsigned char)in->cur[5] << 8 * 5 | (unsigned long long)(unsigned char)in->cur[6] << 8 * 6 | (unsigned long long)(unsigned char)in->cur[7] << 8 * 7) == 0x636e452d74706563) {
		in->cur += 7;
		goto yy176;
	} else {
		switch ((((((((((unsigned long long)(unsigned char)in->cur[0] | (unsigned long long)(unsigned char)in->cur[1] << 8 * 1 | (unsigned long long)(unsigned char)in->cur[2] << 8 * 2 | (unsigned long long)(unsigned char)in->cur[3] << 8 * 3 | (unsigned long long)(unsigned char)in->cur[4] << 8 * 4 | (unsigned long long)(unsigned char)in->cur[5] << 8 * 5 | (unsigned long long)(unsigned char)in->cur[6] << 8 * 6 | (unsigned long long)(unsigned char)in->cur[7] << 8 * 7) ^ 0x636e452d74706563) - 1) & ~(((unsigned long long)(unsigned char)in->cur[0] | (unsigned long long)(unsigned char)in->cur[1] << 8 * 1 | (unsigned long long)(unsigned char)in->cur[2] << 8 * 2 | (unsigned long long)(unsigned char)in->cur[3] << 8 * 3 | (unsigned long long)(unsigned char)in->cur[4] << 8 * 4 | (unsigned long long)(unsigned char)in->cur[5] << 8 * 5 | (unsigned long long)(unsigned char)in->cur[6] << 8 * 6 | (unsigned long long)(unsigned char)in->cur[7] << 8 * 7) ^ 0x636e452d74706563)) >> 7) & 0x0101010101010101ULL) * 0x0101010101010101ULL) >> 56)) {
			case 1: goto yy127;
			case 2:
				in->cur += 1;
				goto yy133;
			case 3:
				in->cur += 2;
				goto yy140;
			case 4:
				in->cur += 3;
				goto yy147;
			case 5:
				in->cur += 4;
				goto yy154;
			case 6:
				in->cur += 5;
				goto yy161;
			case 7:
				in->cur += 6;
				goto yy168;
		}
	}
	switch (yych) {
		case 'c': goto yy127;
		default: goto yy118;
	}
yy122:
	yych = *++in->cur;
	if (((unsigned long long)(unsigned char)in->cur[0] | (unsigned long long)(unsigned char)in->cur[1] << 8 * 1 | (unsigned long long)(unsigned char)in->cur[2] << 8 * 2 | (unsigned long long)(unsigned char)in->cur[3] << 8 * 3 | (unsigned long long)(unsigned char)in->cur[4] << 8 * 4 | (unsigned long long)(unsigned char)in->cur[5] << 8 * 5 | (unsigned long long)(unsigned char)in->cur[6] << 8 * 6 | (unsigned long long)(unsigned char)in->cur[7] << 8 * 7) == 0x74617a69726f6874) {
		in->cur += 7;
		goto yy177;
	} else {
		switch ((((((((((unsigned long long)(unsigned char)in->cur[0] | (unsigned long long)(unsigned char)in->cur[1] << 8 * 1 | (unsigned long long)(unsigned char)in->cur[2] << 8 * 2 | (unsigned long long)(unsigned char)in->cur[3] << 8 * 3 | (unsigned long long)(unsigned char)in->cur[4] << 8 * 4 | (unsigned long long)(unsigned char)in->cur[5] << 8 * 5 | (unsigned long long)(unsigned char)in->cur[6] << 8 * 6 | (unsigned long long)(unsigned char)in->cur[7] << 8 * 7) ^ 0x74617a69726f6874) - 1) & ~(((unsigned long long)(unsigned char)in->cur[0] | (unsigned long long)(unsigned char)in->cur[1] << 8 * 1 | (unsigned long long)(unsigned char)in->cur[2] << 8 * 2 | (unsigned long long)(unsigned char)in->cur[3] << 8 * 3 | (unsigned long long)(unsigned char)in->cur[4] << 8 * 4 | (unsigned long long)(unsigned char)in->cur[5] << 8 * 5 | (unsigned long long)(unsigned char)in->cur[6] << 8 * 6 | (unsigned long long)(unsigned char)in->cur[7] << 8 * 7) ^ 0x74617a69726f6874)) >> 7) & 0x0101010101010101ULL) * 0x0101010101010101ULL) >> 56)) {
			case 1: goto yy128;
			case 2:
				in->cur += 1;
				goto yy134;
			case 3:
				in->cur += 2;
				goto yy141;
			case 4:
				in->cur += 3;
				goto yy148;
			case 5:
				in->cur += 4;
				goto yy155;
			case 6:
				in->cur += 5;
				goto yy162;
			case 7:
				in->cur += 6;
				goto yy169;
		}
	}
	switch (yych) {
		case 't': goto yy128;
		default: goto yy118;
	}
yy123:
	yych = *++in->cur;
	if (((unsigned long long)(unsigned char)in->cur[0] | (unsigned long long)(unsigned char)in->cur[1] << 8 * 1 | (unsigned long long)(unsigned char)in->cur[2] << 8 * 2 | (unsigned long long)(unsigned char)in->cur[3] << 8 * 3 | (unsigned long long)(unsigned char)in->cur[4] << 8 * 4 | (unsigned long long)(unsigned char)in->cur[5] << 8 * 5 | (unsigned long long)(unsigned char)in->cur[6] << 8 * 6 | (unsigned long long)(unsigned char)in->cur[7] << 8 * 7) == 0x746e6f432d656863) {
		in->cur += 7;
		goto yy178;
	} else {
		switch ((((((((((unsigned long long)(unsigned char)in->cur[0] | (unsigned long long)(unsigned char)in->cur[1] << 8 * 1 | (unsigned long long)(unsigned char)in->cur[2] << 8 * 2 | (unsigned long long)(unsigned char)in->cur[3] << 8 * 3 | (unsigned long long)(unsigned char)in->cur[4] << 8 * 4 | (unsigned long long)(unsigned char)in->cur[5] << 8 * 5 | (unsigned long long)(unsigned char)in->cur[6] << 8 * 6 | (unsigned long long)(unsigned char)in->cur[7] << 8 * 7) ^ 0x746e6f432d656863) - 1) & ~(((unsigned long long)(unsigned char)in->cur[0] | (unsigned long long)(unsigned char)in->cur[1] << 8 * 1 | (unsigned long long)(unsigned char)in->cur[2] << 8 * 2 | (unsigned long long)(unsigned char)in->cur[3] << 8 * 3 | (unsigned long long)(unsigned char)in->cur[4] << 8 * 4 | (unsigned long long)(unsigned char)in->cur[5] << 8 * 5 | (unsigned long long)(unsigned char)in->cur[6] << 8 * 6 | (unsigned long long)(unsigned char)in->cur[7] << 8 * 7) ^ 0x746e6f432d656863)) >> 7) & 0x0101010101010101ULL) * 0x0101010101010101ULL) >> 56)) {
			case 1: goto yy129;
			case 2:
				in->cur += 1;
				goto yy135;
			case 3:
				in->cur += 2;
				goto yy142;
			case 4:
				in->cur += 3;
				goto yy149;
			case 5:
				in->cur += 4;
				goto yy156;
			case 6:
				in->cur += 5;
				goto yy163;
			case 7:
				in->cur += 6;
				goto yy170;
		}
	}
	switch (yych) {
		case 'c': goto yy129;
		default: goto yy118;
	}
yy124:
	yych = *++in->cur;
	switch (yych) {
		case 'n': goto yy130;
		default: goto yy118;
	}
yy125:
	yych = *++in->cur;
	switch (yych) {
		case 'a': goto yy131;
		default: goto yy118;
	}
yy126:
	yych = *++in->cur;
	switch (yych) {
		case 'e': goto yy132;
		default: goto yy118;
	}
yy127:
	yych = *++in->cur;
	switch (yych) {
		case 'e': goto yy133;
		default: goto yy118;
	}
yy128:
	yych = *++in->cur;
	switch (yych) {
		case 'h': goto yy134;
		default: goto yy118;
	}
yy129:
	yych = *++in->cur;
	switch (yych) {
		case 'h': goto yy135;
		default: goto yy118;
	}
yy130:
	yych = *++in->cur;
	switch (yych) {
		case 'n': goto yy136;
		case 't': goto yy137;
		default: goto yy118;
	}
yy131:
	yych = *++in->cur;
	switch (yych) {
		case 'n': goto yy138;
		default: goto yy118;
	}
yy132:
	yych = *++in->cur;
	switch (yych) {
		case 'r': goto yy139;
		default: goto yy118;
	}
yy133:
	yych = *++in->cur;
	switch (yych) {
		case 'p': goto yy140;
		default: goto yy118;
	}
yy134:
	yych = *++in->cur;
	switch (yych) {
		case 'o': goto yy141;
		default: goto yy118;
	}
yy135:
	yych = *++in->cur;
	switch (yych) {
		case 'e': goto yy142;
		default: goto yy118;
	}
yy136:
	yych = *++in->cur;
	if (((unsigned long long)(unsigned char)in->cur[0] | (unsigned long long)(unsigned char)in->cur[1] << 8 * 1 | (unsigned long long)(unsigned char)in->cur[2] << 8 * 2 | (unsigned long long)(unsigned char)in->cur[3] << 8 * 3) == 0x69746365) {
		in->cur += 3;
		goto yy164;
	} else {
		switch ((((((((((unsigned long long)(unsigned char)in->cur[0] | (unsigned long long)(unsigned char)in->cur[1] << 8 * 1 | (unsigned long long)(unsigned char)in->cur[2] << 8 * 2 | (unsigned long long)(unsigned char)in->cur[3] << 8 * 3) ^ 0x69746365) - 1) & ~(((unsigned long long)(unsigned char)in->cur[0] | (unsigned long long)(unsigned char)in->cur[1] << 8 * 1 | (unsigned long long)(unsigned char)in->cur[2] << 8 * 2 | (unsigned long long)(unsigned char)in->cur[3] << 8 * 3) ^ 0x69746365)) >> 7) & 0x0101010101010101ULL) * 0x0101010101010101ULL) >> 56)) {
			case 1: goto yy143;
			case 2:
				in->cur += 1;
				goto yy150;
			case 3:
				in->cur += 2;
				goto yy157;
		}
	}
	switch (yych) {
		case 'e': goto yy143;
		default: goto yy118;
	}
yy137:
	yych = *++in->cur;
	if (((unsigned long long)(unsigned char)in->cur[0] | (unsigned long long)(unsigned char)in->cur[1] << 8 * 1 | (unsigned long long)(unsigned char)in->cur[2] << 8 * 2 | (unsigned long long)(unsigned char)in->cur[3] << 8 * 3) == 0x2d746e65) {
		in->cur += 3;
		goto yy165;
	} else {
		switch ((((((((((unsigned long long)(unsigned char)in->cur[0] | (unsigned long long)(unsigned char)in->cur[1] << 8 * 1 | (unsigned long long)(unsigned char)in->cur[2] << 8 * 2 | (unsigned long long)(unsigned char)in->cur[3] << 8 * 3) ^ 0x2d746e65) - 1) & ~(((unsigned long long)(unsigned char)in->cur[0] | (unsigned long long)(unsigned char)in->cur[1] << 8 * 1 | (unsigned long long)(unsigned char)in->cur[2] << 8 * 2 | (unsigned long long)(unsigned char)in->cur[3] << 8 * 3) ^ 0x2d746e65)) >> 7) & 0x0101010101010101ULL) * 0x0101010101010101ULL) >> 56)) {
			case 1: goto yy144;
			case 2:
				in->cur += 1;
				goto yy151;
			case 3:
				in->cur += 2;
				goto yy158;
		}
	}
	switch (yych) {
		case 'e': goto yy144;
		default: goto yy118;
	}
yy138:
	yych = *++in->cur;
	switch (yych) {
		case 's': goto yy145;
		default: goto yy118;
	}
yy139:
	yych = *++in->cur;
	switch (yych) {
		case '-': goto yy146;
		default: goto yy118;
	}
yy140:
	yych = *++in->cur;
	switch (yych) {
		case 't': goto yy147;
		default: goto yy118;
	}
yy141:
	yych = *++in->cur;
	switch (yych) {
		case 'r': goto yy148;
		default: goto yy118;
	}
yy142:
	yych = *++in->cur;
	switch (yych) {
		case '-': goto yy149;
		default: goto yy118;
	}
yy143:
	yych = *++in->cur;
	switch (yych) {
		case 'c': goto yy150;
		default: goto yy118;
	}
yy144:
	yych = *++in->cur;
	switch (yych) {
		case 'n': goto yy151;
		default: goto yy118;
	}
yy145:
	yych = *++in->cur;
	switch (yych) {
		case 'f': goto yy152;
		default: goto yy118;
	}
yy146:
	yych = *++in->cur;
	switch (yych) {
		case 'A': goto yy153;
		default: goto yy118;
	}
yy147:
	yych = *++in->cur;
	switch (yych) {
		case '-': goto yy154;
		default: goto yy118;
	}
yy148:
	yych = *++in->cur;
	switch (yych) {
		case 'i': goto yy155;
		default: goto yy118;
	}
yy149:
	yych = *++in->cur;
	switch (yych) {
		case 'C': goto yy156;
		default: goto yy118;
	}
yy150:
	yych = *++in->cur;
	switch (yych) {
		case 't': goto yy157;
		default: goto yy118;
	}
yy151:
	yych = *++in->cur;
	switch (yych) {
		case 't': goto yy158;
		default: goto yy118;
	}
yy152:
	yych = *++in->cur;
	switch (yych) {
		case 'e': goto yy159;
		default: goto yy118;
	}
yy153:
	yych = *++in->cur;
	switch (yych) {
		case 'g': goto yy160;
		default: goto yy118;
	}
yy154:
	yych = *++in->cur;
	switch (yych) {
		case 'E': goto yy161;
		default: goto yy118;
	}
yy155:
	yych = *++in->cur;
	switch (yych) {
		case 'z': goto yy162;
		default: goto yy118;
	}
yy156:
	yych = *++in->cur;
	switch (yych) {
		case 'o': goto yy163;
		default: goto yy118;
	}
yy157:
	yych = *++in->cur;
	switch (yych) {
		case 'i': goto yy164;
		default: goto yy118;
	}
yy158:
	yych = *++in->cur;
	switch (yych) {
		case '-': goto yy165;
		default: goto yy118;
	}
yy159:
	yych = *++in->cur;
	switch (yych) {
		case 'r': goto yy166;
		default: goto yy118;
	}
yy160:
	yych = *++in->cur;
	switch (yych) {
		case 'e': goto yy167;
		default: goto yy118;
	}
yy161:
	yych = *++in->cur;
	switch (yych) {
		case 'n': goto yy168;
		default: goto yy118;
	}
yy162:
	yych = *++in->cur;
	switch (yych) {
		case 'a': goto yy169;
		default: goto yy118;
	}
yy163:
	yych = *++in->cur;
	switch (yych) {
		case 'n': goto yy170;
		default: goto yy118;
	}
yy164:
	yych = *++in->cur;
	if (((unsigned long long)(unsigned char)in->cur[0] | (unsigned long long)(unsigned char)in->cur[1] << 8 * 1) == 0x6e6f) {
		in->cur += 1;
		goto yy179;
	} else {
		switch ((((((((((unsigned long long)(unsigned char)in->cur[0] | (unsigned long long)(unsigned char)in->cur[1] << 8 * 1) ^ 0x6e6f) - 1) & ~(((unsigned long long)(unsigned char)in->cur[0] | (unsigned long long)(unsigned char)in->cur[1] << 8 * 1) ^ 0x6e6f)) >> 7) & 0x0101010101010101ULL) * 0x0101010101010101ULL) >> 56)) {
			case 1: goto yy171;
		}
	}
	switch (yych) {
		case 'o': goto yy171;
		default: goto yy118;
	}
yy165:
	yych = *++in->cur;
	switch (yych) {
		case 'L': goto yy172;
		case 'T': goto yy173;
		default: goto yy118;
	}
yy166:
	yych = *++in->cur;
	switch (yych) {
		case '-': goto yy174;
		default: goto yy118;
	}
yy167:
	yych = *++in->cur;
	switch (yych) {
		case 'n': goto yy175;
		default: goto yy118;
	}
yy168:
	yych = *++in->cur;
	switch (yych) {
		case 'c': goto yy176;
		default: goto yy118;
	}
yy169:
	yych = *++in->cur;
	switch (yych) {
		case 't': goto yy177;
		default: goto yy118;
	}
yy170:
	yych = *++in->cur;
	switch (yych) {
		case 't': goto yy178;
		default: goto yy118;
	}
yy171:
	yych = *++in->cur;
	switch (yych) {
		case 'n': goto yy179;
		default: goto yy118;
	}
yy172:
	yych = *++in->cur;
	if (((unsigned long long)(unsigned char)in->cur[0] | (unsigned long long)(unsigned char)in->cur[1] << 8 * 1 | (unsigned long long)(unsigned char)in->cur[2] << 8 * 2 | (unsigned long long)(unsigned char)in->cur[3] << 8 * 3) == 0x74676e65) {
		in->cur += 3;
		goto yy201;
	} else {
		switch ((((((((((unsigned long long)(unsigned char)in->cur[0] | (unsigned long long)(unsigned char)in->cur[1] << 8 * 1 | (unsigned long long)(unsigned char)in->cur[2] << 8 * 2 | (unsigned long long)(unsigned char)in->cur[3] << 8 * 3) ^ 0x74676e65) - 1) & ~(((unsigned long long)(unsigned char)in->cur[0] | (unsigned long long)(unsigned char)in->cur[1] << 8 * 1 | (unsigned long long)(unsigned char)in->cur[2] << 8 * 2 | (unsigned long long)(unsigned char)in->cur[3] << 8 * 3) ^ 0x74676e65)) >> 7) & 0x0101010101010101ULL) * 0x0101010101010101ULL) >> 56)) {
			case 1: goto yy180;
			case 2:
				in->cur += 1;
				goto yy188;
			case 3:
				in->cur += 2;
				goto yy195;
		}
	}
	switch (yych) {
		case 'e': goto yy180;
		default: goto yy118;
	}
yy173:
	yych = *++in->cur;
	if (((unsigned long long)(unsigned char)in->cur[0] | (unsigned long long)(unsigned char)in->cur[1] << 8 * 1 | (unsigned long long)(unsigned char)in->cur[2] << 8 * 2 | (unsigned long long)(unsigned char)in->cur[3] << 8 * 3) == 0x3a657079) {
		in->cur += 3;
		goto yy202;
	} else {
		switch ((((((((((unsigned long long)(unsigned char)in->cur[0] | (unsigned long long)(unsigned char)in->cur[1] << 8 * 1 | (unsigned long long)(unsigned char)in->cur[2] << 8 * 2 | (unsigned long long)(unsigned char)in->cur[3] << 8 * 3) ^ 0x3a657079) - 1) & ~(((unsigned long long)(unsigned char)in->cur[0] | (unsigned long long)(unsigned char)in->cur[1] << 8 * 1 | (unsigned long long)(unsigned char)in->cur[2] << 8 * 2 | (unsigned long long)(unsigned char)in->cur[3] << 8 * 3) ^ 0x3a657079)) >> 7) & 0x0101010101010101ULL) * 0x0101010101010101ULL) >> 56)) {
			case 1: goto yy181;
			case 2:
				in->cur += 1;
				goto yy189;
			case 3:
				in->cur += 2;
				goto yy196;
		}
	}
	switch (yych) {
		case 'y': goto yy181;
		default: goto yy118;
	}
yy174:
	yych = *++in->cur;
	if (((unsigned long long)(unsigned char)in->cur[0] | (unsigned long long)(unsigned char)in->cur[1] << 8 * 1 | (unsigned long long)(unsigned char)in->cur[2] << 8 * 2 | (unsigned long long)(unsigned char)in->cur[3] << 8 * 3 | (unsigned long long)(unsigned char)in->cur[4] << 8 * 4 | (unsigned long long)(unsigned char)in->cur[5] << 8 * 5 | (unsigned long long)(unsigned char)in->cur[6] << 8 * 6 | (unsigned long long)(unsigned char)in->cur[7] << 8 * 7) == 0x676e69646f636e45) {
		in->cur += 7;
		goto yy214;
	} else {
		switch ((((((((((unsigned long long)(unsigned char)in->cur[0] | (unsigned long long)(unsigned char)in->cur[1] << 8 * 1 | (unsigned long long)(unsigned char)in->cur[2] << 8 * 2 | (unsigned long long)(unsigned char)in->cur[3] << 8 * 3 | (unsigned long long)(unsigned char)in->cur[4] << 8 * 4 | (unsigned long long)(unsigned char)in->cur[5] << 8 * 5 | (unsigned long long)(unsigned char)in->cur[6] << 8 * 6 | (unsigned long long)(unsigned char)in->cur[7] << 8 * 7) ^ 0x676e69646f636e45) - 1) & ~(((unsigned long long)(unsigned char)in->cur[0] | (unsigned long long)(unsigned char)in->cur[1] << 8 * 1 | (unsigned long long)(unsigned char)in->cur[2] << 8 * 2 | (unsigned long long)(unsigned char)in->cur[3] << 8 * 3 | (unsigned long long)(unsigned char)in->cur[4] << 8 * 4 | (unsigned long long)(unsigned char)in->cur[5] << 8 * 5 | (unsigned long long)(unsigned char)in->cur[6] << 8 * 6 | (unsigned long long)(unsigned char)in->cur[7] << 8 * 7) ^ 0x676e69646f636e45)) >> 7) & 0x0101010101010101ULL) * 0x0101010101010101ULL) >> 56)) {
			case 1: goto yy182;
			case 2:
				in->cur += 1;
				goto yy190;
			case 3:
				in->cur += 2;
				goto yy197;
			case 4:
				in->cur += 3;
				goto yy203;
			case 5:
				in->cur += 4;
				goto yy208;
			case 6:
				in->cur += 5;
				goto yy211;
			case 7:
				in->cur += 6;
				goto yy213;
		}
	}
	switch (yych) {
		case 'E': goto yy182;
		default: goto yy118;
	}
yy175:
	yych = *++in->cur;
	if (((unsigned long long)(unsigned char)in->cur[0] | (unsigned long long)(unsigned char)in->cur[1] << 8 * 1) == 0x3a74) {
		in->cur += 1;
		goto yy191;
	} else {
		switch ((((((((((unsigned long long)(unsigned char)in->cur[0] | (unsigned long long)(unsigned char)in->cur[1] << 8 * 1) ^ 0x3a74) - 1) & ~(((unsigned long long)(unsigned char)in->cur[0] | (unsigned long long)(unsigned char)in->cur[1] << 8 * 1) ^ 0x3a74)) >> 7) & 0x0101010101010101ULL) * 0x0101010101010101ULL) >> 56)) {
			case 1: goto yy183;
		}
	}
	switch (yych) {
		case 't': goto yy183;
		default: goto yy118;
	}
yy176:
	yych = *++in->cur;
	if (((unsigned long long)(unsigned char)in->cur[0] | (unsigned long long)(unsigned char)in->cur[1] << 8 * 1 | (unsigned long long)(unsigned char)in->cur[2] << 8 * 2 | (unsigned long long)(unsigned char)in->cur[3] << 8 * 3) == 0x6e69646f) {
		in->cur += 3;
		goto yy204;
	} else {
		switch ((((((((((unsigned long long)(unsigned char)in->cur[0] | (unsigned long long)(unsigned char)in->cur[1] << 8 * 1 | (unsigned long long)(unsigned char)in->cur[2] << 8 * 2 | (unsigned long long)(unsigned char)in->cur[3] << 8 * 3) ^ 0x6e69646f) - 1) & ~(((unsigned long long)(unsigned char)in->cur[0] | (unsigned long long)(unsigned char)in->cur[1] << 8 * 1 | (unsigned long long)(unsigned char)in->cur[2] << 8 * 2 | (unsigned long long)(unsigned char)in->cur[3] << 8 * 3) ^ 0x6e69646f)) >> 7) & 0x0101010101010101ULL) * 0x0101010101010101ULL) >> 56)) {
			case 1: goto yy184;
			case 2:
				in->cur += 1;
				goto yy192;
			case 3:
				in->cur += 2;
				goto yy198;
		}
	}
	switch (yych) {
		case 'o': goto yy184;
		default: goto yy118;
	}
yy177:
	yych = *++in->cur;
	if (((unsigned long long)(unsigned char)in->cur[0] | (unsigned long long)(unsigned char)in->cur[1] << 8 * 1 | (unsigned long long)(unsigned char)in->cur[2] << 8 * 2 | (unsigned long long)(unsigned char)in->cur[3] << 8 * 3) == 0x3a6e6f69) {
		in->cur += 3;
		goto yy205;
	} else {
		switch ((((((((((unsigned long long)(unsigned char)in->cur[0] | (unsigned long long)(unsigned char)in->cur[1] << 8 * 1 | (unsigned long long)(unsigned char)in->cur[2] << 8 * 2 | (unsigned long long)(unsigned char)in->cur[3] << 8 * 3) ^ 0x3a6e6f69) - 1) & ~(((unsigned long long)(unsigned char)in->cur[0] | (unsigned long long)(unsigned char)in->cur[1] << 8 * 1 | (unsigned long long)(unsigned char)in->cur[2] << 8 * 2 | (unsigned long long)(unsigned char)in->cur[3] << 8 * 3) ^ 0x3a6e6f69)) >> 7) & 0x0101010101010101ULL) * 0x0101010101010101ULL) >> 56)) {
			case 1: goto yy185;
			case 2:
				in->cur += 1;
				goto yy193;
			case 3:
				in->cur += 2;
				goto yy199;
		}
	}
	switch (yych) {
		case 'i': goto yy185;
		default: goto yy118;
	}
yy178:
	yych = *++in->cur;
	if (((unsigned long long)(unsigned char)in->cur[0] | (unsigned long long)(unsigned char)in->cur[1] << 8 * 1 | (unsigned long long)(unsigned char)in->cur[2] << 8 * 2 | (unsigned long long)(unsigned char)in->cur[3] << 8 * 3) == 0x3a6c6f72) {
		in->cur += 3;
		goto yy206;
	} else {
		switch ((((((((((unsigned long long)(unsigned char)in->cur[0] | (unsigned long long)(unsigned char)in->cur[1] << 8 * 1 | (unsigned long long)(unsigned char)in->cur[2] << 8 * 2 | (unsigned long long)(unsigned char)in->cur[3] << 8 * 3) ^ 0x3a6c6f72) - 1) & ~(((unsigned long long)(unsigned char)in->cur[0] | (unsigned long long)(unsigned char)in->cur[1] << 8 * 1 | (unsigned long long)(unsigned char)in->cur[2] << 8 * 2 | (unsigned long long)(unsigned char)in->cur[3] << 8 * 3) ^ 0x3a6c6f72)) >> 7) & 0x0101010101010101ULL) * 0x0101010101010101ULL) >> 56)) {
			case 1: goto yy186;
			case 2:
				in->cur += 1;
				goto yy194;
			case 3:
				in->cur += 2;
				goto yy200;
		}
	}
	switch (yych) {
		case 'r': goto yy186;
		default: goto yy118;
	}
yy179:
	yych = *++in->cur;
	switch (yych) {
		case ':': goto yy187;
		default: goto yy118;
	}
yy180:
	yych = *++in->cur;
	switch (yych) {
		case 'n': goto yy188;
		default: goto yy118;
	}
yy181:
	yych = *++in->cur;
	switch (yych) {
		case 'p': goto yy189;
		default: goto yy118;
	}
yy182:
	yych = *++in->cur;
	switch (yych) {
		case 'n': goto yy190;
		default: goto yy118;
	}
yy183:
	yych = *++in->cur;
	switch (yych) {
		case ':': goto yy191;
		default: goto yy118;
	}
yy184:
	yych = *++in->cur;
	switch (yych) {
		case 'd': goto yy192;
		default: goto yy118;
	}
yy185:
	yych = *++in->cur;
	switch (yych) {
		case 'o': goto yy193;
		default: goto yy118;
	}
yy186:
	yych = *++in->cur;
	switch (yych) {
		case 'o': goto yy194;
		default: goto yy118;
	}
yy187:
	++in->cur;
	{ *len = (size_t)(in->cur - in->tok); return 8; }
yy188:
	yych = *++in->cur;
	switch (yych) {
		case 'g': goto yy195;
		default: goto yy118;
	}
yy189:
	yych = *++in->cur;
	switch (yych) {
		case 'e': goto yy196;
		default: goto yy118;
	}
yy190:
	yych = *++in->cur;
	switch (yych) {
		case 'c': goto yy197;
		default: goto yy118;
	}
yy191:
	++in->cur;
	{ *len = (size_t)(in->cur - in->tok); return 6; }
yy192:
	yych = *++in->cur;
	switch (yych) {
		case 'i': goto yy198;
		default: goto yy118;
	}
yy193:
	yych = *++in->cur;
	switch (yych) {
		case 'n': goto yy199;
		default: goto yy118;
	}
yy194:
	yych = *++in->cur;
	switch (yych) {
		case 'l': goto yy200;
		default: goto yy118;
	}
yy195:
	yych = *++in->cur;
	switch (yych) {
		case 't': goto yy201;
		default: goto yy118;
	}
yy196:
	yych = *++in->cur;
	switch (yych) {
		case ':': goto yy202;
		default: goto yy118;
	}
yy197:
	yych = *++in->cur;
	switch (yych) {
		case 'o': goto yy203;
		default: goto yy118;
	}
yy198:
	yych = *++in->cur;
	switch (yych) {
		case 'n': goto yy204;
		default: goto yy118;
	}
yy199:
	yych = *++in->cur;
	switch (yych) {
		case ':': goto yy205;
		default: goto yy118;
	}
yy200:
	yych = *++in->cur;
	switch (yych) {
		case ':': goto yy206;
		default: goto yy118;
	}
yy201:
	yych = *++in->cur;
	if (((unsigned long long)(unsigned char)in->cur[0] | (unsigned long long)(unsigned char)in->cur[1] << 8 * 1) == 0x3a68) {
		in->cur += 1;
		goto yy210;
	} else {
		switch ((((((((((unsigned long long)(unsigned char)in->cur[0] | (unsigned long long)(unsigned char)in->cur[1] << 8 * 1) ^ 0x3a68) - 1) & ~(((unsigned long long)(unsigned char)in->cur[0] | (unsigned long long)(unsigned char)in->cur[1] << 8 * 1) ^ 0x3a68)) >> 7) & 0x0101010101010101ULL) * 0x0101010101010101ULL) >> 56)) {
			case 1: goto yy207;
		}
	}
	switch (yych) {
		case 'h': goto yy207;
		default: goto yy118;
	}
yy202:
	++in->cur;
	{ *len = (size_t)(in->cur - in->tok); return 2; }
yy203:
	yych = *++in->cur;
	switch (yych) {
		case 'd': goto yy208;
		default: goto yy118;
	}
yy204:
	yych = *++in->cur;
	if (((unsigned long long)(unsigned char)in->cur[0] | (unsigned long long)(unsigned char)in->cur[1] << 8 * 1) == 0x3a67) {
		in->cur += 1;
		goto yy212;
	} else {
		switch ((((((((((unsigned long long)(unsigned char)in->cur[0] | (unsigned long long)(unsigned char)in->cur[1] << 8 * 1) ^ 0x3a67) - 1) & ~(((unsigned long long)(unsigned char)in->cur[0] | (unsigned long long)(unsigned char)in->cur[1] << 8 * 1) ^ 0x3a67)) >> 7) & 0x0101010101010101ULL) * 0x0101010101010101ULL) >> 56)) {
			case 1: goto yy209;
		}
	}
	switch (yych) {
		case 'g': goto yy209;
		default: goto yy118;
	}
yy205:
	++in->cur;
	{ *len = (size_t)(in->cur - in->tok); return 4; }
yy206:
	++in->cur;
	{ *len = (size_t)(in->cur - in->tok); return 7; }
yy207:
	yych = *++in->cur;
	switch (yych) {
		case ':': goto yy210;
		default: goto yy118;
	}
yy208:
	yych = *++in->cur;
	switch (yych) {
		case 'i': goto yy211;
		default: goto yy118;
	}
yy209:
	yych = *++in->cur;
	switch (yych) {
		case ':': goto yy212;
		default: goto yy118;
	}
yy210:
	++in->cur;
	{ *len = (size_t)(in->cur - in->tok); return 1; }
yy211:
	yych = *++in->cur;
	switch (yych) {
		case 'n': goto yy213;
		default: goto yy118;
	}
yy212:
	++in->cur;
	{ *len = (size_t)(in->cur - in->tok); return 5; }
yy213:
	yych = *++in->cur;
	switch (yych) {
		case 'g': goto yy214;
		default: goto yy118;
	}
yy214:
	yych = *++in->cur;
	switch (yych) {
		case ':': goto yy215;
		default: goto yy118;
	}
yy215:
	++in->cur;
	{ *len = (size_t)(in->cur - in->tok); return 3; }
}

}

static const struct word headers_words[] = {
    {"\x43\x6f\x6e\x74\x65\x6e\x74\x2d\x4c\x65\x6e\x67\x74\x68\x3a", 15},
    {"\x43\x6f\x6e\x74\x65\x6e\x74\x2d\x54\x79\x70\x65\x3a", 13},
    {"\x54\x72\x61\x6e\x73\x66\x65\x72\x2d\x45\x6e\x63\x6f\x64\x69\x6e\x67\x3a", 18},
    {"\x41\x75\x74\x68\x6f\x72\x69\x7a\x61\x74\x69\x6f\x6e\x3a", 14},
    {"\x41\x63\x63\x65\x70\x74\x2d\x45\x6e\x63\x6f\x64\x69\x6e\x67\x3a", 16},
    {"\x55\x73\x65\x72\x2d\x41\x67\x65\x6e\x74\x3a", 11},
    {"\x43\x61\x63\x68\x65\x2d\x43\x6f\x6e\x74\x72\x6f\x6c\x3a", 14},
    {"\x43\x6f\x6e\x6e\x65\x63\x74\x69\x6f\x6e\x3a", 11},
    {"\x43\x6f\x6e\x74\x65\x6e\x74\x2d\x4c\x61\x6e\x67\x75\x61\x67\x65\x3a", 17},
    {"\x41\x63\x63\x65\x70\x74\x3a", 7},
    {"\x43\x6f\x6e\x6e\x65\x63\x74\x69\x6f\x6e\x2d\x49\x64\x3a", 14},
    {"\x43\x61\x63\x68\x65\x2d\x53\x74\x61\x74\x75\x73\x3a", 13},
    {NULL, 0}
};



static int keywords_0(Input* in, size_t* len) {
    in->tok = in->cur;
    
{
	unsigned char yych;
	if ((in->lim - in->cur) < 9) if (fill(in, 9) != 0) return -1;
	yych = *in->cur;
	switch (yych) {
		case 0x00: goto yy217;
		case ' ': goto yy219;
		case 'A':
		case 'C':
		case 'E':
		case 'G':
		case 'H':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'T':
		case 'V':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy221;
		case 'B': goto yy224;
		case 'D': goto yy225;
		case 'F': goto yy226;
		case 'I': goto yy227;
		case 'S': goto yy228;
		case 'U': goto yy229;
		case 'W': goto yy230;
		default: goto yy218;
	}
yy217:
	++in->cur;
	{ *len = 0; return in->tok == in->lim - YYMAXFILL ? 100 : -1; }
yy218:
	++in->cur;
	{ *len = (size_t)(in->cur - in->tok); return 0; }
yy219:
	++in->cur;
	if (in->lim <= in->cur) if (fill(in, 1) != 0) return -1;
	yych = *in->cur;
	switch (yych) {
		case ' ': goto yy219;
		default: goto yy220;
	}
yy220:
	{ *len = (size_t)(in->cur - in->tok); return 10; }
yy221:
	++in->cur;
	if (in->lim <= in->cur) if (fill(in, 1) != 0) return -1;
	yych = *in->cur;
yy222:
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy221;
		default: goto yy223;
	}
yy223:
	{ *len = (size_t)(in->cur - in->tok); return 9; }
yy224:
	yych = *++in->cur;
	switch (yych) {
		case 'E': goto yy231;
		default: goto yy222;
	}
yy225:
	yych = *++in->cur;
	switch (yych) {
		case 'E': goto yy232;
		case 'I': goto yy233;
		default: goto yy222;
	}
yy226:
	yych = *++in->cur;
	switch (yych) {
		case 'R': goto yy234;
		default: goto yy222;
	}
yy227:
	yych = *++in->cur;
	switch (yych) {
		case 'N': goto yy235;
		default: goto yy222;
	}
yy228:
	yych = *++in->cur;
	switch (yych) {
		case 'E': goto yy236;
		default: goto yy222;
	}
yy229:
	yych = *++in->cur;
	switch (yych) {
		case 'P': goto yy237;
		default: goto yy222;
	}
yy230:
	yych = *++in->cur;
	switch (yych) {
		case 'H': goto yy238;
		default: goto yy222;
	}
yy231:
	yych = *++in->cur;
	switch (yych) {
		case 'T': goto yy239;
		default: goto yy222;
	}
yy232:
	yych = *++in->cur;
	switch (yych) {
		case 'L': goto yy240;
		default: goto yy222;
	}
yy233:
	yych = *++in->cur;
	switch (yych) {
		case 'S': goto yy241;
		default: goto yy222;
	}
yy234:
	yych = *++in->cur;
	switch (yych) {
		case 'O': goto yy242;
		default: goto yy222;
	}
yy235:
	yych = *++in->cur;
	switch (yych) {
		case 'S': goto yy243;
		default: goto yy222;
	}
yy236:
	yych = *++in->cur;
	switch (yych) {
		case 'L': goto yy244;
		default: goto yy222;
	}
yy237:
	yych = *++in->cur;
	switch (yych) {
		case 'D': goto yy245;
		default: goto yy222;
	}
yy238:
	yych = *++in->cur;
	switch (yych) {
		case 'E': goto yy246;
		default: goto yy222;
	}
yy239:
	yych = *++in->cur;
	switch (yych) {
		case 'W': goto yy247;
		default: goto yy222;
	}
yy240:
	yych = *++in->cur;
	switch (yych) {
		case 'E': goto yy248;
		default: goto yy222;
	}
yy241:
	yych = *++in->cur;
	switch (yych) {
		case 'T': goto yy249;
		default: goto yy222;
	}
yy242:
	yych = *++in->cur;
	switch (yych) {
		case 'M': goto yy250;
		default: goto yy222;
	}
yy243:
	yych = *++in->cur;
	switch (yych) {
		case 'E': goto yy252;
		default: goto yy222;
	}
yy244:
	yych = *++in->cur;
	switch (yych) {
		case 'E': goto yy253;
		default: goto yy222;
	}
yy245:
	yych = *++in->cur;
	switch (yych) {
		case 'A': goto yy254;
		default: goto yy222;
	}
yy246:
	yych = *++in->cur;
	switch (yych) {
		case 'R': goto yy255;
		default: goto yy222;
	}
yy247:
	yych = *++in->cur;
	switch (yych) {
		case 'E': goto yy256;
		default: goto yy222;
	}
yy248:
	yych = *++in->cur;
	switch (yych) {
		case 'T': goto yy257;
		default: goto yy222;
	}
yy249:
	yych = *++in->cur;
	switch (yych) {
		case 'I': goto yy258;
		default: goto yy222;
	}
yy250:
	yych = *++in->cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy221;
		default: goto yy251;
	}
yy251:
	{ *len = (size_t)(in->cur - in->tok); return 5; }
yy252:
	yych = *++in->cur;
	switch (yych) {
		case 'R': goto yy259;
		default: goto yy222;
	}
yy253:
	yych = *++in->cur;
	switch (yych) {
		case 'C': goto yy260;
		default: goto yy222;
	}
yy254:
	yych = *++in->cur;
	switch (yych) {
		case 'T': goto yy261;
		default: goto yy222;
	}
yy255:
	yych = *++in->cur;
	switch (yych) {
		case 'E': goto yy262;
		default: goto yy222;
	}
yy256:
	yych = *++in->cur;
	switch (yych) {
		case 'E': goto yy264;
		default: goto yy222;
	}
yy257:
	yych = *++in->cur;
	switch (yych) {
		case 'E': goto yy265;
		default: goto yy222;
	}
yy258:
	yych = *++in->cur;
	switch (yych) {
		case 'N': goto yy267;
		default: goto yy222;
	}
yy259:
	yych = *++in->cur;
	switch (yych) {
		case 'T': goto yy268;
		default: goto yy222;
	}
yy260:
	yych = *++in->cur;
	switch (yych) {
		case 'T': goto yy270;
		default: goto yy222;
	}
yy261:
	yych = *++in->cur;
	switch (yych) {
		case 'E': goto yy272;
		default: goto yy222;
	}
yy262:
	yych = *++in->cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy221;
		default: goto yy263;
	}
yy263:
	{ *len = (size_t)(in->cur - in->tok); return 6; }
yy264:
	yych = *++in->cur;
	switch (yych) {
		case 'N': goto yy274;
		default: goto yy222;
	}
yy265:
	yych = *++in->cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy221;
		default: goto yy266;
	}
yy266:
	{ *len = (size_t)(in->cur - in->tok); return 4; }
yy267:
	yych = *++in->cur;
	switch (yych) {
		case 'C': goto yy276;
		default: goto yy222;
	}
yy268:
	yych = *++in->cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy221;
		default: goto yy269;
	}
yy269:
	{ *len = (size_t)(in->cur - in->tok); return 2; }
yy270:
	yych = *++in->cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy221;
		default: goto yy271;
	}
yy271:
	{ *len = (size_t)(in->cur - in->tok); return 1; }
yy272:
	yych = *++in->cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy221;
		default: goto yy273;
	}
yy273:
	{ *len = (size_t)(in->cur - in->tok); return 3; }
yy274:
	yych = *++in->cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy221;
		default: goto yy275;
	}
yy275:
	{ *len = (size_t)(in->cur - in->tok); return 7; }
yy276:
	yych = *++in->cur;
	switch (yych) {
		case 'T': goto yy277;
		default: goto yy222;
	}
yy277:
	yych = *++in->cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy221;
		default: goto yy278;
	}
yy278:
	{ *len = (size_t)(in->cur - in->tok); return 8; }
}

}

static int keywords_1(Input* in, size_t* len) {
    in->tok = in->cur;
    
{
	unsigned char yych;
	if ((in->lim - in->cur) < 9) if (fill(in, 9) != 0) return -1;
	yych = *in->cur;
	switch (yych) {
		case 0x00: goto yy280;
		case ' ': goto yy282;
		case 'A':
		case 'C':
		case 'E':
		case 'G':
		case 'H':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'T':
		case 'V':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy284;
		case 'B': goto yy287;
		case 'D': goto yy288;
		case 'F': goto yy289;
		case 'I': goto yy290;
		case 'S': goto yy291;
		case 'U': goto yy292;
		case 'W': goto yy293;
		default: goto yy281;
	}
yy280:
	++in->cur;
	{ *len = 0; return in->tok == in->lim - YYMAXFILL ? 100 : -1; }
yy281:
	++in->cur;
	{ *len = (size_t)(in->cur - in->tok); return 0; }
yy282:
	++in->cur;
	if (in->lim <= in->cur) if (fill(in, 1) != 0) return -1;
	yych = *in->cur;
	switch (yych) {
		case ' ': goto yy282;
		default: goto yy283;
	}
yy283:
	{ *len = (size_t)(in->cur - in->tok); return 10; }
yy284:
	++in->cur;
	if (in->lim <= in->cur) if (fill(in, 1) != 0) return -1;
	yych = *in->cur;
yy285:
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy284;
		default: goto yy286;
	}
yy286:
	{ *len = (size_t)(in->cur - in->tok); return 9; }
yy287:
	yych = *++in->cur;
	switch (yych) {
		case 'E': goto yy294;
		default: goto yy285;
	}
yy288:
	yych = *++in->cur;
	switch (yych) {
		case 'E': goto yy295;
		case 'I': goto yy296;
		default: goto yy285;
	}
yy289:
	yych = *++in->cur;
	switch (yych) {
		case 'R': goto yy297;
		default: goto yy285;
	}
yy290:
	yych = *++in->cur;
	switch (yych) {
		case 'N': goto yy298;
		default: goto yy285;
	}
yy291:
	yych = *++in->cur;
	switch (yych) {
		case 'E': goto yy299;
		default: goto yy285;
	}
yy292:
	yych = *++in->cur;
	switch (yych) {
		case 'P': goto yy300;
		default: goto yy285;
	}
yy293:
	yych = *++in->cur;
	switch (yych) {
		case 'H': goto yy301;
		default: goto yy285;
	}
yy294:
	yych = *++in->cur;
	switch (yych) {
		case 'T': goto yy302;
		default: goto yy285;
	}
yy295:
	yych = *++in->cur;
	switch (yych) {
		case 'L': goto yy303;
		default: goto yy285;
	}
yy296:
	yych = *++in->cur;
	switch (yych) {
		case 'S': goto yy304;
		default: goto yy285;
	}
yy297:
	yych = *++in->cur;
	switch (yych) {
		case 'O': goto yy305;
		default: goto yy285;
	}
yy298:
	yych = *++in->cur;
	switch (yych) {
		case 'S': goto yy306;
		default: goto yy285;
	}
yy299:
	yych = *++in->cur;
	switch (yych) {
		case 'L': goto yy307;
		default: goto yy285;
	}
yy300:
	yych = *++in->cur;
	switch (yych) {
		case 'D': goto yy308;
		default: goto yy285;
	}
yy301:
	yych = *++in->cur;
	switch (yych) {
		case 'E': goto yy309;
		default: goto yy285;
	}
yy302:
	yych = *++in->cur;
	switch (yych) {
		case 'W': goto yy310;
		default: goto yy285;
	}
yy303:
	yych = *++in->cur;
	switch (yych) {
		case 'E': goto yy311;
		default: goto yy285;
	}
yy304:
	yych = *++in->cur;
	switch (yych) {
		case 'T': goto yy312;
		default: goto yy285;
	}
yy305:
	yych = *++in->cur;
	switch (yych) {
		case 'M': goto yy313;
		default: goto yy285;
	}
yy306:
	yych = *++in->cur;
	switch (yych) {
		case 'E': goto yy315;
		default: goto yy285;
	}
yy307:
	yych = *++in->cur;
	switch (yych) {
		case 'E': goto yy316;
		default: goto yy285;
	}
yy308:
	yych = *++in->cur;
	switch (yych) {
		case 'A': goto yy317;
		default: goto yy285;
	}
yy309:
	yych = *++in->cur;
	switch (yych) {
		case 'R': goto yy318;
		default: goto yy285;
	}
yy310:
	yych = *++in->cur;
	switch (yych) {
		case 'E': goto yy319;
		default: goto yy285;
	}
yy311:
	yych = *++in->cur;
	switch (yych) {
		case 'T': goto yy320;
		default: goto yy285;
	}
yy312:
	yych = *++in->cur;
	switch (yych) {
		case 'I': goto yy321;
		default: goto yy285;
	}
yy313:
	yych = *++in->cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy284;
		default: goto yy314;
	}
yy314:
	{ *len = (size_t)(in->cur - in->tok); return 5; }
yy315:
	yych = *++in->cur;
	switch (yych) {
		case 'R': goto yy322;
		default: goto yy285;
	}
yy316:
	yych = *++in->cur;
	switch (yych) {
		case 'C': goto yy323;
		default: goto yy285;
	}
yy317:
	yych = *++in->cur;
	switch (yych) {
		case 'T': goto yy324;
		default: goto yy285;
	}
yy318:
	yych = *++in->cur;
	switch (yych) {
		case 'E': goto yy325;
		default: goto yy285;
	}
yy319:
	yych = *++in->cur;
	switch (yych) {
		case 'E': goto yy327;
		default: goto yy285;
	}
yy320:
	yych = *++in->cur;
	switch (yych) {
		case 'E': goto yy328;
		default: goto yy285;
	}
yy321:
	yych = *++in->cur;
	switch (yych) {
		case 'N': goto yy330;
		default: goto yy285;
	}
yy322:
	yych = *++in->cur;
	switch (yych) {
		case 'T': goto yy331;
		default: goto yy285;
	}
yy323:
	yych = *++in->cur;
	switch (yych) {
		case 'T': goto yy333;
		default: goto yy285;
	}
yy324:
	yych = *++in->cur;
	switch (yych) {
		case 'E': goto yy335;
		default: goto yy285;
	}
yy325:
	yych = *++in->cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy284;
		default: goto yy326;
	}
yy326:
	{ *len = (size_t)(in->cur - in->tok); return 6; }
yy327:
	yych = *++in->cur;
	switch (yych) {
		case 'N': goto yy337;
		default: goto yy285;
	}
yy328:
	yych = *++in->cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy284;
		default: goto yy329;
	}
yy329:
	{ *len = (size_t)(in->cur - in->tok); return 4; }
yy330:
	yych = *++in->cur;
	switch (yych) {
		case 'C': goto yy339;
		default: goto yy285;
	}
yy331:
	yych = *++in->cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy284;
		default: goto yy332;
	}
yy332:
	{ *len = (size_t)(in->cur - in->tok); return 2; }
yy333:
	yych = *++in->cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy284;
		default: goto yy334;
	}
yy334:
	{ *len = (size_t)(in->cur - in->tok); return 1; }
yy335:
	yych = *++in->cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy284;
		default: goto yy336;
	}
yy336:
	{ *len = (size_t)(in->cur - in->tok); return 3; }
yy337:
	yych = *++in->cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy284;
		default: goto yy338;
	}
yy338:
	{ *len = (size_t)(in->cur - in->tok); return 7; }
yy339:
	yych = *++in->cur;
	switch (yych) {
		case 'T': goto yy340;
		default: goto yy285;
	}
yy340:
	yych = *++in->cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy284;
		default: goto yy341;
	}
yy341:
	{ *len = (size_t)(in->cur - in->tok); return 8; }
}

}

static const struct word keywords_words[] = {
    {"\x53\x45\x4c\x45\x43\x54", 6},
    {"\x49\x4e\x53\x45\x52\x54", 6},
    {"\x55\x50\x44\x41\x54\x45", 6},
    {"\x44\x45\x4c\x45\x54\x45", 6},
    {"\x46\x52\x4f\x4d", 4},
    {"\x57\x48\x45\x52\x45", 5},
    {"\x42\x45\x54\x57\x45\x45\x4e", 7},
    {"\x44\x49\x53\x54\x49\x4e\x43\x54", 8},
    {"\x53\x45\x4c\x45\x43\x54\x45\x44", 8},
    {"\x44\x49\x53\x54\x49\x4e\x43\x54\x49\x4f\x4e", 11},
    {"\x46\x52\x4f\x4d\x41\x47\x45", 7},
    {"\x57\x48\x45\x52\x45\x41\x53", 7},
    {NULL, 0}
};



static int backtrack_0(Input* in, size_t* len) {
    in->tok = in->cur;
    
{
	unsigned char yych;
	unsigned int yyaccept = 0;
	if ((in->lim - in->cur) < 11) if (fill(in, 11) != 0) return -1;
	yych = *in->cur;
	switch (yych) {
		case 0x00: goto yy343;
		case 'a': goto yy346;
		case 'b': goto yy347;
		case 'q': goto yy348;
		case 'x': goto yy349;
		default: goto yy344;
	}
yy343:
	++in->cur;
	{ *len = 0; return in->tok == in->lim - YYMAXFILL ? 100 : -1; }
yy344:
	++in->cur;
yy345:
	{ *len = (size_t)(in->cur - in->tok); return 0; }
yy346:
	yych = *++in->cur;
	switch (yych) {
		case 'b': goto yy350;
		default: goto yy345;
	}
yy347:
	yyaccept = 0;
	yych = *(in->mar = ++in->cur);
	switch (yych) {
		case 'c': goto yy352;
		default: goto yy345;
	}
yy348:
	yyaccept = 0;
	yych = *(in->mar = ++in->cur);
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy354;
		default: goto yy345;
	}
yy349:
	yyaccept = 0;
	yych = *(in->mar = ++in->cur);
	switch (yych) {
		case 'y': goto yy355;
		default: goto yy345;
	}
yy350:
	yyaccept = 1;
	yych = *(in->mar = ++in->cur);
	switch (yych) {
		case 'c': goto yy356;
		default: goto yy351;
	}
yy351:
	{ *len = (size_t)(in->cur - in->tok); return 1; }
yy352:
	yych = *++in->cur;
	switch (yych) {
		case 'd': goto yy357;
		default: goto yy353;
	}
yy353:
	in->cur = in->mar;
	switch (yyaccept) {
		case 0: goto yy345;
		case 1: goto yy351;
		case 2: goto yy361;
		default: goto yy377;
	}
yy354:
	++in->cur;
	if ((in->lim - in->cur) < 3) if (fill(in, 3) != 0) return -1;
	yych = *in->cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy354;
		case 'e': goto yy358;
		default: goto yy353;
	}
yy355:
	yych = *++in->cur;
	switch (yych) {
		case 'z': goto yy359;
		default: goto yy353;
	}
yy356:
	yych = *++in->cur;
	switch (yych) {
		case 'd': goto yy360;
		case 'x': goto yy362;
		default: goto yy353;
	}
yy357:
	yych = *++in->cur;
	switch (yych) {
		case 'e': goto yy363;
		default: goto yy353;
	}
yy358:
	yych = *++in->cur;
	switch (yych) {
		case 'n': goto yy364;
		default: goto yy353;
	}
yy359:
	yych = *++in->cur;
	switch (yych) {
		case 'z': goto yy365;
		default: goto yy353;
	}
yy360:
	yyaccept = 2;
	yych = *(in->mar = ++in->cur);
	switch (yych) {
		case 'e': goto yy366;
		default: goto yy361;
	}
yy361:
	{ *len = (size_t)(in->cur - in->tok); return 2; }
yy362:
	++in->cur;
	{ *len = (size_t)(in->cur - in->tok); return 5; }
yy363:
	yych = *++in->cur;
	switch (yych) {
		case 'f': goto yy367;
		default: goto yy353;
	}
yy364:
	yych = *++in->cur;
	switch (yych) {
		case 'd': goto yy368;
		default: goto yy353;
	}
yy365:
	yych = *++in->cur;
	switch (yych) {
		case 'y': goto yy369;
		default: goto yy353;
	}
yy366:
	yych = *++in->cur;
	switch (yych) {
		case 'f': goto yy370;
		default: goto yy353;
	}
yy367:
	yych = *++in->cur;
	switch (yych) {
		case 'g': goto yy371;
		default: goto yy353;
	}
yy368:
	++in->cur;
	{ *len = (size_t)(in->cur - in->tok); return 8; }
yy369:
	yych = *++in->cur;
	switch (yych) {
		case 'x': goto yy372;
		default: goto yy353;
	}
yy370:
	yych = *++in->cur;
	switch (yych) {
		case 'g': goto yy373;
		default: goto yy353;
	}
yy371:
	yych = *++in->cur;
	switch (yych) {
		case 'h': goto yy374;
		default: goto yy353;
	}
yy372:
	yych = *++in->cur;
	switch (yych) {
		case 'y': goto yy375;
		default: goto yy353;
	}
yy373:
	yych = *++in->cur;
	switch (yych) {
		case 'h': goto yy376;
		default: goto yy353;
	}
yy374:
	yych = *++in->cur;
	switch (yych) {
		case 'i': goto yy378;
		default: goto yy353;
	}
yy375:
	yych = *++in->cur;
	switch (yych) {
		case 'z': goto yy379;
		default: goto yy353;
	}
yy376:
	yyaccept = 3;
	yych = *(in->mar = ++in->cur);
	switch (yych) {
		case 'i': goto yy380;
		default: goto yy377;
	}
yy377:
	{ *len = (size_t)(in->cur - in->tok); return 3; }
yy378:
	++in->cur;
	{ *len = (size_t)(in->cur - in->tok); return 6; }
yy379:
	yych = *++in->cur;
	switch (yych) {
		case 'z': goto yy381;
		default: goto yy353;
	}
yy380:
	yych = *++in->cur;
	switch (yych) {
		case 'j': goto yy382;
		default: goto yy353;
	}
yy381:
	yych = *++in->cur;
	switch (yych) {
		case 'y': goto yy383;
		default: goto yy353;
	}
yy382:
	yych = *++in->cur;
	switch (yych) {
		case 'k': goto yy384;
		default: goto yy353;
	}
yy383:
	++in->cur;
	{ *len = (size_t)(in->cur - in->tok); return 7; }
yy384:
	++in->cur;
	{ *len = (size_t)(in->cur - in->tok); return 4; }
}

}

static int backtrack_1(Input* in, size_t* len) {
    in->tok = in->cur;
    
{
	unsigned char yych;
	unsigned int yyaccept = 0;
	if ((in->lim - in->cur) < 11) if (fill(in, 11) != 0) return -1;
	yych = *in->cur;
	switch (yych) {
		case 0x00: goto yy386;
		case 'a': goto yy389;
		case 'b': goto yy390;
		case 'q': goto yy391;
		case 'x': goto yy392;
		default: goto yy387;
	}
yy386:
	++in->cur;
	{ *len = 0; return in->tok == in->lim - YYMAXFILL ? 100 : -1; }
yy387:
	++in->cur;
yy388:
	{ *len = (size_t)(in->cur - in->tok); return 0; }
yy389:
	yych = *++in->cur;
	switch (yych) {
		case 'b': goto yy393;
		default: goto yy388;
	}
yy390:
	yyaccept = 0;
	yych = *(in->mar = ++in->cur);
	if (((unsigned long long)(unsigned char)in->cur[0] | (unsigned long long)(unsigned char)in->cur[1] << 8 * 1 | (unsigned long long)(unsigned char)in->cur[2] << 8 * 2 | (unsigned long long)(unsigned char)in->cur[3] << 8 * 3) == 0x66656463) {
		in->cur += 3;
		goto yy410;
	} else {
		switch ((((((((((unsigned long long)(unsigned char)in->cur[0] | (unsigned long long)(unsigned char)in->cur[1] << 8 * 1 | (unsigned long long)(unsigned char)in->cur[2] << 8 * 2 | (unsigned long long)(unsigned char)in->cur[3] << 8 * 3) ^ 0x66656463) - 1) & ~(((unsigned long long)(unsigned char)in->cur[0] | (unsigned long long)(unsigned char)in->cur[1] << 8 * 1 | (unsigned long long)(unsigned char)in->cur[2] << 8 * 2 | (unsigned long long)(unsigned char)in->cur[3] << 8 * 3) ^ 0x66656463)) >> 7) & 0x0101010101010101ULL) * 0x0101010101010101ULL) >> 56)) {
			case 1: goto yy395;
			case 2:
				in->cur += 1;
				goto yy400;
			case 3:
				in->cur += 2;
				goto yy406;
		}
	}
	switch (yych) {
		case 'c': goto yy395;
		default: goto yy388;
	}
yy391:
	yyaccept = 0;
	yych = *(in->mar = ++in->cur);
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy397;
		default: goto yy388;
	}
yy392:
	yyaccept = 0;
	yych = *(in->mar = ++in->cur);
	if (((unsigned long long)(unsigned char)in->cur[0] | (unsigned long long)(unsigned char)in->cur[1] << 8 * 1 | (unsigned long long)(unsigned char)in->cur[2] << 8 * 2 | (unsigned long long)(unsigned char)in->cur[3] << 8 * 3 | (unsigned long long)(unsigned char)in->cur[4] << 8 * 4 | (unsigned long long)(unsigned char)in->cur[5] << 8 * 5 | (unsigned long long)(unsigned char)in->cur[6] << 8 * 6 | (unsigned long long)(unsigned char)in->cur[7] << 8 * 7) == 0x7a7a7978797a7a79) {
		in->cur += 7;
		goto yy424;
	} else {
		switch ((((((((((unsigned long long)(unsigned char)in->cur[0] | (unsigned long long)(unsigned char)in->cur[1] << 8 * 1 | (unsigned long long)(unsigned char)in->cur[2] << 8 * 2 | (unsigned long long)(unsigned char)in->cur[3] << 8 * 3 | (unsigned long long)(unsigned char)in->cur[4] << 8 * 4 | (unsigned long long)(unsigned char)in->cur[5] << 8 * 5 | (unsigned long long)(unsigned char)in->cur[6] << 8 * 6 | (unsigned long long)(unsigned char)in->cur[7] << 8 * 7) ^ 0x7a7a7978797a7a79) - 1) & ~(((unsigned long long)(unsigned char)in->cur[0] | (unsigned long long)(unsigned char)in->cur[1] << 8 * 1 | (unsigned long long)(unsigned char)in->cur[2] << 8 * 2 | (unsigned long long)(unsigned char)in->cur[3] << 8 * 3 | (unsigned long long)(unsigned char)in->cur[4] << 8 * 4 | (unsigned long long)(unsigned char)in->cur[5] << 8 * 5 | (unsigned long long)(unsigned char)in->cur[6] << 8 * 6 | (unsigned long long)(unsigned char)in->cur[7] << 8 * 7) ^ 0x7a7a7978797a7a79)) >> 7) & 0x0101010101010101ULL) * 0x0101010101010101ULL) >> 56)) {
			case 1: goto yy398;
			case 2:
				in->cur += 1;
				goto yy402;
			case 3:
				in->cur += 2;
				goto yy408;
			case 4:
				in->cur += 3;
				goto yy412;
			case 5:
				in->cur += 4;
				goto yy415;
			case 6:
				in->cur += 5;
				goto yy418;
			case 7:
				in->cur += 6;
				goto yy422;
		}
	}
	switch (yych) {
		case 'y': goto yy398;
		default: goto yy388;
	}
yy393:
	yyaccept = 1;
	yych = *(in->mar = ++in->cur);
	switch (yych) {
		case 'c': goto yy399;
		default: goto yy394;
	}
yy394:
	{ *len = (size_t)(in->cur - in->tok); return 1; }
yy395:
	yych = *++in->cur;
	switch (yych) {
		case 'd': goto yy400;
		default: goto yy396;
	}
yy396:
	in->cur = in->mar;
	switch (yyaccept) {
		case 0: goto yy388;
		case 1: goto yy394;
		case 2: goto yy404;
		default: goto yy420;
	}
yy397:
	++in->cur;
	if ((in->lim - in->cur) < 3) if (fill(in, 3) != 0) return -1;
	yych = *in->cur;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy397;
		case 'e': goto yy401;
		default: goto yy396;
	}
yy398:
	yych = *++in->cur;
	switch (yych) {
		case 'z': goto yy402;
		default: goto yy396;
	}
yy399:
	yych = *++in->cur;
	switch (yych) {
		case 'd': goto yy403;
		case 'x': goto yy405;
		default: goto yy396;
	}
yy400:
	yych = *++in->cur;
	switch (yych) {
		case 'e': goto yy406;
		default: goto yy396;
	}
yy401:
	yych = *++in->cur;
	if (((unsigned long long)(unsigned char)in->cur[0] | (unsigned long long)(unsigned char)in->cur[1] << 8 * 1) == 0x646e) {
		in->cur += 1;
		goto yy411;
	} else {
		switch ((((((((((unsigned long long)(unsigned char)in->cur[0] | (unsigned long long)(unsigned char)in->cur[1] << 8 * 1) ^ 0x646e) - 1) & ~(((unsigned long long)(unsigned char)in->cur[0] | (unsigned long long)(unsigned char)in->cur[1] << 8 * 1) ^ 0x646e)) >> 7) & 0x0101010101010101ULL) * 0x0101010101010101ULL) >> 56)) {
			case 1: goto yy407;
		}
	}
	switch (yych) {
		case 'n': goto yy407;
		default: goto yy396;
	}
yy402:
	yych = *++in->cur;
	switch (yych) {
		case 'z': goto yy408;
		default: goto yy396;
	}
yy403:
	yyaccept = 2;
	yych = *(in->mar = ++in->cur);
	if (((unsigned long long)(unsigned char)in->cur[0] | (unsigned long long)(unsigned char)in->cur[1] << 8 * 1 | (unsigned long long)(unsigned char)in->cur[2] << 8 * 2 | (unsigned long long)(unsigned char)in->cur[3] << 8 * 3) == 0x68676665) {
		in->cur += 3;
		goto yy419;
	} else {
		switch ((((((((((unsigned long long)(unsigned char)in->cur[0] | (unsigned long long)(unsigned char)in->cur[1] << 8 * 1 | (unsigned long long)(unsigned char)in->cur[2] << 8 * 2 | (unsigned long long)(unsigned char)in->cur[3] << 8 * 3) ^ 0x68676665) - 1) & ~(((unsigned long long)(unsigned char)in->cur[0] | (unsigned long long)(unsigned char)in->cur[1] << 8 * 1 | (unsigned long long)(unsigned char)in->cur[2] << 8 * 2 | (unsigned long long)(unsigned char)in->cur[3] << 8 * 3) ^ 0x68676665)) >> 7) & 0x0101010101010101ULL) * 0x0101010101010101ULL) >> 56)) {
			case 1: goto yy409;
			case 2:
				in->cur += 1;
				goto yy413;
			case 3:
				in->cur += 2;
				goto yy416;
		}
	}
	switch (yych) {
		case 'e': goto yy409;
		default: goto yy404;
	}
yy404:
	{ *len = (size_t)(in->cur - in->tok); return 2; }
yy405:
	++in->cur;
	{ *len = (size_t)(in->cur - in->tok); return 5; }
yy406:
	yych = *++in->cur;
	switch (yych) {
		case 'f': goto yy410;
		default: goto yy396;
	}
yy407:
	yych = *++in->cur;
	switch (yych) {
		case 'd': goto yy411;
		default: goto yy396;
	}
yy408:
	yych = *++in->cur;
	switch (yych) {
		case 'y': goto yy412;
		default: goto yy396;
	}
yy409:
	yych = *++in->cur;
	switch (yych) {
		case 'f': goto yy413;
		default: goto yy396;
	}
yy410:
	yych = *++in->cur;
	if (((unsigned long long)(unsigned char)in->cur[0] | (unsigned long long)(unsigned char)in->cur[1] << 8 * 1) == 0x6867) {
		in->cur += 1;
		goto yy417;
	} else {
		switch ((((((((((unsigned long long)(unsigned char)in->cur[0] | (unsigned long long)(unsigned char)in->cur[1] << 8 * 1) ^ 0x6867) - 1) & ~(((unsigned long long)(unsigned char)in->cur[0] | (unsigned long long)(unsigned char)in->cur[1] << 8 * 1) ^ 0x6867)) >> 7) & 0x0101010101010101ULL) * 0x0101010101010101ULL) >> 56)) {
			case 1: goto yy414;
		}
	}
	switch (yych) {
		case 'g': goto yy414;
		default: goto yy396;
	}
yy411:
	++in->cur;
	{ *len = (size_t)(in->cur - in->tok); return 8; }
yy412:
	yych = *++in->cur;
	switch (yych) {
		case 'x': goto yy415;
		default: goto yy396;
	}
yy413:
	yych = *++in->cur;
	switch (yych) {
		case 'g': goto yy416;
		default: goto yy396;
	}
yy414:
	yych = *++in->cur;
	switch (yych) {
		case 'h': goto yy417;
		default: goto yy396;
	}
yy415:
	yych = *++in->cur;
	switch (yych) {
		case 'y': goto yy418;
		default: goto yy396;
	}
yy416:
	yych = *++in->cur;
	switch (yych) {
		case 'h': goto yy419;
		default: goto yy396;
	}
yy417:
	yych = *++in->cur;
	switch (yych) {
		case 'i': goto yy421;
		default: goto yy396;
	}
yy418:
	yych = *++in->cur;
	switch (yych) {
		case 'z': goto yy422;
		default: goto yy396;
	}
yy419:
	yyaccept = 3;
	yych = *(in->mar = ++in->cur);
	if (((unsigned long long)(unsigned char)in->cur[0] | (unsigned long long)(unsigned char)in->cur[1] << 8 * 1) == 0x6a69) {
		in->cur += 1;
		goto yy425;
	} else {
		switch ((((((((((unsigned long long)(unsigned char)in->cur[0] | (unsigned long long)(unsigned char)in->cur[1] << 8 * 1) ^ 0x6a69) - 1) & ~(((unsigned long long)(unsigned char)in->cur[0] | (unsigned long long)(unsigned char)in->cur[1] << 8 * 1) ^ 0x6a69)) >> 7) & 0x0101010101010101ULL) * 0x0101010101010101ULL) >> 56)) {
			case 1: goto yy423;
		}
	}
	switch (yych) {
		case 'i': goto yy423;
		default: goto yy420;
	}
yy420:
	{ *len = (size_t)(in->cur - in->tok); return 3; }
yy421:
	++in->cur;
	{ *len = (size_t)(in->cur - in->tok); return 6; }
yy422:
	yych = *++in->cur;
	switch (yych) {
		case 'z': goto yy424;
		default: goto yy396;
	}
yy423:
	yych = *++in->cur;
	switch (yych) {
		case 'j': goto yy425;
		default: goto yy396;
	}
yy424:
	yych = *++in->cur;
	switch (yych) {
		case 'y': goto yy426;
		default: goto yy396;
	}
yy425:
	yych = *++in->cur;
	switch (yych) {
		case 'k': goto yy427;
		default: goto yy396;
	}
yy426:
	++in->cur;
	{ *len = (size_t)(in->cur - in->tok); return 7; }
yy427:
	++in->cur;
	{ *len = (size_t)(in->cur - in->tok); return 4; }
}

}

static const struct word backtrack_words[] = {
    {"\x61\x62", 2},
    {"\x61\x62\x63\x64", 4},
    {"\x61\x62\x63\x64\x65\x66\x67\x68", 8},
    {"\x61\x62\x63\x64\x65\x66\x67\x68\x69\x6a\x6b", 11},
    {"\x61\x62\x63\x78", 4},
    {"\x62\x63\x64\x65\x66\x67\x68\x69", 8},
    {"\x78\x79\x7a\x7a\x79\x78\x79\x7a\x7a\x79", 10},
    {"\x71\x31\x32\x33\x65\x6e\x64", 7},
    {"\x61\x62\x63\x64\x65\x66\x67\x68\x69\x6a", 10},
    {"\x78\x79\x7a\x7a\x79\x78\x79\x7a\x7a", 9},
    {NULL, 0}
};

static int failures = 0;

static void run(lex_t f, Input* in, const unsigned char* src, size_t len, size_t bufsize,
        int* rules, size_t* lens, size_t* ntok) {
    in->src = src;
    in->srclen = len;
    in->srcpos = 0;
    in->bufsize = bufsize;
    in->buf = (unsigned char*)malloc(bufsize + YYMAXFILL);
    in->cur = in->tok = in->mar = in->lim = in->buf + bufsize;
    in->eof = 0;
    *ntok = 0;
    for (;;) {
        size_t l = 0;
        const int r = f(in, &l);
        rules[*ntok] = r;
        lens[*ntok] = l;
        ++*ntok;
        if (r == 100 || r == -1) break;
    }
    free(in->buf);
}

static void check_set(lex_t f, lex_t g, const struct word* ws, const char* name) {
    // Build a stream of words, their prefixes and near misses, separated by a few characters.
    static const char seps[] = " :-\t";
    unsigned char* src = (unsigned char*)malloc(1 << 16);
    size_t len = 0, k = 0;
    for (const struct word* w = ws; w->str; ++w) {
        for (size_t i = 1; i <= w->len; ++i) {
            memcpy(src + len, w->str, i);
            len += i;
            src[len++] = (unsigned char)seps[k++ % (sizeof(seps) - 1)];
            memcpy(src + len, w->str, i);
            len += i;
            if (i < w->len) src[len++] = (unsigned char)(w->str[i] + 1);
            src[len++] = (unsigned char)seps[k++ % (sizeof(seps) - 1)];
        }
        for (const struct word* v = ws; v->str; ++v) {
            memcpy(src + len, w->str, w->len);
            len += w->len;
            memcpy(src + len, v->str, v->len);
            len += v->len;
            src[len++] = (unsigned char)seps[k++ % (sizeof(seps) - 1)];
        }
    }
    int* r1 = (int*)malloc(sizeof(int) * (len + 2));
    int* r2 = (int*)malloc(sizeof(int) * (len + 2));
    size_t* l1 = (size_t*)malloc(sizeof(size_t) * (len + 2));
    size_t* l2 = (size_t*)malloc(sizeof(size_t) * (len + 2));
    for (size_t bufsize = 40; bufsize <= 72; ++bufsize) {
        Input in;
        size_t n1, n2;
        run(f, &in, src, len, bufsize, r1, l1, &n1);
        run(g, &in, src, len, bufsize, r2, l2, &n2);
        if (n1 != n2 || r1[n1 - 1] != 100) {
            fprintf(stderr, "%s, buffer %d: %d/%d tokens, last rule %d\n",
                name, (int)bufsize, (int)n1, (int)n2, r1[n1 - 1]);
            ++failures;
            continue;
        }
        for (size_t i = 0; i < n1; ++i) {
            if (r1[i] != r2[i] || l1[i] != l2[i]) {
                fprintf(stderr, "%s, buffer %d, token %d: rule %d/%d, length %d/%d\n",
                    name, (int)bufsize, (int)i, r1[i], r2[i], (int)l1[i], (int)l2[i]);
                ++failures;
                break;
            }
        }
    }
    free(r1); free(r2); free(l1); free(l2); free(src);
}

int main() {
    check_set(headers_0, headers_1, headers_words, "headers");
    check_set(keywords_0, keywords_1, keywords_words, "keywords");
    check_set(backtrack_0, backtrack_1, backtrack_words, "backtrack");
    return failures > 0 ? 1 : 0;
}
