// Code generated by re2go, DO NOT EDIT.
//go:generate re2go $INPUT -o $OUTPUT -i --api simple --vectorize-linear
package main

const (
	hdrOther = iota
	hdrContentLength
	hdrContentType
	hdrTransferEncoding
	hdrConnection
	hdrError
)

// Classify the name of an HTTP header line. Header names are long literals that are
// usually matched to the end, so most of their characters are compared eight at a time.
func header(yyinput string) int {
	yycursor, yymarker := 0, 0
	_ = yymarker

	
{
	var yych byte
	yych = yyinput[yycursor]
	switch (yych) {
	case '-':
		fallthrough
	case 'A','B':
		fallthrough
	case 'D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S':
		fallthrough
	case 'U','V','W','X','Y','Z':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy3
	case 'C':
		goto yy4
	case 'T':
		goto yy5
	default:
		goto yy1
	}
yy1:
	yycursor += 1
yy2:
	{ return hdrError }
yy3:
	yycursor += 1
	yymarker = yycursor
	yych = yyinput[yycursor]
	switch (yych) {
	case '-':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy6
	case ':':
		goto yy9
	default:
		goto yy2
	}
yy4:
	yycursor += 1
	yymarker = yycursor
	yych = yyinput[yycursor]
	switch (yych) {
	case '-':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n':
		fallthrough
	case 'p','q','r','s','t','u','v','w','x','y','z':
		goto yy6
	case ':':
		goto yy9
	case 'o':
		goto yy10
	default:
		goto yy2
	}
yy5:
	yycursor += 1
	yymarker = yycursor
	yych = yyinput[yycursor]
	switch (yych) {
	case '-':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q':
		fallthrough
	case 's','t','u','v','w','x','y','z':
		goto yy6
	case ':':
		goto yy9
	case 'r':
		goto yy11
	default:
		goto yy2
	}
yy6:
	yycursor += 1
	yych = yyinput[yycursor]
yy7:
	switch (yych) {
	case '-':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy6
	case ':':
		goto yy9
	default:
		goto yy8
	}
yy8:
	yycursor = yymarker
	goto yy2
yy9:
	yycursor += 1
	{ return hdrOther }
yy10:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'n':
		goto yy12
	default:
		goto yy7
	}
yy11:
	yycursor += 1
	yych = yyinput[yycursor]
	if (len(yyinput)-yycursor >= 8) {
		if (uint64(yyinput[yycursor:][7])<<(8*7) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) | uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][4])<<(8*4) | uint64(yyinput[yycursor:][5])<<(8*5) | uint64(yyinput[yycursor:][6])<<(8*6) == 0x452d726566736e61) {
			yycursor += 7
			goto yy36
		} else {
			switch (((((((uint64(yyinput[yycursor:][7])<<(8*7) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) | uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][4])<<(8*4) | uint64(yyinput[yycursor:][5])<<(8*5) | uint64(yyinput[yycursor:][6])<<(8*6) ^ 0x452d726566736e61) - 1) &^ (uint64(yyinput[yycursor:][7])<<(8*7) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) | uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][4])<<(8*4) | uint64(yyinput[yycursor:][5])<<(8*5) | uint64(yyinput[yycursor:][6])<<(8*6) ^ 0x452d726566736e61)) >> 7) & 0x0101010101010101) * 0x0101010101010101) >> 56) {
			case 1:
				goto yy13
			case 2:
				yycursor += 1
				goto yy16
			case 3:
				yycursor += 2
				goto yy19
			case 4:
				yycursor += 3
				goto yy22
			case 5:
				yycursor += 4
				goto yy25
			case 6:
				yycursor += 5
				goto yy28
			case 7:
				yycursor += 6
				goto yy32
			}
		}
	}
	switch (yych) {
	case 'a':
		goto yy13
	default:
		goto yy7
	}
yy12:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'n':
		goto yy14
	case 't':
		goto yy15
	default:
		goto yy7
	}
yy13:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'n':
		goto yy16
	default:
		goto yy7
	}
yy14:
	yycursor += 1
	yych = yyinput[yycursor]
	if (len(yyinput)-yycursor >= 4) {
		if (uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) == 0x69746365) {
			yycursor += 3
			goto yy26
		} else {
			switch (((((((uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) ^ 0x69746365) - 1) &^ (uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) ^ 0x69746365)) >> 7) & 0x0101010101010101) * 0x0101010101010101) >> 56) {
			case 1:
				goto yy17
			case 2:
				yycursor += 1
				goto yy20
			case 3:
				yycursor += 2
				goto yy23
			}
		}
	}
	switch (yych) {
	case 'e':
		goto yy17
	default:
		goto yy7
	}
yy15:
	yycursor += 1
	yych = yyinput[yycursor]
	if (len(yyinput)-yycursor >= 4) {
		if (uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) == 0x2d746e65) {
			yycursor += 3
			goto yy27
		} else {
			switch (((((((uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) ^ 0x2d746e65) - 1) &^ (uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) ^ 0x2d746e65)) >> 7) & 0x0101010101010101) * 0x0101010101010101) >> 56) {
			case 1:
				goto yy18
			case 2:
				yycursor += 1
				goto yy21
			case 3:
				yycursor += 2
				goto yy24
			}
		}
	}
	switch (yych) {
	case 'e':
		goto yy18
	default:
		goto yy7
	}
yy16:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 's':
		goto yy19
	default:
		goto yy7
	}
yy17:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'c':
		goto yy20
	default:
		goto yy7
	}
yy18:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'n':
		goto yy21
	default:
		goto yy7
	}
yy19:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'f':
		goto yy22
	default:
		goto yy7
	}
yy20:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 't':
		goto yy23
	default:
		goto yy7
	}
yy21:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 't':
		goto yy24
	default:
		goto yy7
	}
yy22:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'e':
		goto yy25
	default:
		goto yy7
	}
yy23:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'i':
		goto yy26
	default:
		goto yy7
	}
yy24:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case '-':
		goto yy27
	default:
		goto yy7
	}
yy25:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'r':
		goto yy28
	default:
		goto yy7
	}
yy26:
	yycursor += 1
	yych = yyinput[yycursor]
	if (len(yyinput)-yycursor >= 2) {
		if (uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][0]) == 0x6e6f) {
			yycursor += 1
			goto yy33
		} else {
			switch (((((((uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][0]) ^ 0x6e6f) - 1) &^ (uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][0]) ^ 0x6e6f)) >> 7) & 0x0101010101010101) * 0x0101010101010101) >> 56) {
			case 1:
				goto yy29
			}
		}
	}
	switch (yych) {
	case 'o':
		goto yy29
	default:
		goto yy7
	}
yy27:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'L':
		goto yy30
	case 'T':
		goto yy31
	default:
		goto yy7
	}
yy28:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case '-':
		goto yy32
	default:
		goto yy7
	}
yy29:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'n':
		goto yy33
	default:
		goto yy7
	}
yy30:
	yycursor += 1
	yych = yyinput[yycursor]
	if (len(yyinput)-yycursor >= 4) {
		if (uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) == 0x74676e65) {
			yycursor += 3
			goto yy44
		} else {
			switch (((((((uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) ^ 0x74676e65) - 1) &^ (uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) ^ 0x74676e65)) >> 7) & 0x0101010101010101) * 0x0101010101010101) >> 56) {
			case 1:
				goto yy34
			case 2:
				yycursor += 1
				goto yy38
			case 3:
				yycursor += 2
				goto yy41
			}
		}
	}
	switch (yych) {
	case 'e':
		goto yy34
	default:
		goto yy7
	}
yy31:
	yycursor += 1
	yych = yyinput[yycursor]
	if (len(yyinput)-yycursor >= 4) {
		if (uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) == 0x3a657079) {
			yycursor += 3
			goto yy45
		} else {
			switch (((((((uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) ^ 0x3a657079) - 1) &^ (uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) ^ 0x3a657079)) >> 7) & 0x0101010101010101) * 0x0101010101010101) >> 56) {
			case 1:
				goto yy35
			case 2:
				yycursor += 1
				goto yy39
			case 3:
				yycursor += 2
				goto yy42
			}
		}
	}
	switch (yych) {
	case 'y':
		goto yy35
	default:
		goto yy7
	}
yy32:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'E':
		goto yy36
	default:
		goto yy7
	}
yy33:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case ':':
		goto yy37
	default:
		goto yy7
	}
yy34:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'n':
		goto yy38
	default:
		goto yy7
	}
yy35:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'p':
		goto yy39
	default:
		goto yy7
	}
yy36:
	yycursor += 1
	yych = yyinput[yycursor]
	if (len(yyinput)-yycursor >= 8) {
		if (uint64(yyinput[yycursor:][7])<<(8*7) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) | uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][4])<<(8*4) | uint64(yyinput[yycursor:][5])<<(8*5) | uint64(yyinput[yycursor:][6])<<(8*6) == 0x3a676e69646f636e) {
			yycursor += 7
			goto yy53
		} else {
			switch (((((((uint64(yyinput[yycursor:][7])<<(8*7) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) | uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][4])<<(8*4) | uint64(yyinput[yycursor:][5])<<(8*5) | uint64(yyinput[yycursor:][6])<<(8*6) ^ 0x3a676e69646f636e) - 1) &^ (uint64(yyinput[yycursor:][7])<<(8*7) | uint64(yyinput[yycursor:][0]) | uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][2])<<(8*2) | uint64(yyinput[yycursor:][3])<<(8*3) | uint64(yyinput[yycursor:][4])<<(8*4) | uint64(yyinput[yycursor:][5])<<(8*5) | uint64(yyinput[yycursor:][6])<<(8*6) ^ 0x3a676e69646f636e)) >> 7) & 0x0101010101010101) * 0x0101010101010101) >> 56) {
			case 1:
				goto yy40
			case 2:
				yycursor += 1
				goto yy43
			case 3:
				yycursor += 2
				goto yy46
			case 4:
				yycursor += 3
				goto yy48
			case 5:
				yycursor += 4
				goto yy50
			case 6:
				yycursor += 5
				goto yy51
			case 7:
				yycursor += 6
				goto yy52
			}
		}
	}
	switch (yych) {
	case 'n':
		goto yy40
	default:
		goto yy7
	}
yy37:
	yycursor += 1
	{ return hdrConnection }
yy38:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'g':
		goto yy41
	default:
		goto yy7
	}
yy39:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'e':
		goto yy42
	default:
		goto yy7
	}
yy40:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'c':
		goto yy43
	default:
		goto yy7
	}
yy41:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 't':
		goto yy44
	default:
		goto yy7
	}
yy42:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case ':':
		goto yy45
	default:
		goto yy7
	}
yy43:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'o':
		goto yy46
	default:
		goto yy7
	}
yy44:
	yycursor += 1
	yych = yyinput[yycursor]
	if (len(yyinput)-yycursor >= 2) {
		if (uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][0]) == 0x3a68) {
			yycursor += 1
			goto yy49
		} else {
			switch (((((((uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][0]) ^ 0x3a68) - 1) &^ (uint64(yyinput[yycursor:][1])<<(8*1) | uint64(yyinput[yycursor:][0]) ^ 0x3a68)) >> 7) & 0x0101010101010101) * 0x0101010101010101) >> 56) {
			case 1:
				goto yy47
			}
		}
	}
	switch (yych) {
	case 'h':
		goto yy47
	default:
		goto yy7
	}
yy45:
	yycursor += 1
	{ return hdrContentType }
yy46:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'd':
		goto yy48
	default:
		goto yy7
	}
yy47:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case ':':
		goto yy49
	default:
		goto yy7
	}
yy48:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'i':
		goto yy50
	default:
		goto yy7
	}
yy49:
	yycursor += 1
	{ return hdrContentLength }
yy50:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'n':
		goto yy51
	default:
		goto yy7
	}
yy51:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'g':
		goto yy52
	default:
		goto yy7
	}
yy52:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case ':':
		goto yy53
	default:
		goto yy7
	}
yy53:
	yycursor += 1
	{ return hdrTransferEncoding }
}

}

func main() {
	assert_eq := func(x, y int) { if x != y { panic("error") } }
	assert_eq(header("Content-Length: 42\r\n"), hdrContentLength)
	assert_eq(header("Content-Type: text/plain\r\n"), hdrContentType)
	assert_eq(header("Transfer-Encoding: chunked\r\n"), hdrTransferEncoding)
	assert_eq(header("Connection: close\r\n"), hdrConnection)
	assert_eq(header("Content-Language: en\r\n"), hdrOther)
	assert_eq(header("Connection-Id: 7\r\n"), hdrOther)
	assert_eq(header("Content\r\n"), hdrError)
	assert_eq(header("\r\n"), hdrError)
}
