// Code generated by re2go, DO NOT EDIT.
//go:generate re2go $INPUT -o $OUTPUT -i --api simple --multi-char
package main

import (
	"encoding/binary"
	"fmt"
)

var curInput string

func YYPEEKN(cur int, n int) uint64 {
	if cur+n > len(curInput) {
		return 0
	}
	var buf [8]byte
	copy(buf[:], curInput[cur:cur+n])
	return binary.LittleEndian.Uint64(buf[:])
}

const (
	TokUnknown = 0
	TokSelect  = 1
	TokInsert  = 2
	TokUpdate  = 3
	TokDelete  = 4
	TokFrom    = 5
	TokWhere   = 6
)

// LexKeyword reconnaît un mot-clé isolé terminé par une sentinelle nulle.
func LexKeyword(yyinput string) int {
	curInput = yyinput
	var yycursor int
	var yymarker int

	
{
	var yych byte
	yych = yyinput[yycursor]
	switch (yych) {
	case 'D':
		goto yy3
	case 'F':
		goto yy4
	case 'I':
		goto yy5
	case 'S':
		goto yy6
	case 'U':
		goto yy7
	case 'W':
		goto yy8
	default:
		goto yy1
	}
yy1:
	yycursor += 1
yy2:
	{ return TokUnknown }
yy3:
	yycursor += 1
	yymarker = yycursor
	yych = yyinput[yycursor]
	switch (yych) {
	case 'E':
		goto yy9
	default:
		goto yy2
	}
yy4:
	yycursor += 1
	yymarker = yycursor
	yych = yyinput[yycursor]
	switch (yych) {
	case 'R':
		goto yy11
	default:
		goto yy2
	}
yy5:
	yycursor += 1
	yymarker = yycursor
	yych = yyinput[yycursor]
	switch (yych) {
	case 'N':
		goto yy12
	default:
		goto yy2
	}
yy6:
	yycursor += 1
	yymarker = yycursor
	yych = yyinput[yycursor]
	switch (yych) {
	case 'E':
		goto yy13
	default:
		goto yy2
	}
yy7:
	yycursor += 1
	yymarker = yycursor
	yych = yyinput[yycursor]
	switch (yych) {
	case 'P':
		goto yy14
	default:
		goto yy2
	}
yy8:
	yycursor += 1
	yymarker = yycursor
	yych = yyinput[yycursor]
	switch (yych) {
	case 'H':
		goto yy15
	default:
		goto yy2
	}
yy9:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (YYPEEKN(yycursor, 4)) {
	case 0x4554454c:
		yycursor += 3
		goto yy34
	default:
		switch (yych) {
		case 'L':
			goto yy16
		default:
			goto yy10
		}
	}
yy10:
	yycursor = yymarker
	goto yy2
yy11:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (YYPEEKN(yycursor, 2)) {
	case 0x4d4f:
		yycursor += 1
		goto yy23
	default:
		switch (yych) {
		case 'O':
			goto yy17
		default:
			goto yy10
		}
	}
yy12:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (YYPEEKN(yycursor, 4)) {
	case 0x54524553:
		yycursor += 3
		goto yy35
	default:
		switch (yych) {
		case 'S':
			goto yy18
		default:
			goto yy10
		}
	}
yy13:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (YYPEEKN(yycursor, 4)) {
	case 0x5443454c:
		yycursor += 3
		goto yy36
	default:
		switch (yych) {
		case 'L':
			goto yy19
		default:
			goto yy10
		}
	}
yy14:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (YYPEEKN(yycursor, 4)) {
	case 0x45544144:
		yycursor += 3
		goto yy37
	default:
		switch (yych) {
		case 'D':
			goto yy20
		default:
			goto yy10
		}
	}
yy15:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (YYPEEKN(yycursor, 2)) {
	case 0x5245:
		yycursor += 1
		goto yy27
	default:
		switch (yych) {
		case 'E':
			goto yy21
		default:
			goto yy10
		}
	}
yy16:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (YYPEEKN(yycursor, 2)) {
	case 0x5445:
		yycursor += 1
		goto yy28
	default:
		switch (yych) {
		case 'E':
			goto yy22
		default:
			goto yy10
		}
	}
yy17:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'M':
		goto yy23
	default:
		goto yy10
	}
yy18:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (YYPEEKN(yycursor, 2)) {
	case 0x5245:
		yycursor += 1
		goto yy30
	default:
		switch (yych) {
		case 'E':
			goto yy24
		default:
			goto yy10
		}
	}
yy19:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (YYPEEKN(yycursor, 2)) {
	case 0x4345:
		yycursor += 1
		goto yy31
	default:
		switch (yych) {
		case 'E':
			goto yy25
		default:
			goto yy10
		}
	}
yy20:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (YYPEEKN(yycursor, 2)) {
	case 0x5441:
		yycursor += 1
		goto yy32
	default:
		switch (yych) {
		case 'A':
			goto yy26
		default:
			goto yy10
		}
	}
yy21:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (YYPEEKN(yycursor, 2)) {
	case 0x4552:
		yycursor += 1
		goto yy33
	default:
		switch (yych) {
		case 'R':
			goto yy27
		default:
			goto yy10
		}
	}
yy22:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (YYPEEKN(yycursor, 2)) {
	case 0x4554:
		yycursor += 1
		goto yy34
	default:
		switch (yych) {
		case 'T':
			goto yy28
		default:
			goto yy10
		}
	}
yy23:
	yycursor += 1
	yych = yyinput[yycursor]
	if (yych <= 0x00) {
		goto yy29
	}
	goto yy10
yy24:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (YYPEEKN(yycursor, 2)) {
	case 0x5452:
		yycursor += 1
		goto yy35
	default:
		switch (yych) {
		case 'R':
			goto yy30
		default:
			goto yy10
		}
	}
yy25:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (YYPEEKN(yycursor, 2)) {
	case 0x5443:
		yycursor += 1
		goto yy36
	default:
		switch (yych) {
		case 'C':
			goto yy31
		default:
			goto yy10
		}
	}
yy26:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (YYPEEKN(yycursor, 2)) {
	case 0x4554:
		yycursor += 1
		goto yy37
	default:
		switch (yych) {
		case 'T':
			goto yy32
		default:
			goto yy10
		}
	}
yy27:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'E':
		goto yy33
	default:
		goto yy10
	}
yy28:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'E':
		goto yy34
	default:
		goto yy10
	}
yy29:
	yycursor += 1
	{ return TokFrom }
yy30:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'T':
		goto yy35
	default:
		goto yy10
	}
yy31:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'T':
		goto yy36
	default:
		goto yy10
	}
yy32:
	yycursor += 1
	yych = yyinput[yycursor]
	switch (yych) {
	case 'E':
		goto yy37
	default:
		goto yy10
	}
yy33:
	yycursor += 1
	yych = yyinput[yycursor]
	if (yych <= 0x00) {
		goto yy38
	}
	goto yy10
yy34:
	yycursor += 1
	yych = yyinput[yycursor]
	if (yych <= 0x00) {
		goto yy39
	}
	goto yy10
yy35:
	yycursor += 1
	yych = yyinput[yycursor]
	if (yych <= 0x00) {
		goto yy40
	}
	goto yy10
yy36:
	yycursor += 1
	yych = yyinput[yycursor]
	if (yych <= 0x00) {
		goto yy41
	}
	goto yy10
yy37:
	yycursor += 1
	yych = yyinput[yycursor]
	if (yych <= 0x00) {
		goto yy42
	}
	goto yy10
yy38:
	yycursor += 1
	{ return TokWhere }
yy39:
	yycursor += 1
	{ return TokDelete }
yy40:
	yycursor += 1
	{ return TokInsert }
yy41:
	yycursor += 1
	{ return TokSelect }
yy42:
	yycursor += 1
	{ return TokUpdate }
}

}

func main() {
	fmt.Printf("SELECT -> %d\n", LexKeyword("SELECT\x00"))
	fmt.Printf("FROM   -> %d\n", LexKeyword("FROM\x00"))
}
